import AsyncStorage from "@react-native-async-storage/async-storage";
import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { theme } from "@/constants/theme";

type Category={id:string;name:string;description:string|null;image_url:string|null;sort_order:number;is_active:boolean};
const API_URL=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,"");

export default function AdminCategories(){
 const [items,setItems]=useState<Category[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[name,setName]=useState(""),[description,setDescription]=useState(""),[message,setMessage]=useState("");
 const token=async()=>AsyncStorage.getItem("auth_token");
 const load=async()=>{try{const t=await token();if(!t||!API_URL)throw new Error("رابط الخادم غير مضبوط");const r=await fetch(`${API_URL}/api/categories/all`,{headers:{Authorization:`Bearer ${t}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر تحميل التصنيفات");setItems(d.categories||[])}catch(e){setMessage(e instanceof Error?e.message:"تعذر تحميل التصنيفات")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const add=async()=>{if(!name.trim())return setMessage("اكتب اسم التصنيف أولًا");try{setSaving(true);setMessage("");const t=await token();const r=await fetch(`${API_URL}/api/categories`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({name:name.trim(),description:description.trim()||null})});const d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر إضافة التصنيف");setItems(x=>[d.category,...x]);setName("");setDescription("");setMessage("تمت إضافة التصنيف") }catch(e){setMessage(e instanceof Error?e.message:"تعذر إضافة التصنيف")}finally{setSaving(false)}};
 const toggle=async(c:Category)=>{try{const t=await token();const r=await fetch(`${API_URL}/api/categories/${c.id}`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({isActive:!c.is_active})});const d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر تحديث التصنيف");setItems(x=>x.map(i=>i.id===c.id?d.category:i))}catch(e){setMessage(e instanceof Error?e.message:"تعذر تحديث التصنيف")}};
 const remove=(c:Category)=>Alert.alert("حذف التصنيف",`هل تريد إخفاء «${c.name}» من التطبيق؟`,[{text:"إلغاء",style:"cancel"},{text:"حذف",style:"destructive",onPress:async()=>{try{const t=await token();const r=await fetch(`${API_URL}/api/categories/${c.id}`,{method:"DELETE",headers:{Authorization:`Bearer ${t}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر حذف التصنيف");setItems(x=>x.map(i=>i.id===c.id?{...i,is_active:false}:i))}catch(e){setMessage(e instanceof Error?e.message:"تعذر حذف التصنيف")}}}]);
 if(loading)return <View style={styles.loading}><ActivityIndicator size="large" color={theme.primary}/><Text style={styles.muted}>جاري تحميل التصنيفات...</Text></View>;
 return <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
  <Text style={styles.title}>التصنيفات</Text><Text style={styles.subtitle}>رتّب أقسام المطاعم اللي بتظهر للعملاء، وخفي أي تصنيف من غير ما تحذف بياناته.</Text>
  <View style={styles.form}><Text style={styles.formTitle}>إضافة تصنيف جديد</Text><TextInput value={name} onChangeText={setName} placeholder="اسم التصنيف" placeholderTextColor="#8C8C8C" style={styles.input} textAlign="right"/><TextInput value={description} onChangeText={setDescription} placeholder="وصف مختصر (اختياري)" placeholderTextColor="#8C8C8C" style={[styles.input,styles.textarea]} multiline textAlign="right"/><Pressable disabled={saving} onPress={add} style={[styles.add,saving&&styles.disabled]}>{saving?<ActivityIndicator color="#fff"/>:<Text style={styles.addText}>إضافة التصنيف</Text>}</Pressable></View>
  {!!message&&<Text style={styles.message}>{message}</Text>}
  <Text style={styles.section}>كل التصنيفات</Text>
  {items.map(c=><View key={c.id} style={[styles.card,!c.is_active&&styles.inactive]}><View style={styles.actions}><Pressable onPress={()=>toggle(c)} style={styles.small}><Text style={styles.smallText}>{c.is_active?"إخفاء":"إظهار"}</Text></Pressable><Pressable onPress={()=>remove(c)} style={[styles.small,styles.delete]}><Text style={styles.deleteText}>حذف</Text></Pressable></View><View style={styles.body}><Text style={styles.name}>{c.name}</Text>{c.description?<Text style={styles.desc}>{c.description}</Text>:null}<Text style={styles.status}>{c.is_active?"نشط":"مخفي"} · ترتيب {c.sort_order}</Text></View></View>)}
  {!items.length&&<View style={styles.empty}><Text style={styles.emptyText}>لا توجد تصنيفات حتى الآن.</Text></View>}
 </ScrollView>
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:theme.background},content:{padding:20,paddingTop:55,paddingBottom:45},title:{color:theme.text,fontSize:29,fontWeight:"900",textAlign:"right"},subtitle:{color:theme.muted,lineHeight:22,textAlign:"right",marginTop:7,marginBottom:18},form:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:18,padding:15},formTitle:{color:theme.text,fontSize:16,fontWeight:"900",textAlign:"right",marginBottom:10},input:{minHeight:48,borderWidth:1,borderColor:theme.border,borderRadius:13,paddingHorizontal:13,color:theme.text,backgroundColor:theme.background,fontSize:14,marginBottom:9},textarea:{minHeight:82,paddingTop:12},add:{minHeight:50,borderRadius:14,backgroundColor:theme.primary,alignItems:"center",justifyContent:"center"},addText:{color:"#fff",fontSize:15,fontWeight:"900"},disabled:{opacity:.55},message:{color:theme.text,textAlign:"right",fontSize:12,marginTop:10},section:{color:theme.text,fontSize:19,fontWeight:"900",textAlign:"right",marginTop:24,marginBottom:10},card:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:17,padding:14,marginBottom:9,flexDirection:"row-reverse",alignItems:"center"},inactive:{opacity:.58},body:{flex:1},name:{color:theme.text,fontSize:16,fontWeight:"900",textAlign:"right"},desc:{color:theme.muted,fontSize:12,textAlign:"right",marginTop:4,lineHeight:18},status:{color:theme.muted,fontSize:10,textAlign:"right",marginTop:7},actions:{width:78,marginLeft:10,gap:7},small:{borderWidth:1,borderColor:theme.border,borderRadius:10,minHeight:34,alignItems:"center",justifyContent:"center",backgroundColor:theme.background},smallText:{color:theme.text,fontSize:11,fontWeight:"800"},delete:{borderColor:"#E5B8B8"},deleteText:{color:"#B42318",fontSize:11,fontWeight:"800"},empty:{padding:25,alignItems:"center"},emptyText:{color:theme.muted},loading:{flex:1,backgroundColor:theme.background,alignItems:"center",justifyContent:"center",gap:12},muted:{color:theme.muted,fontSize:13}});
