import AsyncStorage from '@react-native-async-storage/async-storage';
import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { theme } from '@/constants/theme';
import { SafeAreaView } from 'react-native-safe-area-context';

const API=(process.env.EXPO_PUBLIC_API_URL||'').replace(/\/$/,'');
const readJson=async(r:Response)=>{const text=await r.text();try{return JSON.parse(text)}catch{return {error:`تعذر قراءة رد الخادم (HTTP ${r.status})`}}};

export default function CustomerAccounts(){
 const [users,setUsers]=useState<any[]>([]),[values,setValues]=useState<Record<string,string>>({}),[notes,setNotes]=useState<Record<string,string>>({}),[mode,setMode]=useState<Record<string,string>>({});
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState(''),[q,setQ]=useState('');
 const token=()=>AsyncStorage.getItem('auth_token');
 const load=async()=>{try{setLoading(true);setError('');const r=await fetch(API+'/api/admin/wallets',{headers:{Authorization:`Bearer ${await token()}`}}),d=await readJson(r);if(!r.ok)throw Error(d.error||'تعذر تحميل حسابات العملاء');setUsers(Array.isArray(d.customers)?d.customers:[])}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل حسابات العملاء')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>{const s=q.trim().toLowerCase();return !s?users:users.filter(u=>String(u.full_name||'').toLowerCase().includes(s)||String(u.phone||'').includes(s))},[users,q]);
 const adjust=async(u:any)=>{const amount=Number(values[u.id]);if(!Number.isFinite(amount)||amount<=0)return setError('اكتب مبلغًا صحيحًا');const type=mode[u.id]||'credit';const note=String(notes[u.id]||'').trim();if(!note)return setError('اكتب سبب العملية حتى يظهر في سجل المراجعة');
  try{setBusy(u.id);setError('');const r=await fetch(API+'/api/financial/wallet/adjust',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await token()}`},body:JSON.stringify({userId:u.id,amount,type,note})});const d=await readJson(r);if(!r.ok)throw Error(d.error||'تعذر تعديل الرصيد');Alert.alert('تم',`الرصيد الجديد: ${Number(d.balance).toFixed(2)} ج.م`);setValues(x=>({...x,[u.id]:''}));setNotes(x=>({...x,[u.id]:''}));load()}catch(e){setError(e instanceof Error?e.message:'تعذر تعديل الرصيد')}finally{setBusy(null)}
 };
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
  <View style={s.head}><Pressable onPress={()=>router.replace('/admin/operations')} style={s.back}><Text style={s.backText}>←</Text></Pressable><View style={{flex:1}}><Text style={s.title}>حسابات العملاء والمحافظ</Text><Text style={s.sub}>ابحث عن العميل، راجع رصيده، ثم أضف أو اخصم مع تسجيل سبب العملية.</Text></View></View>
  <TextInput value={q} onChangeText={setQ} placeholder="بحث بالاسم أو رقم الهاتف" placeholderTextColor={theme.muted} style={s.search} textAlign="right"/>
  {error?<View style={s.errorBox}><Text style={s.error}>{error}</Text></View>:null}
  {loading?<View style={s.loading}><ActivityIndicator color={theme.primary}/><Text style={s.sub}>جاري تحميل الحسابات...</Text></View>:!visible.length?<View style={s.empty}><Text style={s.emptyTitle}>{users.length?'لا توجد نتيجة مطابقة':'لا توجد حسابات عملاء حتى الآن'}</Text><Text style={s.sub}>{users.length?'جرّب البحث باسم مختلف.':'ستظهر هنا الحسابات بعد إنشاء العملاء.'}</Text></View>:visible.map(u=><View key={u.id} style={s.card}><Text style={s.name}>{u.full_name||'بدون اسم'}</Text><Text style={s.phone}>{u.phone||'بدون رقم'}</Text><Text style={s.balance}>الرصيد: {Number(u.balance||0).toFixed(2)} ج.م • {Number(u.transactions_count||0)} عملية</Text>
   <View style={s.modes}><Pressable onPress={()=>setMode(x=>({...x,[u.id]:'credit'}))} style={[s.mode,(mode[u.id]||'credit')==='credit'&&s.credit]}><Text style={(mode[u.id]||'credit')==='credit'?s.onText:s.mt}>إضافة رصيد</Text></Pressable><Pressable onPress={()=>setMode(x=>({...x,[u.id]:'debit'}))} style={[s.mode,mode[u.id]==='debit'&&s.debit]}><Text style={mode[u.id]==='debit'?s.onText:s.mt}>خصم رصيد</Text></Pressable></View>
   <TextInput value={values[u.id]||''} onChangeText={v=>setValues(x=>({...x,[u.id]:v}))} keyboardType="decimal-pad" placeholder="المبلغ" placeholderTextColor={theme.muted} style={s.input} textAlign="right"/>
   <TextInput value={notes[u.id]||''} onChangeText={v=>setNotes(x=>({...x,[u.id]:v}))} placeholder="سبب العملية — إلزامي" placeholderTextColor={theme.muted} style={s.input} textAlign="right"/>
   <Pressable disabled={busy===u.id} onPress={()=>adjust(u)} style={[s.primary,busy===u.id&&s.disabled]}><Text style={s.btn}>{busy===u.id?'جاري الحفظ...':'حفظ العملية'}</Text></Pressable>
  </View>)}
 </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({
 safe:{flex:1,backgroundColor:theme.background},content:{padding:18,paddingBottom:112},head:{flexDirection:'row-reverse',alignItems:'center',gap:10,marginBottom:14},back:{width:44,height:44,borderRadius:14,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,alignItems:'center',justifyContent:'center'},backText:{fontSize:22,color:theme.text},title:{fontSize:25,fontWeight:'900',color:theme.text,textAlign:'right'},sub:{color:theme.muted,textAlign:'right',fontSize:10,lineHeight:16,marginTop:4},search:{height:47,borderWidth:1,borderColor:theme.border,borderRadius:13,backgroundColor:theme.surface,color:theme.text,paddingHorizontal:12},card:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:18,padding:14,marginTop:10},name:{color:theme.text,fontWeight:'900',fontSize:16,textAlign:'right'},phone:{color:theme.muted,textAlign:'right',fontSize:10,marginTop:3},balance:{color:theme.primary,fontWeight:'900',textAlign:'right',marginTop:7,fontSize:11},modes:{flexDirection:'row-reverse',gap:7,marginTop:10},mode:{flex:1,padding:10,borderRadius:11,borderWidth:1,borderColor:theme.border,alignItems:'center',backgroundColor:theme.background},credit:{backgroundColor:theme.success,borderColor:theme.success},debit:{backgroundColor:theme.danger,borderColor:theme.danger},mt:{color:theme.text,fontWeight:'800',fontSize:11},onText:{color:'#fff',fontWeight:'900',fontSize:11},input:{backgroundColor:theme.background,borderWidth:1,borderColor:theme.border,borderRadius:12,padding:11,color:theme.text,marginTop:8,textAlign:'right'},primary:{height:45,borderRadius:12,backgroundColor:theme.primary,alignItems:'center',justifyContent:'center',marginTop:9},btn:{color:'#fff',fontWeight:'900'},disabled:{opacity:.6},errorBox:{backgroundColor:theme.dangerSoft,borderRadius:13,padding:10,marginTop:9},error:{color:theme.danger,textAlign:'right',fontSize:10},loading:{alignItems:'center',paddingVertical:35,gap:8},empty:{alignItems:'center',paddingVertical:35,backgroundColor:theme.surface,borderRadius:18,marginTop:10},emptyTitle:{color:theme.text,fontWeight:'900'}
});