import AsyncStorage from "@react-native-async-storage/async-storage";
import { useEffect, useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from "react-native";
import { theme } from "@/constants/theme";
const API_URL=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,"");
type Summary={orders:number;gross:string|number;delivery_fees:string|number;activeDrivers:number};
type Driver={id:string;full_name:string;phone:string;status:string;delivered_orders:number;delivery_earnings:string|number;handled_value:string|number};
export default function AdminFinance(){
 const [summary,setSummary]=useState<Summary|null>(null),[drivers,setDrivers]=useState<Driver[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{(async()=>{try{const token=await AsyncStorage.getItem("auth_token");if(!token||!API_URL)throw new Error("رابط الخادم غير مضبوط");const h={Authorization:`Bearer ${token}`};const [a,b]=await Promise.all([fetch(`${API_URL}/api/admin/finance/summary`,{headers:h}),fetch(`${API_URL}/api/admin/finance/drivers`,{headers:h})]);const ad=await a.json(),bd=await b.json();if(!a.ok)throw new Error(ad.error||"تعذر تحميل الملخص المالي");if(!b.ok)throw new Error(bd.error||"تعذر تحميل حسابات المندوبين");setSummary(ad.summary);setDrivers(bd.drivers||[])}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل البيانات")}finally{setLoading(false)}})()},[]);
 if(loading)return <View style={s.loading}><ActivityIndicator size="large" color={theme.primary}/><Text style={s.muted}>جاري تحميل المالية...</Text></View>;
 return <ScrollView style={s.page} contentContainerStyle={s.content}><Text style={s.title}>المالية والتقارير</Text><Text style={s.subtitle}>ملخص الطلبات المكتملة وأداء المندوبين. التسويات النقدية الفعلية تضاف لاحقًا مع سجل الدفعات.</Text>{error?<Text style={s.error}>{error}</Text>:null}<View style={s.grid}><Card title="الطلبات المكتملة" value={String(summary?.orders??0)}/><Card title="إجمالي قيمة الطلبات" value={`${Number(summary?.gross||0).toFixed(2)} ج.م`}/><Card title="رسوم التوصيل" value={`${Number(summary?.delivery_fees||0).toFixed(2)} ج.م`}/><Card title="مندوبون نشطون" value={String(summary?.activeDrivers??0)}/></View><Text style={s.section}>حسابات المندوبين</Text>{drivers.map(d=><View key={d.id} style={s.driver}><View><Text style={s.name}>{d.full_name}</Text><Text style={s.meta}>{d.phone||"بدون رقم"} • {d.status}</Text></View><View style={s.amount}><Text style={s.earn}>{Number(d.delivery_earnings||0).toFixed(2)} ج.م</Text><Text style={s.meta}>{d.delivered_orders} طلب مكتمل</Text></View></View>)}{!drivers.length?<Text style={s.muted}>لا يوجد مندوبون حاليًا.</Text>:null}</ScrollView>;
}
function Card({title,value}:{title:string;value:string}){return <View style={s.card}><Text style={s.value}>{value}</Text><Text style={s.label}>{title}</Text></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:theme.background},content:{padding:20,paddingTop:55,paddingBottom:40},title:{color:theme.text,fontSize:29,fontWeight:"900",textAlign:"right"},subtitle:{color:theme.muted,lineHeight:23,textAlign:"right",marginTop:7,marginBottom:18},grid:{flexDirection:"row-reverse",flexWrap:"wrap",gap:9},card:{width:"48%",minHeight:105,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:17,padding:14,justifyContent:"center"},value:{color:theme.primary,fontSize:21,fontWeight:"900",textAlign:"right"},label:{color:theme.muted,fontSize:12,textAlign:"right",marginTop:7},section:{color:theme.text,fontSize:20,fontWeight:"900",textAlign:"right",marginTop:28,marginBottom:11},driver:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:17,padding:15,marginBottom:9,flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center"},name:{color:theme.text,fontSize:15,fontWeight:"800",textAlign:"right"},meta:{color:theme.muted,fontSize:11,textAlign:"right",marginTop:4},amount:{alignItems:"flex-start"},earn:{color:theme.text,fontSize:15,fontWeight:"900"},error:{color:"#B42318",backgroundColor:"#FDECEC",padding:12,borderRadius:12,textAlign:"right",marginBottom:12},loading:{flex:1,backgroundColor:theme.background,alignItems:"center",justifyContent:"center",gap:12},muted:{color:theme.muted,textAlign:"center",fontSize:13}});
