import AsyncStorage from "@react-native-async-storage/async-storage";
import { router } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { theme } from "@/constants/theme";

const API_URL=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,"");
const roleLabels={driver:"دليفري",restaurant:"مطعم",staff:"موظف"} as const;
type Role=keyof typeof roleLabels;
type Invite={id:string;code:string;invited_role:Role;invitee_name?:string|null;phone?:string|null;restaurant_name?:string|null;status:string;expires_at:string};

export default function InvitationsAdmin(){
 const [role,setRole]=useState<Role>("driver"),[name,setName]=useState(""),[phone,setPhone]=useState(""),[restaurantName,setRestaurantName]=useState(""),[items,setItems]=useState<Invite[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const load=useCallback(async()=>{try{const token=await AsyncStorage.getItem("auth_token");const r=await fetch(`${API_URL}/api/invitations`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر تحميل الدعوات");setItems(d.invitations||[]);}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل الدعوات");}finally{setLoading(false);}},[]);
 useEffect(()=>{load();},[load]);
 const create=async()=>{try{setSaving(true);setError("");setSuccess("");const token=await AsyncStorage.getItem("auth_token");const r=await fetch(`${API_URL}/api/invitations`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({role,name,phone,restaurantName:role==="restaurant"?restaurantName:undefined})});const d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر إنشاء الدعوة");setItems(v=>[d.invitation,...v]);setSuccess(`تم إنشاء الدعوة: ${d.invitation.code}`);setName("");setPhone("");setRestaurantName("");}catch(e){setError(e instanceof Error?e.message:"تعذر إنشاء الدعوة");}finally{setSaving(false);}};
 const revoke=async(id:string)=>{try{const token=await AsyncStorage.getItem("auth_token");const r=await fetch(`${API_URL}/api/invitations/${id}/revoke`,{method:"PATCH",headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر إلغاء الدعوة");setItems(v=>v.map(x=>x.id===id?d.invitation:x));}catch(e){setError(e instanceof Error?e.message:"تعذر إلغاء الدعوة");}};
 return <ScrollView style={styles.page} contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.back}><Text style={styles.backText}>→</Text></Pressable><View style={{flex:1}}><Text style={styles.title}>الدعوات</Text><Text style={styles.subtitle}>دعوات آمنة للمندوبين والمطاعم والموظفين</Text></View></View>
 <View style={styles.form}><Text style={styles.section}>دعوة جديدة</Text><View style={styles.roles}>{(Object.keys(roleLabels) as Role[]).map(x=><Pressable key={x} onPress={()=>setRole(x)} style={[styles.role,role===x&&styles.roleSelected]}><Text style={[styles.roleText,role===x&&styles.roleTextSelected]}>{roleLabels[x]}</Text></Pressable>)}</View><TextInput value={name} onChangeText={setName} placeholder="اسم الشخص / المسؤول" placeholderTextColor={theme.muted} style={styles.input}/><TextInput value={phone} onChangeText={setPhone} keyboardType="phone-pad" placeholder="رقم الهاتف (اختياري)" placeholderTextColor={theme.muted} style={styles.input}/>{role==="restaurant"?<TextInput value={restaurantName} onChangeText={setRestaurantName} placeholder="اسم المطعم" placeholderTextColor={theme.muted} style={styles.input}/>:null}<Pressable disabled={saving} onPress={create} style={styles.create}>{saving?<ActivityIndicator color="#fff"/>:<Text style={styles.createText}>إنشاء الدعوة</Text>}</Pressable></View>
 {success?<View style={styles.success}><Text style={styles.successText}>{success}</Text><Text style={styles.codeHint}>ابعت الكود للمستخدم لإتمام التسجيل.</Text></View>:null}{error?<View style={styles.error}><Text style={styles.errorText}>{error}</Text></View>:null}
 <Text style={styles.section}>آخر الدعوات</Text>{loading?<View style={styles.loading}><ActivityIndicator size="large" color={theme.primary}/></View>:items.length===0?<View style={styles.empty}><Text style={styles.emptyTitle}>مفيش دعوات لسه</Text><Text style={styles.muted}>أنشئ أول دعوة من النموذج فوق.</Text></View>:items.map(x=><View key={x.id} style={styles.card}><View style={styles.row}><View style={styles.code}><Text style={styles.codeText}>{x.code}</Text></View><View style={{flex:1}}><Text style={styles.name}>{x.invitee_name||"دعوة بدون اسم"}</Text><Text style={styles.meta}>{roleLabels[x.invited_role]} {x.restaurant_name?`• ${x.restaurant_name}`:""}</Text></View><View style={[styles.badge,x.status!=="pending"&&styles.badgeOff]}><Text style={styles.badgeText}>{x.status==="pending"?"معلقة":x.status==="used"?"مستخدمة":x.status==="revoked"?"ملغاة":"منتهية"}</Text></View></View>{x.phone?<Text style={styles.detail}>📱 {x.phone}</Text>:null}<Text style={styles.detail}>تنتهي: {new Date(x.expires_at).toLocaleDateString("ar-EG")}</Text>{x.status==="pending"?<Pressable onPress={()=>revoke(x.id)} style={styles.revoke}><Text style={styles.revokeText}>إلغاء الدعوة</Text></Pressable>:null}</View>)}
 </ScrollView>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:theme.background},content:{padding:20,paddingTop:55,paddingBottom:45},header:{flexDirection:"row-reverse",alignItems:"center",gap:12,marginBottom:18},back:{width:44,height:44,borderRadius:14,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,alignItems:"center",justifyContent:"center"},backText:{fontSize:23,color:theme.text},title:{fontSize:28,fontWeight:"900",color:theme.text,textAlign:"right"},subtitle:{fontSize:12,color:theme.muted,marginTop:4,textAlign:"right"},form:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:19,padding:15,marginBottom:16},section:{fontSize:19,fontWeight:"900",color:theme.text,textAlign:"right",marginBottom:10},roles:{flexDirection:"row-reverse",gap:7,marginBottom:10},role:{flex:1,borderWidth:1,borderColor:theme.border,borderRadius:12,paddingVertical:10,alignItems:"center"},roleSelected:{backgroundColor:theme.primary,borderColor:theme.primary},roleText:{color:theme.text,fontSize:12,fontWeight:"800"},roleTextSelected:{color:"#fff"},input:{height:46,borderWidth:1,borderColor:theme.border,borderRadius:13,color:theme.text,paddingHorizontal:13,textAlign:"right",marginTop:8},create:{height:47,borderRadius:13,backgroundColor:theme.primary,alignItems:"center",justifyContent:"center",marginTop:10},createText:{color:"#fff",fontWeight:"900"},success:{backgroundColor:"#E8F7EE",borderRadius:14,padding:12,marginBottom:12},successText:{color:theme.text,fontWeight:"900",textAlign:"right"},codeHint:{color:theme.muted,fontSize:11,textAlign:"right",marginTop:3},error:{backgroundColor:"#FDECEC",borderRadius:14,padding:12,marginBottom:12},errorText:{color:"#B42318",textAlign:"right",fontSize:12},card:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:18,padding:14,marginBottom:10},row:{flexDirection:"row-reverse",alignItems:"center",gap:9},code:{backgroundColor:theme.background,borderRadius:11,paddingHorizontal:10,paddingVertical:9},codeText:{color:theme.primary,fontWeight:"900",letterSpacing:1},name:{color:theme.text,fontWeight:"900",fontSize:14,textAlign:"right"},meta:{color:theme.muted,fontSize:11,textAlign:"right",marginTop:3},badge:{backgroundColor:"#E8F7EE",borderRadius:18,paddingHorizontal:9,paddingVertical:6},badgeOff:{backgroundColor:"#F1EEEE"},badgeText:{color:theme.text,fontSize:9,fontWeight:"800"},detail:{color:theme.muted,fontSize:11,textAlign:"right",marginTop:8},revoke:{borderWidth:1,borderColor:theme.border,borderRadius:11,alignItems:"center",paddingVertical:9,marginTop:10},revokeText:{color:theme.text,fontSize:11,fontWeight:"800"},loading:{paddingVertical:60,alignItems:"center"},empty:{backgroundColor:theme.surface,borderRadius:18,padding:25,alignItems:"center"},emptyTitle:{color:theme.text,fontSize:17,fontWeight:"900",marginBottom:5},muted:{color:theme.muted,fontSize:12,textAlign:"center"}});
