import AsyncStorage from '@react-native-async-storage/async-storage';
import {useEffect,useMemo,useState}from'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import {SafeAreaView}from'react-native-safe-area-context';
import {router}from'expo-router';
import {theme}from'@/constants/theme';
const API=(process.env.EXPO_PUBLIC_API_URL||'').replace(/\\/$/,'');
const layouts=[['horizontal','صف قابل للسحب'],['grid','شبكة Grid'],['single','بطاقة واحدة']] as const;
export default function Marketplaces(){
 const [list,setList]=useState<any[]>([]),[cats,setCats]=useState<any[]>([]),[subs,setSubs]=useState<any[]>([]);
 const [name,setName]=useState(''),[icon,setIcon]=useState('🛍️'),[desc,setDesc]=useState(''),[layout,setLayout]=useState('grid'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [catName,setCatName]=useState<Record<string,string>>({}),[subName,setSubName]=useState<Record<string,string>>({});
 const token=()=>AsyncStorage.getItem('auth_token');
 const request=async(path:string,method='GET',body?:any)=>{const r=await fetch(API+path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+await token()},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'تعذر تنفيذ العملية');return d};
 const load=async()=>{try{const d=await request('/api/marketplaces/admin/all/list');setList(d.marketplaces||[]);setCats(d.categories||[]);setSubs(d.subcategories||[]);setError('')}catch(e){setError(e instanceof Error?e.message:'تعذر التحميل')}};
 useEffect(()=>{load()},[]);
 const run=async(fn:()=>Promise<void>)=>{try{setBusy(true);setError('');await fn()}catch(e){setError(e instanceof Error?e.message:'تعذر تنفيذ العملية')}finally{setBusy(false)}};
 const add=()=>run(async()=>{if(!name.trim())throw Error('اكتب اسم الـMarketplace');await request('/api/marketplaces/admin/all','POST',{name:name.trim(),icon,description:desc.trim(),displayLayout:layout,sortOrder:list.length+1});setName('');setDesc('');setIcon('🛍️');await load()});
 const toggle=async(m:any,key:string)=>run(async()=>{const body:any={};body[key]=!m[key.replace(/[A-Z]/g,x=>'_'+x.toLowerCase())];await request('/api/marketplaces/admin/all/'+m.id,'PATCH',body);await load()});
 const addCat=(m:any)=>run(async()=>{const n=(catName[m.id]||'').trim();if(!n)throw Error('اكتب اسم القسم');await request('/api/marketplaces/admin/all/'+m.id+'/categories','POST',{name:n,sortOrder:(cats.filter(x=>x.marketplace_id===m.id).length+1)});setCatName(x=>({...x,[m.id]:''}));await load()});
 const addSub=(c:any)=>run(async()=>{const n=(subName[c.id]||'').trim();if(!n)throw Error('اكتب اسم التصنيف');await request('/api/marketplaces/admin/categories/'+c.id+'/subcategories','POST',{name:n,sortOrder:(subs.filter(x=>x.category_id===c.id).length+1)});setSubName(x=>({...x,[c.id]:''}));await load()});
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>→</Text></Pressable><Text style={s.title}>إدارة الـMarketplace</Text><Text style={s.sub}>أنشئ أي Marketplace جديد، اختر طريقة عرضه، أخفِ الأقسام أو أظهرها، ثم أضف الأقسام والتصنيفات. الإعدادات بيانات وليست أسماء ثابتة في الكود.</Text>
 <View style={s.card}><Text style={s.section}>Marketplace جديد</Text><TextInput value={name} onChangeText={setName} placeholder="مثال: كاركت بليس" placeholderTextColor={theme.muted} style={s.input} textAlign="right"/><TextInput value={icon} onChangeText={setIcon} placeholder="الأيقونة" placeholderTextColor={theme.muted} style={s.input} textAlign="right"/><TextInput value={desc} onChangeText={setDesc} placeholder="وصف اختياري" placeholderTextColor={theme.muted} style={s.input} textAlign="right"/><Text style={s.label}>طريقة عرض الأقسام</Text><View style={s.wrap}>{layouts.map(([v,l])=><Pressable key={v} onPress={()=>setLayout(v)} style={[s.chip,layout===v&&s.on]}><Text style={layout===v?s.onText:s.chipText}>{l}</Text></Pressable>)}</View><Pressable disabled={busy} onPress={add} style={s.primary}><Text style={s.primaryText}>{busy?'جاري الحفظ...':'+ إنشاء Marketplace'}</Text></Pressable></View>
 {error?<Text style={s.error}>{error}</Text>:null}
 {list.map(m=>{const mc=cats.filter(x=>x.marketplace_id===m.id);return <View key={m.id} style={[s.market,!m.is_active&&s.dim]}><View style={s.marketHead}><View style={{flex:1}}><Text style={s.marketName}>{m.icon||'🛍️'} {m.name}</Text><Text style={s.meta}>{m.display_layout==='horizontal'?'صف قابل للسحب':m.display_layout==='grid'?'Grid':'بطاقة واحدة'} • ترتيب {m.sort_order}</Text></View><Text style={s.slug}>{m.slug}</Text></View><View style={s.wrap}>{[['isActive','نشط'],['showOnHome','Home'],['showInSearch','بحث'],['showCategories','إظهار الأقسام']].map(([k,l])=><Pressable key={k} onPress={()=>toggle(m,k)} style={[s.toggle,Boolean(m[k.replace(/[A-Z]/g,(x:string)=>'_'+x.toLowerCase())])&&s.toggleOn]}><Text style={Boolean(m[k.replace(/[A-Z]/g,(x:string)=>'_'+x.toLowerCase())])?s.onText:s.chipText}>{l}</Text></Pressable>)}</View>
 <View style={s.addRow}><TextInput value={catName[m.id]||''} onChangeText={v=>setCatName(x=>({...x,[m.id]:v}))} placeholder="قسم جديد" placeholderTextColor={theme.muted} style={[s.input,{flex:1,marginBottom:0}]}/><Pressable onPress={()=>addCat(m)} style={s.add}><Text style={s.addText}>+ قسم</Text></Pressable></View>
 {mc.map(c=>{const cs=subs.filter(x=>x.category_id===c.id);return <View key={c.id} style={[s.category,!c.is_active&&s.dim]}><Text style={s.catName}>{c.icon||'📂'} {c.name}</Text><Text style={s.meta}>{cs.length} تصنيف فرعي</Text><View style={s.addRow}><TextInput value={subName[c.id]||''} onChangeText={v=>setSubName(x=>({...x,[c.id]:v}))} placeholder="تصنيف فرعي جديد" placeholderTextColor={theme.muted} style={[s.input,{flex:1,marginBottom:0}]}/><Pressable onPress={()=>addSub(c)} style={s.add}><Text style={s.addText}>+</Text></Pressable></View>{cs.map(x=><Text key={x.id} style={s.subItem}>• {x.icon||'◦'} {x.name}</Text>)}</View>})}
 </View>})}
 </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.background},page:{padding:17,paddingBottom:50},back:{width:42,height:42,borderRadius:13,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,alignItems:'center',justifyContent:'center'},backText:{fontSize:22,color:theme.text},title:{color:theme.text,fontSize:25,fontWeight:'900',textAlign:'right',marginTop:14},sub:{color:theme.muted,fontSize:11,lineHeight:18,textAlign:'right',marginTop:5},card:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:18,padding:13,marginTop:14},section:{color:theme.text,fontSize:15,fontWeight:'900',textAlign:'right',marginBottom:8},input:{height:46,borderWidth:1,borderColor:theme.border,borderRadius:12,backgroundColor:theme.background,color:theme.text,paddingHorizontal:11,marginBottom:7},label:{color:theme.text,fontSize:11,fontWeight:'800',textAlign:'right',marginTop:5,marginBottom:7},wrap:{flexDirection:'row-reverse',flexWrap:'wrap',gap:7},chip:{paddingHorizontal:11,paddingVertical:9,borderWidth:1,borderColor:theme.border,borderRadius:11,backgroundColor:theme.background},on:{backgroundColor:theme.primary,borderColor:theme.primary},chipText:{color:theme.text,fontSize:10,fontWeight:'800'},onText:{color:'#fff',fontSize:10,fontWeight:'900'},primary:{height:48,borderRadius:13,backgroundColor:theme.primary,alignItems:'center',justifyContent:'center',marginTop:11},primaryText:{color:'#fff',fontWeight:'900'},error:{color:theme.danger,textAlign:'right',marginTop:10},market:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:18,padding:13,marginTop:12},marketHead:{flexDirection:'row-reverse',alignItems:'center',gap:9},marketName:{color:theme.text,fontSize:16,fontWeight:'900',textAlign:'right'},meta:{color:theme.muted,fontSize:9,textAlign:'right',marginTop:3},slug:{color:theme.primary,fontSize:9,fontWeight:'900'},toggle:{paddingHorizontal:10,paddingVertical:7,borderRadius:10,borderWidth:1,borderColor:theme.border,marginTop:10},toggleOn:{backgroundColor:theme.primary,borderColor:theme.primary},addRow:{flexDirection:'row-reverse',gap:7,alignItems:'center',marginTop:10},add:{height:46,paddingHorizontal:12,borderRadius:12,backgroundColor:theme.primary,alignItems:'center',justifyContent:'center'},addText:{color:'#fff',fontWeight:'900'},category:{backgroundColor:theme.background,borderRadius:13,padding:10,marginTop:8},catName:{color:theme.text,fontWeight:'900',textAlign:'right'},subItem:{color:theme.muted,fontSize:10,textAlign:'right',marginTop:5},dim:{opacity:.55}});