import AsyncStorage from "@react-native-async-storage/async-storage";
import { router } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { theme } from "@/constants/theme";
const API_URL=process.env.EXPO_PUBLIC_API_URL||"";
const labels:any={pending:"جديد",confirmed:"مؤكد",preparing:"جاري التجهيز",ready:"جاهز",assigned:"مسند",picked_up:"تم الاستلام",on_the_way:"في الطريق",delivered:"تم التسليم",cancelled:"ملغي"};
export default function AdminOrders(){
const [orders,setOrders]=useState<any[]>([]),[drivers,setDrivers]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
const load=async()=>{try{const t=await AsyncStorage.getItem("auth_token");const h={Authorization:"Bearer "+t};const a=await fetch(API_URL+"/api/orders/admin",{headers:h});const b=await fetch(API_URL+"/api/location/drivers",{headers:h});const od=await a.json(),dd=await b.json();if(!a.ok)throw new Error(od.error||"تعذر تحميل الطلبات");setOrders(od.orders||[]);setDrivers(dd.drivers||[])}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل البيانات")}finally{setLoading(false)}};
useEffect(()=>{load();const id=setInterval(load,5000);return()=>clearInterval(id)},[]);
const assign=async(id:string,driverId:string)=>{try{const t=await AsyncStorage.getItem("auth_token");const r=await fetch(API_URL+"/api/orders/"+id+"/assign",{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:"Bearer "+t},body:JSON.stringify({driverId})});const d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر الإسناد");await load()}catch(e){setError(e instanceof Error?e.message:"تعذر الإسناد")}};
return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Pressable onPress={()=>router.back()} style={s.back}><Text>→</Text></Pressable><Text style={s.title}>إدارة الطلبات</Text><Text style={s.sub}>إسناد الطلبات للدليفري</Text>{error?<Text style={s.error}>{error}</Text>:null}{loading?<ActivityIndicator size="large" color={theme.primary}/>:orders.map(o=><View key={o.id} style={s.card}><Text style={s.order}>طلب #{o.id.slice(0,8)} • {labels[o.status]||o.status}</Text><Text style={s.name}>{o.customer_name}</Text><Text style={s.phone}>{o.customer_phone||""}</Text><Text style={s.address}>{o.delivery_address||"الموقع محدد على الخريطة"}</Text><Text style={s.label}>{o.driver_name?"المندوب: "+o.driver_name:"اختيار مندوب"}</Text><ScrollView horizontal>{drivers.map(d=><Pressable key={d.id} onPress={()=>assign(o.id,d.id)} style={[s.driver,o.driver_id===d.id&&s.selected]}><Text style={o.driver_id===d.id?s.selectedText:s.driverText}>{d.full_name}</Text></Pressable>)}</ScrollView></View>)}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.background},content:{padding:20,paddingTop:50,paddingBottom:40},back:{width:44,height:44,borderRadius:14,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,alignItems:"center",justifyContent:"center"},title:{fontSize:29,fontWeight:"900",color:theme.text,textAlign:"right",marginTop:16},sub:{fontSize:12,color:theme.muted,textAlign:"right",marginTop:4,marginBottom:14},card:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:18,padding:16,marginBottom:11},order:{fontSize:11,color:theme.muted,textAlign:"right"},name:{fontSize:17,fontWeight:"900",color:theme.text,textAlign:"right",marginTop:6},phone:{fontSize:12,color:theme.muted,textAlign:"right",marginTop:3},address:{fontSize:13,color:theme.text,textAlign:"right",marginTop:9},label:{fontSize:12,color:theme.muted,fontWeight:"800",textAlign:"right",marginTop:12,marginBottom:7},driver:{borderWidth:1,borderColor:theme.border,borderRadius:12,padding:10,marginRight:7},driverText:{color:theme.text,fontSize:12,fontWeight:"700"},selected:{backgroundColor:theme.primary,borderColor:theme.primary},selectedText:{color:"#fff",fontSize:12,fontWeight:"700"},error:{color:theme.danger,textAlign:"right",marginBottom:10}});