import AsyncStorage from '@react-native-async-storage/async-storage';
import{router}from'expo-router';import{useEffect,useState}from'react';
import{Alert,Modal,Pressable,ScrollView,StyleSheet,Switch,Text,TextInput,View}from'react-native';
import{SafeAreaView}from'react-native-safe-area-context';import{theme}from'@/constants/theme';
const API=(process.env.EXPO_PUBLIC_API_URL||'').replace(/\/$/,'');
type Method=any;
export default function PaymentMethods(){
 const[items,setItems]=useState<Method[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Method|null>(null);
 const[name,setName]=useState(''),[code,setCode]=useState(''),[description,setDescription]=useState(''),[label,setLabel]=useState(''),[value,setValue]=useState(''),[instructions,setInstructions]=useState(''),[proof,setProof]=useState(false);
 const token=()=>AsyncStorage.getItem('auth_token');
 const reset=()=>{setName('');setCode('');setDescription('');setLabel('');setValue('');setInstructions('');setProof(false)};
 const load=async()=>{try{const r=await fetch(API+'/api/financial/admin/payment-methods',{headers:{Authorization:'Bearer '+await token()}}),d=await r.json();if(!r.ok)throw Error(d.error||'تعذر تحميل طرق الدفع');setItems(d.methods||[]);setError('')}catch(e){setError(e instanceof Error?e.message:'تعذر التحميل')}};
 useEffect(()=>{load()},[]);
 const add=async()=>{if(!name.trim()||!code.trim())return setError('اكتب اسم وكود طريقة الدفع');try{setBusy(true);const r=await fetch(API+'/api/financial/admin/payment-methods',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+await token()},body:JSON.stringify({name,code,description,accountLabel:label,accountValue:value,instructions,requiresProof:proof})}),d=await r.json();if(!r.ok)throw Error(d.error||'تعذر الإضافة');reset();await load()}catch(e){setError(e instanceof Error?e.message:'تعذر الإضافة')}finally{setBusy(false)}};
 const patch=async(x:Method,body:any)=>{const r=await fetch(API+'/api/financial/admin/payment-methods/'+x.id,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:'Bearer '+await token()},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error||'تعذر الحفظ');return d};
 const toggle=async(x:Method)=>{try{await patch(x,{isActive:!x.is_active});load()}catch(e){setError(e instanceof Error?e.message:'تعذر تغيير الحالة')}};
 const openEdit=(x:Method)=>{setEditing(x);setName(x.name||'');setCode(x.code||'');setDescription(x.description||'');setLabel(x.account_label||'');setValue(x.account_value||'');setInstructions(x.instructions||'');setProof(Boolean(x.requires_proof))};
 const saveEdit=async()=>{if(!editing||!name.trim())return setError('اكتب اسم طريقة الدفع');try{setBusy(true);await patch(editing,{name,description,accountLabel:label,accountValue:value,instructions,requiresProof:proof});setEditing(null);reset();await load()}catch(e){setError(e instanceof Error?e.message:'تعذر الحفظ')}finally{setBusy(false)}};
 const remove=(x:Method)=>Alert.alert('حذف طريقة الدفع','سيتم حذفها من النظام وقد لا تظهر في الطلبات الجديدة.',[{text:'إلغاء',style:'cancel'},{text:'حذف',style:'destructive',onPress:async()=>{try{const r=await fetch(API+'/api/financial/admin/payment-methods/'+x.id,{method:'DELETE',headers:{Authorization:'Bearer '+await token()}}),d=await r.json();if(!r.ok)throw Error(d.error||'تعذر الحذف');load()}catch(e){setError(e instanceof Error?e.message:'تعذر الحذف')}}}]);
 const move=async(x:Method,delta:number)=>{const sorted=[...items].sort((a,b)=>Number(a.sort_order||0)-Number(b.sort_order||0));const i=sorted.findIndex(v=>v.id===x.id),j=i+delta;if(j<0||j>=sorted.length)return;try{await patch(sorted[i],{sortOrder:Number(sorted[j].sort_order||0)});await patch(sorted[j],{sortOrder:Number(sorted[i].sort_order||0)});load()}catch(e){setError(e instanceof Error?e.message:'تعذر تغيير الترتيب')}};
 const Form=({edit=false}:{edit?:boolean})=><View style={s.card}><Text style={s.section}>{edit?'تعديل طريقة الدفع':'إضافة طريقة دفع'}</Text><Text style={s.hint}>الاسم والوصف يظهران للعميل، وبيانات الحساب والتعليمات تستخدم أثناء التحويل.</Text><TextInput value={name} onChangeText={setName} placeholder="اسم الطريقة" placeholderTextColor={theme.muted} style={s.input} textAlign="right"/>{!edit&&<TextInput value={code} onChangeText={setCode} placeholder="كود: vodafone_cash" placeholderTextColor={theme.muted} style={s.input} autoCapitalize="none"/>}<TextInput value={description} onChangeText={setDescription} placeholder="وصف مختصر للعميل" placeholderTextColor={theme.muted} style={s.input} textAlign="right"/><TextInput value={label} onChangeText={setLabel} placeholder="مثال: رقم Vodafone Cash" placeholderTextColor={theme.muted} style={s.input} textAlign="right"/><TextInput value={value} onChangeText={setValue} placeholder="رقم الهاتف أو الحساب" placeholderTextColor={theme.muted} style={s.input} textAlign="right"/><TextInput value={instructions} onChangeText={setInstructions} placeholder="تعليمات الدفع والتحويل" placeholderTextColor={theme.muted} style={[s.input,s.textarea]} multiline textAlignVertical="top" textAlign="right"/><View style={s.switchRow}><Switch value={proof} onValueChange={setProof}/><View><Text style={s.name}>يتطلب إثبات تحويل</Text><Text style={s.hint}>يطلب من العميل رفع صورة الإيصال.</Text></View></View><Pressable onPress={edit?saveEdit:add} disabled={busy} style={[s.primary,busy&&{opacity:.6}]}><Text style={s.primaryText}>{busy?'جاري الحفظ...':edit?'حفظ التعديلات':'إضافة طريقة الدفع'}</Text></Pressable></View>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>←</Text></Pressable><Text style={s.title}>طرق الدفع</Text><Text style={s.sub}>هنا تتحكم بالكامل في طرق الدفع التي تظهر للعميل، وبيانات التحويل وترتيب الظهور.</Text>{error?<View style={s.errorBox}><Text style={s.error}>{error}</Text></View>:null}<Form/><Text style={s.section}>الطرق الحالية</Text>{[...items].sort((a,b)=>Number(a.sort_order||0)-Number(b.sort_order||0)).map((x,i)=><View key={x.id} style={[s.item,!x.is_active&&s.off]}><View style={{flex:1}}><View style={s.itemHead}><Text style={s.order}>{i+1}</Text><View style={{flex:1}}><Text style={s.name}>{x.name}</Text><Text style={s.meta}>{x.description||x.code}</Text></View></View>{x.account_value?<Text style={s.account}>{x.account_label||'الحساب'}: {x.account_value}</Text>:null}<Text style={s.meta}>{x.requires_proof?'✓ يتطلب إثبات تحويل':'✓ لا يحتاج إثبات'} • {x.is_active?'ظاهر للعميل':'مخفي'}</Text><View style={s.actions}><Pressable onPress={()=>move(x,-1)} style={s.action}><Text style={s.actionText}>↑</Text></Pressable><Pressable onPress={()=>move(x,1)} style={s.action}><Text style={s.actionText}>↓</Text></Pressable><Pressable onPress={()=>openEdit(x)} style={s.action}><Text style={s.editText}>تعديل</Text></Pressable><Pressable onPress={()=>remove(x)} style={s.action}><Text style={s.deleteText}>حذف</Text></Pressable></View></View><Switch value={Boolean(x.is_active)} onValueChange={()=>toggle(x)}/></View>)}</ScrollView><Modal visible={Boolean(editing)} animationType="slide" onRequestClose={()=>{setEditing(null);reset()}}><SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><View style={s.modalHead}><Pressable onPress={()=>{setEditing(null);reset()}} style={s.back}><Text style={s.backText}>×</Text></Pressable><Text style={s.modalTitle}>تعديل طريقة الدفع</Text></View><Form edit/></ScrollView></SafeAreaView></Modal></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.background},page:{padding:17,paddingBottom:45},back:{width:43,height:43,borderRadius:14,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,alignItems:'center',justifyContent:'center'},backText:{color:theme.text,fontSize:21},title:{color:theme.text,fontSize:27,fontWeight:'900',textAlign:'right',marginTop:13},modalTitle:{color:theme.text,fontSize:20,fontWeight:'900',textAlign:'right'},modalHead:{flexDirection:'row-reverse',alignItems:'center',justifyContent:'space-between'},sub:{color:theme.muted,fontSize:10,textAlign:'right',lineHeight:17,marginTop:5},card:{backgroundColor:theme.surface,borderRadius:20,borderWidth:1,borderColor:theme.border,padding:14,marginTop:15},section:{color:theme.text,fontSize:16,fontWeight:'900',textAlign:'right',marginTop:14,marginBottom:8},hint:{color:theme.muted,fontSize:9,textAlign:'right',lineHeight:15,marginBottom:7},input:{borderWidth:1,borderColor:theme.border,borderRadius:13,backgroundColor:theme.background,color:theme.text,paddingHorizontal:12,marginBottom:8,minHeight:47},textarea:{height:85,paddingTop:12},switchRow:{flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center',marginTop:3},primary:{height:49,borderRadius:14,backgroundColor:theme.primary,alignItems:'center',justifyContent:'center',marginTop:13},primaryText:{color:'#fff',fontWeight:'900'},item:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:17,padding:12,marginBottom:9,flexDirection:'row-reverse',alignItems:'center',gap:10},off:{opacity:.55},itemHead:{flexDirection:'row-reverse',alignItems:'center',gap:9},order:{width:28,height:28,borderRadius:9,backgroundColor:theme.primarySoft,color:theme.primary,textAlign:'center',textAlignVertical:'center',fontWeight:'900'},name:{color:theme.text,fontWeight:'900',textAlign:'right'},meta:{color:theme.muted,fontSize:9,textAlign:'right',marginTop:4},account:{color:theme.primary,fontSize:10,fontWeight:'800',textAlign:'right',marginTop:6},actions:{flexDirection:'row-reverse',gap:6,marginTop:10},action:{paddingHorizontal:10,paddingVertical:7,borderRadius:9,backgroundColor:theme.background},actionText:{color:theme.text,fontWeight:'900'},editText:{color:theme.primary,fontSize:10,fontWeight:'900'},deleteText:{color:theme.danger,fontSize:10,fontWeight:'900'},errorBox:{backgroundColor:theme.dangerSoft,borderRadius:13,padding:10,marginTop:10},error:{color:theme.danger,textAlign:'right',fontSize:10}});
