import AsyncStorage from "@react-native-async-storage/async-storage";
import { router } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { theme } from "@/constants/theme";

const API_URL=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,"");
type Restaurant={id:string;full_name:string;phone?:string|null;status:string;display_name?:string|null;description?:string|null;address?:string|null;area?:string|null;minimum_order?:string|number;preparation_minutes?:string|number;is_open?:boolean;is_featured?:boolean;menu_items:number};

export default function RestaurantsAdmin(){
 const [items,setItems]=useState<Restaurant[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [search,setSearch]=useState(""); const [error,setError]=useState("");
 const load=useCallback(async()=>{try{setError("");const token=await AsyncStorage.getItem("auth_token");if(!token){router.replace("/auth");return;}const r=await fetch(`${API_URL}/api/admin/restaurants`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر تحميل المطاعم");setItems(d.restaurants||[]);}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل المطاعم");}finally{setLoading(false);}},[]);
 useEffect(()=>{load();},[load]);
 const update=async(id:string,body:object)=>{try{setBusy(id);const token=await AsyncStorage.getItem("auth_token");const r=await fetch(`${API_URL}/api/admin/restaurants/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر تحديث المطعم");setItems(v=>v.map(x=>x.id===id?{...x,...d.restaurant}:x));}catch(e){setError(e instanceof Error?e.message:"تعذر تحديث المطعم");}finally{setBusy(null);}};
 const filtered=items.filter(x=>`${x.display_name||x.full_name} ${x.area||""} ${x.phone||""}`.toLowerCase().includes(search.toLowerCase()));
 return <ScrollView style={styles.page} contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.back}><Text style={styles.backText}>→</Text></Pressable><View style={{flex:1}}><Text style={styles.title}>المطاعم</Text><Text style={styles.subtitle}>إدارة حالة المطعم وظهوره والمنيو</Text></View></View>
 <TextInput value={search} onChangeText={setSearch} placeholder="ابحث باسم المطعم أو المنطقة" placeholderTextColor={theme.muted} style={styles.search}/>
 {error?<View style={styles.error}><Text style={styles.errorText}>{error}</Text></View>:null}
 {loading?<View style={styles.loading}><ActivityIndicator size="large" color={theme.primary}/><Text style={styles.muted}>جاري تحميل المطاعم...</Text></View>:filtered.length===0?<View style={styles.empty}><Text style={styles.emptyTitle}>لا توجد مطاعم</Text><Text style={styles.muted}>عيّن حسابًا كـ مطعم من المستخدمين أو أنشئ دعوة.</Text></View>:filtered.map(r=><View key={r.id} style={styles.card}><View style={styles.row}><View style={styles.avatar}><Text style={styles.avatarText}>{(r.display_name||r.full_name||"م").slice(0,1)}</Text></View><View style={{flex:1}}><Text style={styles.name}>{r.display_name||r.full_name}</Text><Text style={styles.meta}>{r.phone||"بدون هاتف"} • {r.menu_items||0} منتج</Text></View><View style={[styles.badge,r.status!=="active"&&styles.badgeOff]}><Text style={styles.badgeText}>{r.status==="active"?"نشط":r.status==="suspended"?"موقوف":"معلق"}</Text></View></View>
 <Text style={styles.description}>{r.description||"أضف وصفًا للمطعم من لوحة الإدارة لاحقًا."}</Text><View style={styles.info}><Text style={styles.infoText}>المنطقة: {r.area||"غير محددة"}</Text><Text style={styles.infoText}>الحد الأدنى: {Number(r.minimum_order||0).toFixed(2)} ج</Text><Text style={styles.infoText}>التجهيز: {Number(r.preparation_minutes||30)} دقيقة</Text></View>
 <View style={styles.actions}><Pressable disabled={busy===r.id} onPress={()=>update(r.id,{isOpen:!r.is_open})} style={[styles.action,r.is_open&&styles.actionOn]}><Text style={[styles.actionText,r.is_open&&styles.actionTextOn]}>{r.is_open?"مفتوح":"مغلق"}</Text></Pressable><Pressable disabled={busy===r.id} onPress={()=>update(r.id,{isFeatured:!r.is_featured})} style={[styles.action,r.is_featured&&styles.actionOn]}><Text style={[styles.actionText,r.is_featured&&styles.actionTextOn]}>{r.is_featured?"مميز":"تمييز"}</Text></Pressable><Pressable disabled={busy===r.id} onPress={()=>update(r.id,{status:r.status==="active"?"suspended":"active"})} style={styles.action}>{busy===r.id?<ActivityIndicator color={theme.primary}/>:<Text style={styles.actionText}>{r.status==="active"?"إيقاف":"تفعيل"}</Text>}</Pressable></View></View>)}
 </ScrollView>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:theme.background},content:{padding:20,paddingTop:55,paddingBottom:45},header:{flexDirection:"row-reverse",alignItems:"center",gap:12,marginBottom:18},back:{width:44,height:44,borderRadius:14,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,alignItems:"center",justifyContent:"center"},backText:{fontSize:23,color:theme.text},title:{fontSize:28,fontWeight:"900",color:theme.text,textAlign:"right"},subtitle:{fontSize:12,color:theme.muted,marginTop:4,textAlign:"right"},search:{height:48,borderRadius:15,borderWidth:1,borderColor:theme.border,backgroundColor:theme.surface,color:theme.text,paddingHorizontal:14,textAlign:"right",marginBottom:14},card:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:19,padding:15,marginBottom:12},row:{flexDirection:"row-reverse",alignItems:"center",gap:10},avatar:{width:46,height:46,borderRadius:15,backgroundColor:theme.primary,alignItems:"center",justifyContent:"center"},avatarText:{color:"#fff",fontWeight:"900",fontSize:18},name:{color:theme.text,fontSize:16,fontWeight:"900",textAlign:"right"},meta:{color:theme.muted,fontSize:11,marginTop:4,textAlign:"right"},badge:{backgroundColor:"#E8F7EE",borderRadius:18,paddingHorizontal:10,paddingVertical:6},badgeOff:{backgroundColor:"#F4E8E8"},badgeText:{color:theme.text,fontSize:10,fontWeight:"800"},description:{color:theme.muted,fontSize:12,lineHeight:19,textAlign:"right",marginTop:13},info:{marginTop:10,gap:5},infoText:{color:theme.text,fontSize:11,textAlign:"right"},actions:{flexDirection:"row-reverse",gap:7,marginTop:14},action:{flex:1,minHeight:40,borderRadius:12,borderWidth:1,borderColor:theme.border,alignItems:"center",justifyContent:"center"},actionOn:{backgroundColor:theme.primary,borderColor:theme.primary},actionText:{color:theme.text,fontSize:11,fontWeight:"800"},actionTextOn:{color:"#fff"},loading:{alignItems:"center",paddingVertical:70,gap:12},empty:{padding:30,backgroundColor:theme.surface,borderRadius:18,alignItems:"center"},emptyTitle:{color:theme.text,fontSize:18,fontWeight:"900",marginBottom:7},muted:{color:theme.muted,textAlign:"center",fontSize:12},error:{backgroundColor:"#FDECEC",borderRadius:14,padding:12,marginBottom:12},errorText:{color:"#B42318",textAlign:"right",fontSize:12,lineHeight:19}});
