import AsyncStorage from '@react-native-async-storage/async-storage';
import { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { theme } from '@/constants/theme';

const API=(process.env.EXPO_PUBLIC_API_URL||'').replace(/\/$/,'');
const TYPES=[
 {key:'free_delivery',label:'توصيل مجاني',hint:'لا يحتاج قيمة مالية',needsValue:false},
 {key:'delivery_percent',label:'خصم نسبة على التوصيل',hint:'اكتب نسبة الخصم من رسوم التوصيل',needsValue:true,valueLabel:'نسبة الخصم %'},
 {key:'delivery_fixed',label:'خصم ثابت على التوصيل',hint:'اكتب قيمة الخصم بالجنيه',needsValue:true,valueLabel:'قيمة الخصم (ج.م)'},
 {key:'order_percent',label:'خصم نسبة على الطلب',hint:'اكتب نسبة الخصم من قيمة الطلب',needsValue:true,valueLabel:'نسبة الخصم %'},
 {key:'order_fixed',label:'خصم ثابت على الطلب',hint:'اكتب قيمة الخصم بالجنيه',needsValue:true,valueLabel:'قيمة الخصم (ج.م)'},
 {key:'wallet_credit',label:'رصيد في المحفظة',hint:'سيُضاف الرصيد إلى محفظة العميل',needsValue:true,valueLabel:'قيمة الرصيد (ج.م)'},
 {key:'cashback',label:'استرداد نقدي',hint:'اكتب قيمة الاسترداد',needsValue:true,valueLabel:'قيمة الاسترداد (ج.م)'},
 {key:'voucher',label:'قسيمة لمطعم',hint:'حدد قيمة القسيمة أو اتركها حسب إعداد المطعم',needsValue:true,valueLabel:'قيمة القسيمة (ج.م)'},
 {key:'free_item',label:'منتج مجاني',hint:'اكتب وصف المنتج المجاني',needsText:true,valueLabel:'اسم أو وصف المنتج'},
 {key:'buy_x_get_y',label:'اشترِ X واحصل على Y',hint:'اكتب قاعدة العرض مثل: اشترِ 2 واحصل على 1',needsText:true,valueLabel:'تفاصيل العرض'}
];
const readJson=async(r:Response)=>{const t=await r.text();try{return JSON.parse(t)}catch{return {error:'تعذر قراءة رد الخادم'}}};

export default function Rewards(){
 const [tiers,setTiers]=useState<any[]>([]),[rewards,setRewards]=useState<any[]>([]);
 const [tierId,setTierId]=useState(''),[name,setName]=useState(''),[type,setType]=useState('delivery_percent'),[value,setValue]=useState('');
 const [min,setMin]=useState(''),[max,setMax]=useState(''),[uses,setUses]=useState(''),[budget,setBudget]=useState(''),[expires,setExpires]=useState('');
 const [cq,setCq]=useState(''),[rq,setRq]=useState(''),[customers,setCustomers]=useState<any[]>([]),[restaurants,setRestaurants]=useState<any[]>([]);
 const [customerIds,setCustomerIds]=useState<string[]>([]),[restaurantIds,setRestaurantIds]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const selected=useMemo(()=>TYPES.find(x=>x.key===type)!, [type]);
 const token=()=>AsyncStorage.getItem('auth_token');

 const load=async()=>{try{setError('');const t=await token(),h={Authorization:`Bearer ${t}`};const[a,b]=await Promise.all([fetch(API+'/api/operations/admin/tiers',{headers:h}),fetch(API+'/api/rewards/admin/rewards',{headers:h})]);const x=await readJson(a),y=await readJson(b);if(!a.ok)throw Error(x.error||'تعذر تحميل الفئات');if(!b.ok)throw Error(y.error||'تعذر تحميل المكافآت');setTiers(x.tiers||[]);setRewards(y.rewards||[]);if(!tierId&&x.tiers?.[0])setTierId(x.tiers[0].id)}catch(e){setError(e instanceof Error?e.message:'تعذر التحميل')}};
 useEffect(()=>{load()},[]);

 const chooseType=(key:string)=>{setType(key);setValue('');};
 const search=async(kind:'customer'|'restaurant')=>{try{const q=kind==='customer'?cq:rq;if(!q.trim())return;const path=kind==='customer'?'/api/rewards/admin/targets/customers?q=':'/api/rewards/admin/targets/restaurants?q=';const r=await fetch(API+path+encodeURIComponent(q),{headers:{Authorization:`Bearer ${await token()}`}}),d=await readJson(r);if(!r.ok)throw Error(d.error||'تعذر البحث');kind==='customer'?setCustomers(d.customers||[]):setRestaurants(d.restaurants||[])}catch(e){setError(e instanceof Error?e.message:'تعذر البحث')}};

 const add=async()=>{if(!tierId||!name.trim())return Alert.alert('تنبيه','اختر الفئة واكتب اسم المكافأة');if(selected.needsValue&&(!Number.isFinite(Number(value))||Number(value)<=0))return Alert.alert('تنبيه','اكتب قيمة صحيحة للمكافأة');if(selected.needsText&&!value.trim())return Alert.alert('تنبيه','اكتب تفاصيل المكافأة');
  try{setBusy(true);const config:any=selected.needsText?{description:value.trim()}:{value:selected.needsValue?Number(value):0};const r=await fetch(API+'/api/rewards/admin/rewards',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await token()}`},body:JSON.stringify({tierId,name:name.trim(),rewardType:type,config,minOrderAmount:Number(min||0),maxDiscountAmount:max===''?null:Number(max),usageLimit:uses===''?null:Number(uses),budgetAmount:budget===''?null:Number(budget),expiresAt:expires||null,customerIds,restaurantIds})});const d=await readJson(r);if(!r.ok)throw Error(d.error||'تعذر حفظ المكافأة');Alert.alert('تم','تمت إضافة المكافأة.');setName('');setValue('');setMin('');setMax('');setUses('');setBudget('');setExpires('');setCustomerIds([]);setRestaurantIds([]);load()}catch(e){setError(e instanceof Error?e.message:'تعذر الحفظ')}finally{setBusy(false)}};

 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled">
  <Pressable onPress={()=>router.replace('/admin/operations')} style={s.back}><Text style={s.backText}>←</Text></Pressable>
  <Text style={s.title}>المكافآت</Text><Text style={s.sub}>تتغير تفاصيل الإدخال حسب نوع المكافأة، لذلك لن تظهر حقول لا تحتاجها.</Text>{error?<Text style={s.error}>{error}</Text>:null}
  <View style={s.card}><Text style={s.label}>الفئة المستهدفة</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{tiers.map(t=><Pressable key={t.id} onPress={()=>setTierId(t.id)} style={[s.chip,tierId===t.id&&s.active]}><Text style={tierId===t.id?s.activeText:s.chipText}>{t.name}</Text></Pressable>)}</ScrollView>
  <TextInput value={name} onChangeText={setName} placeholder="اسم واضح للمكافأة" placeholderTextColor={theme.muted} style={s.input} textAlign="right"/>
  <Text style={s.label}>نوع المكافأة</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{TYPES.map(x=><Pressable key={x.key} onPress={()=>chooseType(x.key)} style={[s.chip,type===x.key&&s.active]}><Text style={type===x.key?s.activeText:s.chipText}>{x.label}</Text></Pressable>)}</ScrollView>
  <View style={s.typeInfo}><Text style={s.typeTitle}>{selected.label}</Text><Text style={s.typeHint}>{selected.hint}</Text></View>
  {selected.needsValue||selected.needsText?<TextInput value={value} onChangeText={setValue} placeholder={selected.valueLabel} placeholderTextColor={theme.muted} keyboardType={selected.needsValue?'decimal-pad':'default'} style={s.input} textAlign="right"/>:null}
  {['delivery_percent','delivery_fixed','order_percent','order_fixed'].includes(type)?<><TextInput value={min} onChangeText={setMin} placeholder="الحد الأدنى لقيمة الطلب (اختياري)" placeholderTextColor={theme.muted} keyboardType="decimal-pad" style={s.input} textAlign="right"/><TextInput value={max} onChangeText={setMax} placeholder="الحد الأقصى لقيمة الخصم (اختياري)" placeholderTextColor={theme.muted} keyboardType="decimal-pad" style={s.input} textAlign="right"/></>:null}
  <Text style={s.sectionLabel}>حدود الاستخدام</Text><TextInput value={uses} onChangeText={setUses} placeholder="عدد مرات الاستخدام (اختياري)" placeholderTextColor={theme.muted} keyboardType="number-pad" style={s.input} textAlign="right"/><TextInput value={budget} onChangeText={setBudget} placeholder="إجمالي الميزانية (اختياري)" placeholderTextColor={theme.muted} keyboardType="decimal-pad" style={s.input} textAlign="right"/><TextInput value={expires} onChangeText={setExpires} placeholder="تاريخ الانتهاء ISO (اختياري)" placeholderTextColor={theme.muted} style={s.input} textAlign="right"/>
  <Text style={s.sectionLabel}>استهداف اختياري</Text><Text style={s.hint}>بدون تحديد عملاء أو مطاعم = المكافأة متاحة حسب قواعد الفئة.</Text>
  <View style={s.searchRow}><TextInput value={cq} onChangeText={setCq} placeholder="ابحث عن عميل" placeholderTextColor={theme.muted} style={s.search} textAlign="right"/><Pressable onPress={()=>search('customer')} style={s.small}><Text style={s.smallText}>بحث</Text></Pressable></View>{customers.map(c=><Pressable key={c.id} onPress={()=>setCustomerIds(x=>x.includes(c.id)?x.filter(i=>i!==c.id):[...x,c.id])} style={[s.target,customerIds.includes(c.id)&&s.targetOn]}><Text style={s.targetText}>{customerIds.includes(c.id)?'✓ ':''}{c.full_name} • {c.phone}</Text></Pressable>)}
  <View style={s.searchRow}><TextInput value={rq} onChangeText={setRq} placeholder="ابحث عن مطعم" placeholderTextColor={theme.muted} style={s.search} textAlign="right"/><Pressable onPress={()=>search('restaurant')} style={s.small}><Text style={s.smallText}>بحث</Text></Pressable></View>{restaurants.map(r=><Pressable key={r.id} onPress={()=>setRestaurantIds(x=>x.includes(r.id)?x.filter(i=>i!==r.id):[...x,r.id])} style={[s.target,restaurantIds.includes(r.id)&&s.targetOn]}><Text style={s.targetText}>{restaurantIds.includes(r.id)?'✓ ':''}{r.name}</Text></Pressable>)}
  <Pressable disabled={busy} onPress={add} style={s.primary}><Text style={s.primaryText}>{busy?'جاري الحفظ...':'إضافة المكافأة'}</Text></Pressable></View>
  <Text style={s.current}>المكافآت الحالية</Text>{rewards.map(r=>{const label=TYPES.find(x=>x.key===r.reward_type)?.label||r.reward_type;return <View key={r.id} style={s.item}><Text style={s.itemTitle}>{r.name}</Text><Text style={s.itemMeta}>{r.tier_name} • {label}</Text></View>})}
 </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({
 safe:{flex:1,backgroundColor:theme.background},page:{padding:18,paddingBottom:112},back:{width:44,height:44,borderRadius:14,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,alignItems:'center',justifyContent:'center'},backText:{fontSize:22,color:theme.text},title:{fontSize:28,fontWeight:'900',color:theme.text,textAlign:'right',marginTop:14},sub:{fontSize:11,color:theme.muted,textAlign:'right',lineHeight:18,marginTop:4},error:{color:theme.danger,textAlign:'right',marginTop:8},card:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:20,padding:14,marginTop:14},label:{color:theme.text,fontWeight:'900',textAlign:'right',marginBottom:7},sectionLabel:{color:theme.text,fontWeight:'900',textAlign:'right',fontSize:12,marginTop:5,marginBottom:6},chips:{gap:7,paddingBottom:4},chip:{borderWidth:1,borderColor:theme.border,borderRadius:18,paddingHorizontal:12,paddingVertical:9,backgroundColor:theme.background},active:{backgroundColor:theme.primary,borderColor:theme.primary},chipText:{color:theme.text,fontSize:10,fontWeight:'800'},activeText:{color:'#fff',fontSize:10,fontWeight:'900'},input:{minHeight:46,borderWidth:1,borderColor:theme.border,borderRadius:12,backgroundColor:theme.background,color:theme.text,paddingHorizontal:12,paddingVertical:10,marginBottom:8},typeInfo:{backgroundColor:theme.primarySoft,borderRadius:13,padding:11,marginBottom:8},typeTitle:{color:theme.primary,fontWeight:'900',textAlign:'right'},typeHint:{color:theme.text,fontSize:10,textAlign:'right',marginTop:3},hint:{color:theme.muted,fontSize:10,textAlign:'right',marginBottom:8},searchRow:{flexDirection:'row-reverse',gap:7,marginBottom:7},search:{flex:1,height:44,borderWidth:1,borderColor:theme.border,borderRadius:12,backgroundColor:theme.background,color:theme.text,paddingHorizontal:10},small:{height:44,paddingHorizontal:14,borderRadius:12,backgroundColor:theme.primary,justifyContent:'center'},smallText:{color:'#fff',fontWeight:'900'},target:{padding:10,borderWidth:1,borderColor:theme.border,borderRadius:12,marginBottom:5},targetOn:{borderColor:theme.primary,backgroundColor:theme.primarySoft},targetText:{color:theme.text,textAlign:'right',fontSize:11,fontWeight:'800'},primary:{height:48,borderRadius:14,backgroundColor:theme.primary,alignItems:'center',justifyContent:'center',marginTop:10},primaryText:{color:'#fff',fontWeight:'900'},current:{color:theme.text,fontSize:18,fontWeight:'900',textAlign:'right',marginTop:20,marginBottom:8},item:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:15,padding:12,marginBottom:7},itemTitle:{color:theme.text,fontWeight:'900',textAlign:'right'},itemMeta:{color:theme.muted,fontSize:10,textAlign:'right',marginTop:4}
});