const express = require("express");
const router = express.Router();
const { pool } = require("../db");
const { requireAuth, requireRole, requireSuperAdmin } = require("../auth");
router.use(requireAuth, requireRole("admin"));

router.get("/me", (req, res) => res.json({ user: req.user }));
router.get("/stats", async (_req, res, next) => { try { const [{rows:users},{rows:drivers},{rows:restaurants},{rows:categories},{rows:pending}]=await Promise.all([pool.query("SELECT COUNT(*)::int AS count FROM users"),pool.query("SELECT COUNT(*)::int AS count FROM users WHERE role='driver' AND status='active'"),pool.query("SELECT COUNT(*)::int AS count FROM users WHERE role='restaurant' AND status='active'"),pool.query("SELECT COUNT(*)::int AS count FROM categories WHERE is_active=true"),pool.query("SELECT COUNT(*)::int AS count FROM orders WHERE status IN ('pending','restaurant_pending')")]);res.json({users:users[0].count,activeDrivers:drivers[0].count,activeRestaurants:restaurants[0].count,activeCategories:categories[0].count,pendingOrders:pending[0].count}); } catch(e){next(e)} });
router.get("/attention", async (_req,res,next)=>{try{
 const [{rows:review},{rows:noDriver},{rows:late},{rows:itemIssues},{rows:adjustments},{rows:payments}]=await Promise.all([
  pool.query("SELECT COUNT(*)::int AS count FROM orders WHERE status IN ('pending','restaurant_pending')"),
  pool.query("SELECT COUNT(*)::int AS count FROM orders WHERE status IN ('preparing','ready') AND driver_id IS NULL AND driver_unavailable_notified_at IS NOT NULL"),
  pool.query("SELECT COUNT(*)::int AS count FROM orders WHERE status IN ('preparing','ready') AND estimated_ready_at IS NOT NULL AND estimated_ready_at<now()"),
  pool.query("SELECT COUNT(DISTINCT o.id)::int AS count FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE o.status NOT IN ('delivered','cancelled','restaurant_rejected','admin_rejected') AND oi.availability_status IN ('unavailable','replacement_pending')"),
  pool.query("SELECT COUNT(*)::int AS count FROM payment_adjustments WHERE status='pending'"),
  pool.query("SELECT COUNT(*)::int AS count FROM checkout_sessions WHERE payment_status IN ('pending_verification','payment_pending')")
 ]);
 const items=[
  {key:'orders',title:'طلبات تحتاج مراجعة',count:review[0].count,path:'/admin/orders',description:'طلبات جديدة أو تنتظر قرارًا'},
  {key:'drivers',title:'طلبات بدون مندوب متاح',count:noDriver[0].count,path:'/admin/orders',description:'طلبات أبلغ النظام بعدم توفر مندوب لها'},
  {key:'late',title:'طلبات متأخرة عن الجاهزية',count:late[0].count,path:'/admin/orders',description:'تجاوزت وقت التجهيز المتوقع'},
  {key:'items',title:'مشاكل أصناف معلقة',count:itemIssues[0].count,path:'/admin/orders',description:'أصناف غير متاحة أو تنتظر قرار العميل'},
  {key:'adjustments',title:'تسويات مالية معلقة',count:adjustments[0].count,path:'/admin/payment-adjustments',description:'فروق مالية تحتاج معالجة'},
  {key:'payments',title:'مدفوعات تحتاج متابعة',count:payments[0].count,path:'/admin/payments',description:'جلسات دفع ما زالت معلقة'}
 ];
 res.json({items,total:items.reduce((n,x)=>n+Number(x.count||0),0)});
}catch(e){next(e)}});
router.get("/users", async (_req,res,next)=>{try{const {rows}=await pool.query("SELECT id,full_name,phone,email,role,status,created_at,updated_at FROM users ORDER BY created_at DESC");res.json({users:rows})}catch(e){next(e)}});
router.patch("/users/:id",requireSuperAdmin,async(req,res,next)=>{try{const {role,status}=req.body,allowedRoles=["customer","driver","restaurant","staff","admin"],allowedStatus=["active","suspended","pending"];if(role!==undefined&&!allowedRoles.includes(role))return res.status(400).json({error:"Invalid role"});if(status!==undefined&&!allowedStatus.includes(status))return res.status(400).json({error:"Invalid status"});if(role===undefined&&status===undefined)return res.status(400).json({error:"Nothing to update"});const {rows:targetRows}=await pool.query("SELECT id,role FROM users WHERE id=$1",[req.params.id]);const target=targetRows[0];if(!target)return res.status(404).json({error:"User not found"});if(target.role==="super_admin")return res.status(403).json({error:"لا يمكن تعديل حساب السوبر أدمن"});const {rows}=await pool.query(`UPDATE users SET role=COALESCE($1,role),status=COALESCE($2,status),updated_at=now() WHERE id=$3 RETURNING id,full_name,phone,email,role,status,created_at,updated_at`,[role??null,status??null,req.params.id]);res.json({user:rows[0]})}catch(e){next(e)}});
router.get("/restaurants",async(_req,res,next)=>{try{const {rows}=await pool.query(`SELECT u.id,u.full_name,u.phone,u.email,u.status,u.created_at,rp.display_name,rp.description,rp.logo_url,rp.address,rp.area,rp.minimum_order,rp.preparation_minutes,rp.is_open,rp.is_featured,COUNT(mi.id)::int AS menu_items FROM users u LEFT JOIN restaurant_profiles rp ON rp.restaurant_id=u.id LEFT JOIN menu_items mi ON mi.restaurant_id=u.id WHERE u.role='restaurant' GROUP BY u.id,rp.id ORDER BY COALESCE(rp.is_featured,false) DESC,COALESCE(rp.display_name,u.full_name)`);res.json({restaurants:rows})}catch(e){next(e)}});
router.patch("/restaurants/:id",async(req,res,next)=>{try{const {status,isOpen,isFeatured,displayName,description,address,area,minimumOrder,preparationMinutes}=req.body||{};if(status!==undefined&&!['active','suspended','pending'].includes(status))return res.status(400).json({error:'حالة المطعم غير صحيحة'});const user=await pool.query("SELECT id FROM users WHERE id=$1 AND role='restaurant'",[req.params.id]);if(!user.rows[0])return res.status(404).json({error:'المطعم غير موجود'});await pool.query("BEGIN");try{if(status!==undefined)await pool.query("UPDATE users SET status=$1,updated_at=now() WHERE id=$2",[status,req.params.id]);const current=await pool.query("SELECT * FROM restaurant_profiles WHERE restaurant_id=$1",[req.params.id]);const existing=current.rows[0];await pool.query(`INSERT INTO restaurant_profiles(restaurant_id,display_name,description,address,area,minimum_order,preparation_minutes,is_open,is_featured) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(restaurant_id) DO UPDATE SET display_name=EXCLUDED.display_name,description=EXCLUDED.description,address=EXCLUDED.address,area=EXCLUDED.area,minimum_order=EXCLUDED.minimum_order,preparation_minutes=EXCLUDED.preparation_minutes,is_open=EXCLUDED.is_open,is_featured=EXCLUDED.is_featured,updated_at=now()`,[req.params.id,displayName!==undefined?String(displayName).trim():(existing?.display_name||(await pool.query("SELECT full_name FROM users WHERE id=$1",[req.params.id])).rows[0].full_name),description!==undefined?String(description).trim():existing?.description||null,address!==undefined?String(address).trim():existing?.address||null,area!==undefined?String(area).trim():existing?.area||null,minimumOrder!==undefined?Number(minimumOrder):Number(existing?.minimum_order||0),preparationMinutes!==undefined?Number(preparationMinutes):Number(existing?.preparation_minutes||30),isOpen!==undefined?Boolean(isOpen):existing?.is_open??true,isFeatured!==undefined?Boolean(isFeatured):existing?.is_featured??false]);await pool.query("COMMIT")}catch(e){await pool.query("ROLLBACK");throw e}const {rows}=await pool.query(`SELECT u.id,u.full_name,u.phone,u.email,u.status,rp.display_name,rp.description,rp.address,rp.area,rp.minimum_order,rp.preparation_minutes,rp.is_open,rp.is_featured FROM users u LEFT JOIN restaurant_profiles rp ON rp.restaurant_id=u.id WHERE u.id=$1`,[req.params.id]);res.json({restaurant:rows[0]})}catch(e){next(e)}});
router.get("/settings",async(_req,res,next)=>{try{const {rows}=await pool.query("SELECT key,value,updated_at FROM platform_settings ORDER BY key");res.json({settings:rows})}catch(e){next(e)}});
router.patch("/settings",async(req,res,next)=>{try{const settings=req.body?.settings;if(!settings||typeof settings!=="object"||Array.isArray(settings))return res.status(400).json({error:'settings must be an object'});const entries=Object.entries(settings);if(!entries.length)return res.status(400).json({error:'No settings supplied'});await pool.query("BEGIN");try{for(const [key,value] of entries){const normalizedKey=String(key).trim();if(!/^[a-z][a-z0-9_.-]{0,63}$/i.test(normalizedKey)){await pool.query("ROLLBACK");return res.status(400).json({error:`Invalid setting key: ${normalizedKey}`})}await pool.query(`INSERT INTO platform_settings(key,value,updated_at) VALUES($1,$2,now()) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=now()`,[normalizedKey,value==null?'':String(value)])}await pool.query("COMMIT")}catch(e){await pool.query("ROLLBACK");throw e}const {rows}=await pool.query("SELECT key,value,updated_at FROM platform_settings ORDER BY key");res.json({settings:rows})}catch(e){next(e)}});
router.get("/delivery",async(_req,res,next)=>{try{const {rows:settings}=await pool.query(`SELECT key,value,updated_at FROM platform_settings WHERE key LIKE 'delivery.%' ORDER BY key`);const {rows:zones}=await pool.query(`SELECT * FROM delivery_zones ORDER BY created_at DESC`);res.json({settings, zones})}catch(e){next(e)}});
router.patch("/delivery",async(req,res,next)=>{try{const s=req.body?.settings||{};const allowed=['delivery.base_fee','delivery.included_km','delivery.extra_km_fee','delivery.extra_merchant_fee','delivery.max_distance_km','delivery.max_merchants','delivery.pricing_mode'];for(const [key,value] of Object.entries(s)){if(!allowed.includes(key))return res.status(400).json({error:`إعداد غير مسموح: ${key}`});if(value!==''&&!Number.isFinite(Number(value))&&key!=='delivery.pricing_mode')return res.status(400).json({error:`قيمة غير صحيحة: ${key}`});if(key!=='delivery.pricing_mode'&&Number(value)<0)return res.status(400).json({error:`القيمة لا يمكن أن تكون سالبة: ${key}`})}await pool.query("BEGIN");try{for(const [key,value] of Object.entries(s))await pool.query(`INSERT INTO platform_settings(key,value,updated_at) VALUES($1,$2,now()) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=now()`,[key,String(value??'')]);await pool.query("COMMIT")}catch(e){await pool.query("ROLLBACK");throw e}const {rows}=await pool.query(`SELECT key,value,updated_at FROM platform_settings WHERE key LIKE 'delivery.%' ORDER BY key`);res.json({settings:rows})}catch(e){next(e)}});
router.post("/delivery/zones",async(req,res,next)=>{try{const b=req.body||{},name=String(b.name||'').trim(),lat=Number(b.centerLatitude),lon=Number(b.centerLongitude),radius=Number(b.radiusMeters);if(!name||!validCoord(lat,-90,90)||!validCoord(lon,-180,180)||!Number.isFinite(radius)||radius<=0)return res.status(400).json({error:'بيانات المنطقة غير صحيحة'});for(const key of ['baseFee','includedKm','extraKmFee','extraMerchantFee'])if(b[key]!==undefined&&(Number(b[key])<0||!Number.isFinite(Number(b[key]))))return res.status(400).json({error:`قيمة ${key} غير صحيحة`});const {rows}=await pool.query(`INSERT INTO delivery_zones(name,center_latitude,center_longitude,radius_meters,base_fee,included_km,extra_km_fee,extra_merchant_fee,is_active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[name,lat,lon,Math.round(radius),b.baseFee===''||b.baseFee==null?null:Number(b.baseFee),b.includedKm===''||b.includedKm==null?null:Number(b.includedKm),b.extraKmFee===''||b.extraKmFee==null?null:Number(b.extraKmFee),b.extraMerchantFee===''||b.extraMerchantFee==null?null:Number(b.extraMerchantFee),b.isActive===undefined?true:Boolean(b.isActive)]);res.status(201).json({zone:rows[0]})}catch(e){next(e)}});
router.patch("/delivery/zones/:id",async(req,res,next)=>{try{const b=req.body||{};const fields=[];const vals=[];const add=(column,value)=>{vals.push(value);fields.push(`${column}=$${vals.length}`)};if(b.name!==undefined)add('name',String(b.name).trim());if(b.centerLatitude!==undefined)add('center_latitude',Number(b.centerLatitude));if(b.centerLongitude!==undefined)add('center_longitude',Number(b.centerLongitude));if(b.radiusMeters!==undefined)add('radius_meters',Math.round(Number(b.radiusMeters)));if(b.baseFee!==undefined)add('base_fee',b.baseFee===''?null:Number(b.baseFee));if(b.includedKm!==undefined)add('included_km',b.includedKm===''?null:Number(b.includedKm));if(b.extraKmFee!==undefined)add('extra_km_fee',b.extraKmFee===''?null:Number(b.extraKmFee));if(b.extraMerchantFee!==undefined)add('extra_merchant_fee',b.extraMerchantFee===''?null:Number(b.extraMerchantFee));if(b.isActive!==undefined)add('is_active',Boolean(b.isActive));if(!fields.length)return res.status(400).json({error:'لا توجد تعديلات'});vals.push(req.params.id);const {rows}=await pool.query(`UPDATE delivery_zones SET ${fields.join(',')} WHERE id=$${vals.length} RETURNING *`,vals);if(!rows[0])return res.status(404).json({error:'المنطقة غير موجودة'});res.json({zone:rows[0]})}catch(e){next(e)}});
router.delete("/delivery/zones/:id",async(req,res,next)=>{try{const {rows}=await pool.query("DELETE FROM delivery_zones WHERE id=$1 RETURNING id",[req.params.id]);if(!rows[0])return res.status(404).json({error:'المنطقة غير موجودة'});res.json({ok:true})}catch(e){next(e)}});
function validCoord(v,min,max){return Number.isFinite(v)&&v>=min&&v<=max}
module.exports=router;
