const express=require("express");
const router=express.Router();
const {pool}=require("../db");
const {requireAuth,requireRole}=require("../auth");
const {notifyUser,notifyRole}=require("../push");

function money(v){const n=Number(v);return Number.isFinite(n)?Math.round(n*100)/100:0}
function coord(v,min,max){const n=Number(v);return Number.isFinite(n)&&n>=min&&n<=max}
function distanceMeters(a,b,c,d){const R=6371000,toRad=x=>x*Math.PI/180,p1=toRad(a),p2=toRad(c),dp=toRad(c-a),dl=toRad(d-b);const x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return Math.round(2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x)))}
async function settings(client){const {rows}=await client.query(`SELECT key,value FROM platform_settings WHERE key LIKE 'delivery.%'`);return Object.fromEntries(rows.map(x=>[x.key,x.value]))}
async function deliveryFee(client,restaurantIds,lat,lon){if(lat==null||lon==null)return {fee:0,distance:null};const s=await settings(client);const {rows}=await client.query(`SELECT restaurant_id,latitude,longitude FROM restaurant_profiles WHERE restaurant_id=ANY($1::uuid[])`,[restaurantIds]);const map=new Map(rows.map(x=>[String(x.restaurant_id),x]));const ds=restaurantIds.map(id=>{const p=map.get(String(id));return p?.latitude!=null&&p?.longitude!=null?distanceMeters(Number(p.latitude),Number(p.longitude),lat,lon):null}).filter(x=>x!=null);const distance=ds.length?Math.max(...ds):null;const base=money(s["delivery.base_fee"]||0),included=Math.max(0,Number(s["delivery.included_km"]||0)),extra=Math.max(0,Number(s["delivery.extra_km_fee"]||0)),merchant=Math.max(0,Number(s["delivery.extra_merchant_fee"]||0));const km=distance==null?0:distance/1000;const fee=money(base+Math.max(0,Math.ceil(km-included))*extra+Math.max(0,restaurantIds.length-1)*merchant);return {fee,distance}}
async function normalize(client,groups){if(!Array.isArray(groups)||!groups.length)throw Object.assign(new Error("السلة فارغة"),{status:400});const seen=new Set(),out=[];for(const g of groups){const rid=String(g?.restaurantId||"");if(!rid||seen.has(rid))throw Object.assign(new Error("بيانات الجهات غير صحيحة"),{status:400});seen.add(rid);const items=Array.isArray(g.items)?g.items:[];if(!items.length)throw Object.assign(new Error("إحدى الجهات لا تحتوي منتجات"),{status:400});const ids=items.map(i=>String(i.menuItemId||""));const {rows:menu}=await client.query(`SELECT id,name,price FROM menu_items WHERE id=ANY($1::uuid[]) AND restaurant_id=$2 AND is_available=true`,[ids,rid]);if(menu.length!==new Set(ids).size)throw Object.assign(new Error("بعض المنتجات لم تعد متاحة"),{status:400});const map=new Map(menu.map(x=>[String(x.id),x]));let subtotal=0;const normalized=[];for(const raw of items){const item=map.get(String(raw.menuItemId)),q=Math.floor(Number(raw.quantity));if(!item||!Number.isFinite(q)||q<1||q>50)throw Object.assign(new Error("بيانات السلة غير صحيحة"),{status:400});const unit=money(item.price),line=money(unit*q);subtotal+=line;normalized.push({item,q,unit,line})}out.push({restaurantId:rid,subtotal:money(subtotal),items:normalized})}return out}
function paymentParts(body,total){const method=String(body.paymentMethod||"cash");if(method!=="split")return [{method,amount:total}];if(!Array.isArray(body.payments)||!body.payments.length)throw Object.assign(new Error("حدد طرق الدفع وقيمها"),{status:400});const parts=body.payments.map(p=>({method:String(p.method||""),amount:money(p.amount),reference:p.reference?String(p.reference).trim():null,receiptBase64:p.receiptBase64||null,receiptMime:p.receiptMime||null}));const allowed=["cash","wallet","vodafone_cash","instapay"];if(parts.some(p=>!allowed.includes(p.method)||p.amount<=0))throw Object.assign(new Error("طريقة أو قيمة دفع غير صحيحة"),{status:400});if(Math.abs(parts.reduce((s,p)=>s+p.amount,0)-total)>0.01)throw Object.assign(new Error("إجمالي وسائل الدفع يجب أن يساوي إجمالي الطلب"),{status:400});return parts}
async function applyWallet(client,userId,amount,referenceId){if(amount<=0)return;const {rows}=await client.query(`SELECT balance FROM customer_wallets WHERE user_id=$1 FOR UPDATE`,[userId]);if(!rows[0]||Number(rows[0].balance)<amount)throw Object.assign(new Error("رصيد المحفظة غير كافٍ"),{status:400});const after=money(Number(rows[0].balance)-amount);await client.query(`UPDATE customer_wallets SET balance=$1,updated_at=now() WHERE user_id=$2`,[after,userId]);await client.query(`INSERT INTO wallet_transactions(user_id,type,amount,balance_after,reference_type,reference_id,note) VALUES($1,'debit',$2,$3,'checkout',$4,'دفع من المحفظة')`,[userId,amount,after,referenceId])}
async function couponDiscount(client,userId,code,subtotal){if(!code)return {id:null,code:null,discount:0};const {rows}=await client.query(`SELECT * FROM coupons WHERE code=$1 AND is_active=true FOR UPDATE`,[String(code).trim().toUpperCase()]);const c=rows[0];const now=new Date();if(!c)throw Object.assign(new Error("الكوبون غير موجود أو غير فعال"),{status:400});if(new Date(c.starts_at)>now||(c.expires_at&&new Date(c.expires_at)<now))throw Object.assign(new Error("الكوبون غير صالح حاليًا"),{status:400});if(Number(c.usage_limit||0)>0&&Number(c.used_count)>=Number(c.usage_limit))throw Object.assign(new Error("انتهى استخدام الكوبون"),{status:400});if(subtotal<Number(c.min_order_amount||0))throw Object.assign(new Error(`الحد الأدنى للكوبون ${Number(c.min_order_amount).toFixed(2)} ج.م`),{status:400});const used=await client.query(`SELECT 1 FROM coupon_usages WHERE coupon_id=$1 AND user_id=$2 LIMIT 1`,[c.id,userId]);if(used.rows[0])throw Object.assign(new Error("استخدمت هذا الكوبون من قبل"),{status:400});let discount=c.discount_type==='percentage'?subtotal*Number(c.discount_value)/100:Number(c.discount_value);if(c.max_discount!=null)discount=Math.min(discount,Number(c.max_discount));return {id:c.id,code:c.code,discount:money(Math.min(discount,subtotal)),row:c}}
async function notifyRestaurants(orders){for(const o of orders)await notifyUser(o.restaurant_id,"طلب جديد","لديك طلب جديد يحتاج للمراجعة","order",{orderId:o.id,checkoutId:o.checkout_id})}
router.post("/bulk",requireAuth,requireRole("customer"),async(req,res,next)=>{const b=req.body||{};const key=String(b.idempotencyKey||"").trim();if(!key)return res.status(400).json({error:"مفتاح العملية مطلوب"});if(key.length>100)return res.status(400).json({error:"مفتاح العملية غير صحيح"});const address=b.deliveryAddress?String(b.deliveryAddress).trim():"";const hasLat=b.deliveryLatitude!==undefined&&b.deliveryLatitude!==null&&b.deliveryLatitude!=="";const hasLon=b.deliveryLongitude!==undefined&&b.deliveryLongitude!==null&&b.deliveryLongitude!=="";if(!address&&!hasLat&&!hasLon)return res.status(400).json({error:"اكتب العنوان أو حدد الموقع"});if((hasLat!==hasLon)|| (hasLat&&(!coord(b.deliveryLatitude,-90,90)||!coord(b.deliveryLongitude,-180,180))))return res.status(400).json({error:"إحداثيات الموقع غير صحيحة"});const client=await pool.connect();try{await client.query("BEGIN");const existing=await client.query(`SELECT * FROM checkout_sessions WHERE customer_id=$1 AND idempotency_key=$2 FOR UPDATE`,[req.user.id,key]);if(existing.rows[0]){const orders=await client.query(`SELECT * FROM orders WHERE checkout_id=$1 ORDER BY created_at`,[existing.rows[0].id]);await client.query("COMMIT");return res.status(200).json({checkout:existing.rows[0],orders:orders.rows,idempotent:true})}
 const groups=await normalize(client,b.orders);const lat=hasLat?Number(b.deliveryLatitude):null,lon=hasLon?Number(b.deliveryLongitude):null;const d=await deliveryFee(client,groups.map(x=>x.restaurantId),lat,lon);const subtotal=money(groups.reduce((s,g)=>s+g.subtotal,0));const coupon=await couponDiscount(client,req.user.id,b.couponCode,subtotal);const total=money(Math.max(0,subtotal+d.fee-coupon.discount+money(b.adminFee||0)));const parts=paymentParts(b,total);let walletAmount=0,verifiedTransfer=0,cashDue=0;for(const p of parts){if(p.method==='wallet')walletAmount+=p.amount;else if(p.method==='cash')cashDue+=p.amount;else if(p.method==='vodafone_cash'||p.method==='instapay')verifiedTransfer+=p.amount}
 if(walletAmount>0)await applyWallet(client,req.user.id,walletAmount,"00000000-0000-0000-0000-000000000000");
 const pendingTransfer=parts.some(p=>(p.method==='vodafone_cash'||p.method==='instapay')&&p.amount>0);const paidNow=money(walletAmount);const paymentStatus=pendingTransfer?'pending':money(paidNow+verifiedTransfer)>=total-0.01?'paid':"partially_paid";
 const {rows:[checkout]}=await client.query(`INSERT INTO checkout_sessions(customer_id,delivery_latitude,delivery_longitude,delivery_address,restaurants_count,subtotal,delivery_fee,total_amount,payment_method,order_notes,idempotency_key,coupon_id,coupon_code,discount_amount,admin_fee,payment_status,paid_amount,cash_due) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) RETURNING *`,[req.user.id,lat,lon,address||null,groups.length,subtotal,d.fee,total,String(b.paymentMethod||'cash'),b.orderNotes?String(b.orderNotes).trim():null,key,coupon.id,coupon.code,coupon.discount,money(b.adminFee||0),paymentStatus,paidNow,cashDue]);
 const orders=[];for(let idx=0;idx<groups.length;idx++){const g=groups[idx];const share=idx===0?money(d.fee+money(b.adminFee||0)):0;const groupDiscount=subtotal?money(coupon.discount*(g.subtotal/subtotal)):0;const orderTotal=money(Math.max(0,g.subtotal+share-groupDiscount));const {rows:[order]}=await client.query(`INSERT INTO orders(customer_id,restaurant_id,checkout_id,status,delivery_latitude,delivery_longitude,delivery_address,delivery_distance_meters,delivery_fee,total_amount,subtotal,payment_method,order_notes,coupon_code,discount_amount,admin_fee,payment_status,paid_amount,cash_due) VALUES($1,$2,$3,'restaurant_pending',$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) RETURNING *`,[req.user.id,g.restaurantId,checkout.id,lat,lon,address||null,d.distance,share,orderTotal,g.subtotal,String(b.paymentMethod||'cash'),b.orderNotes?String(b.orderNotes).trim():null,coupon.code,groupDiscount,share,paymentStatus,0,0]);for(const x of g.items)await client.query(`INSERT INTO order_items(order_id,menu_item_id,item_name,unit_price,quantity,line_total) VALUES($1,$2,$3,$4,$5,$6)`,[order.id,x.item.id,x.item.name,x.unit,x.q,x.line]);orders.push(order)}
 let remaining=total;for(const o of orders){const share=orders.length===1?remaining:money(total*(Number(o.total_amount)/total));const paidShare=money(Math.min(share,paidNow*(Number(o.total_amount)/total)));const cashShare=money(Math.min(share-paidShare,cashDue*(Number(o.total_amount)/Math.max(total,1))));await client.query(`UPDATE orders SET paid_amount=$1,cash_due=$2 WHERE id=$3`,[paidShare,o.id,cashShare]);remaining=money(remaining-share)}
 if(coupon.id){await client.query(`INSERT INTO coupon_usages(coupon_id,user_id,checkout_id,discount_amount) VALUES($1,$2,$3,$4)`,[coupon.id,req.user.id,checkout.id,coupon.discount]);await client.query(`UPDATE coupons SET used_count=used_count+1,updated_at=now() WHERE id=$1`,[coupon.id])}
 const receiptParts=parts.filter(p=>p.method==='vodafone_cash'||p.method==='instapay');for(const p of parts){await client.query(`INSERT INTO order_payments(checkout_id,customer_id,method,amount,status,receipt_base64,receipt_mime,transaction_reference) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[checkout.id,req.user.id,p.method,p.amount,p.method==='cash'||p.method==='wallet'?'verified':'pending',p.receiptBase64||null,p.receiptMime||null,p.reference||null])}
 await client.query("COMMIT");const canNotify=!pendingTransfer; if(canNotify)await notifyRestaurants(orders);await notifyRole("admin","طلب جديد","تم إنشاء طلب جديد.","order",{checkoutId:checkout.id,paymentStatus});res.status(201).json({checkout,orders,paymentStatus,paymentPending:pendingTransfer});
 }catch(e){try{await client.query("ROLLBACK")}catch{};if(e.code==='23505'&&key){try{const {rows}=await pool.query(`SELECT * FROM checkout_sessions WHERE customer_id=$1 AND idempotency_key=$2`,[req.user.id,key]);if(rows[0])return res.status(200).json({checkout:rows[0],idempotent:true})}catch{}}if(e.status)return res.status(e.status).json({error:e.message});next(e)}finally{client.release()}});
module.exports=router;
