const express=require('express');
const router=express.Router();
const {pool}=require('../db');
const {requireAuth,requireRole}=require('../auth');
const {notifyUser,notifyRole}=require('../push');
const EDITABLE=['restaurant_pending','preparing'];
const money=v=>Math.round(Math.max(0,Number(v)||0)*100)/100;
async function loadOrder(c,id,userId){const {rows}=await c.query(`SELECT * FROM orders WHERE id=$1 AND customer_id=$2 FOR UPDATE`,[id,userId]);if(!rows[0])throw Object.assign(new Error('الطلب غير موجود أو غير مصرح لك'),{status:404});if(!EDITABLE.includes(rows[0].status))throw Object.assign(new Error('لا يمكن تعديل الطلب بعد الجاهزية'),{status:409});return rows[0]}
async function recalc(c,o){const {rows:s}=await c.query(`SELECT COALESCE(SUM(line_total) FILTER(WHERE availability_status IN ('available','replacement_selected')),0) subtotal FROM order_items WHERE order_id=$1`,[o.id]);const subtotal=money(s[0].subtotal),delivery=money(o.delivery_fee),discount=money(o.discount_amount),fee=money(o.admin_fee),total=money(Math.max(0,subtotal+delivery+fee-discount));const paid=money(o.paid_amount),cashDue=money(Math.max(0,total-paid));await c.query(`UPDATE orders SET subtotal=$1,total_amount=$2,cash_due=$3,payment_status=$4,updated_at=now() WHERE id=$5`,[subtotal,total,cashDue,total<=0||paid+cashDue>=total-.01?'paid':paid>0||cashDue>0?'partially_paid':'pending',o.id]);if(o.checkout_id){const {rows:x}=await c.query(`SELECT COALESCE(SUM(subtotal),0) subtotal,COALESCE(SUM(delivery_fee),0) delivery_fee,COALESCE(SUM(admin_fee),0) admin_fee,COALESCE(SUM(discount_amount),0) discount_amount,COALESCE(SUM(total_amount),0) total FROM orders WHERE checkout_id=$1`,[o.checkout_id]);const z=x[0],ct=money(z.total),cq=await c.query(`SELECT paid_amount FROM checkout_sessions WHERE id=$1 FOR UPDATE`,[o.checkout_id]),cp=money(cq.rows[0]?.paid_amount),cd=money(Math.max(0,ct-cp));await c.query(`UPDATE checkout_sessions SET subtotal=$1,delivery_fee=$2,admin_fee=$3,discount_amount=$4,total_amount=$5,cash_due=$6,payment_status=$7,updated_at=now() WHERE id=$8`,[money(z.subtotal),money(z.delivery_fee),money(z.admin_fee),money(z.discount_amount),ct,cd,ct<=0||cp+cd>=ct-.01?'paid':cp>0||cd>0?'partially_paid':'pending',o.checkout_id])}return (await c.query(`SELECT * FROM orders WHERE id=$1`,[o.id])).rows[0]}
router.patch('/:id/items/:itemId',requireAuth,requireRole('customer'),async(req,res,next)=>{const qty=Math.floor(Number(req.body?.quantity));if(!Number.isFinite(qty)||qty<1||qty>50)return res.status(400).json({error:'الكمية يجب أن تكون بين 1 و50'});const c=await pool.connect();try{await c.query('BEGIN');const o=await loadOrder(c,req.params.id,req.user.id);const q=await c.query(`SELECT * FROM order_items WHERE id=$1 AND order_id=$2 FOR UPDATE`,[req.params.itemId,o.id]);if(!q.rows[0])return res.status(404).json({error:'الصنف غير موجود'});const item=q.rows[0];if(item.availability_status==='removed')return res.status(409).json({error:'الصنف محذوف ولا يمكن تعديل كميته'});await c.query(`UPDATE order_items SET quantity=$1,line_total=unit_price*$1,updated_at=now() WHERE id=$2`,[qty,item.id]);const order=await recalc(c,o);await c.query(`INSERT INTO audit_logs(actor_id,action,entity_type,entity_id,metadata) VALUES($1,'customer_order_item_quantity_changed','order',$2,$3::jsonb)`,[req.user.id,o.id,JSON.stringify({itemId:item.id,from:item.quantity,to:qty})]);await c.query('COMMIT');await notifyRole('staff','العميل عدّل طلبًا',`تم تعديل كمية «${item.item_name}» في طلب العميل.`,'order',{orderId:o.id,itemId:item.id});res.json({order})}catch(e){await c.query('ROLLBACK');if(e.status)return res.status(e.status).json({error:e.message});next(e)}finally{c.release()}});
router.delete('/:id/items/:itemId',requireAuth,requireRole('customer'),async(req,res,next)=>{const c=await pool.connect();try{await c.query('BEGIN');const o=await loadOrder(c,req.params.id,req.user.id);const q=await c.query(`SELECT * FROM order_items WHERE id=$1 AND order_id=$2 FOR UPDATE`,[req.params.itemId,o.id]);if(!q.rows[0])return res.status(404).json({error:'الصنف غير موجود'});const item=q.rows[0];await c.query(`UPDATE order_items SET availability_status='removed',updated_at=now() WHERE id=$1`,[item.id]);const order=await recalc(c,o);await c.query(`INSERT INTO audit_logs(actor_id,action,entity_type,entity_id,metadata) VALUES($1,'customer_order_item_removed','order',$2,$3::jsonb)`,[req.user.id,o.id,JSON.stringify({itemId:item.id,itemName:item.item_name})]);await c.query('COMMIT');await notifyRole('staff','العميل حذف صنفًا',`تم حذف «${item.item_name}» من الطلب.`,'order',{orderId:o.id,itemId:item.id});res.json({order})}catch(e){await c.query('ROLLBACK');if(e.status)return res.status(e.status).json({error:e.message});next(e)}finally{c.release()}});
router.post('/:id/items',requireAuth,requireRole('customer'),async(req,res,next)=>{const menuItemId=String(req.body?.menuItemId||''),qty=Math.floor(Number(req.body?.quantity||1));if(!menuItemId||!Number.isFinite(qty)||qty<1||qty>50)return res.status(400).json({error:'بيانات الصنف غير صحيحة'});const c=await pool.connect();try{await c.query('BEGIN');const o=await loadOrder(c,req.params.id,req.user.id);const mq=await c.query(`SELECT id,name,price FROM menu_items WHERE id=$1 AND restaurant_id=$2 AND is_available=true`,[menuItemId,o.restaurant_id]);if(!mq.rows[0])return res.status(400).json({error:'الصنف غير متاح حاليًا أو ليس تابعًا للمطعم'});const m=mq.rows[0],existing=await c.query(`SELECT * FROM order_items WHERE order_id=$1 AND menu_item_id=$2 AND availability_status IN ('available','replacement_selected') FOR UPDATE`,[o.id,m.id]);if(existing.rows[0]){const nq=Math.min(50,Number(existing.rows[0].quantity)+qty);await c.query(`UPDATE order_items SET quantity=$1,line_total=unit_price*$1,updated_at=now() WHERE id=$2`,[nq,existing.rows[0].id])}else await c.query(`INSERT INTO order_items(order_id,menu_item_id,item_name,unit_price,quantity,line_total,availability_status) VALUES($1,$2,$3,$4,$5,$6,'available')`,[o.id,m.id,m.name,m.price,qty,money(Number(m.price)*qty)]);const order=await recalc(c,o);await c.query(`INSERT INTO audit_logs(actor_id,action,entity_type,entity_id,metadata) VALUES($1,'customer_order_item_added','order',$2,$3::jsonb)`,[req.user.id,o.id,JSON.stringify({menuItemId:m.id,itemName:m.name,quantity:qty})]);await c.query('COMMIT');await notifyRole('staff','العميل أضاف صنفًا',`تمت إضافة «${m.name}» إلى الطلب.`,'order',{orderId:o.id,menuItemId:m.id});res.status(201).json({order})}catch(e){await c.query('ROLLBACK');if(e.status)return res.status(e.status).json({error:e.message});next(e)}finally{c.release()}});
module.exports=router;
