const express=require("express");
const router=express.Router();
const {pool}=require("../db");
const {requireAuth,requireRole}=require("../auth");
const activeDeliveryStatuses=["assigned","picked_up","on_the_way"];
function validCoordinate(v,min,max){const n=Number(v);return Number.isFinite(n)&&n>=min&&n<=max}
function distanceMeters(a,b,c,d){const R=6371000,toRad=x=>x*Math.PI/180;const p1=toRad(a),p2=toRad(c),dp=toRad(c-a),dl=toRad(d-b);const x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return Math.round(2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x)))}
async function calcDelivery(client,restaurantId,lat,lon){if(lat==null||lon==null)return {fee:0,distance:null};const p=await client.query(`SELECT latitude,longitude FROM restaurant_profiles WHERE restaurant_id=$1`,[restaurantId]);let distance=null;if(p.rows[0]?.latitude!=null&&p.rows[0]?.longitude!=null)distance=distanceMeters(Number(p.rows[0].latitude),Number(p.rows[0].longitude),Number(lat),Number(lon));const z=await client.query(`SELECT fixed_price FROM delivery_zones WHERE is_active=true AND min_latitude IS NOT NULL AND max_latitude IS NOT NULL AND min_longitude IS NOT NULL AND max_longitude IS NOT NULL AND $1 BETWEEN min_latitude AND max_latitude AND $2 BETWEEN min_longitude AND max_longitude ORDER BY fixed_price NULLS LAST LIMIT 1`,[lat,lon]);if(z.rows[0]?.fixed_price!=null)return {fee:Number(z.rows[0].fixed_price),distance};if(distance!=null){const r=await client.query(`SELECT price FROM delivery_distance_rates WHERE is_active=true AND min_meters<= $1 AND (max_meters IS NULL OR max_meters>= $1) ORDER BY min_meters DESC LIMIT 1`,[distance]);if(r.rows[0])return {fee:Number(r.rows[0].price),distance}}return {fee:0,distance}}

async function normalizeAndCreateOrder(client,userId,group,b){
 const restaurantId=String(group?.restaurantId||"");
 const items=Array.isArray(group?.items)?group.items:[];
 if(!restaurantId||!items.length)throw Object.assign(new Error("بيانات أحد المطاعم غير صحيحة"),{status:400});
 const ids=items.map(i=>String(i.menuItemId||""));
 if(ids.some(id=>!id))throw Object.assign(new Error("بيانات المنتجات غير صحيحة"),{status:400});
 const {rows:menu}=await client.query(`SELECT id,name,price FROM menu_items WHERE id=ANY($1::uuid[]) AND restaurant_id=$2 AND is_available=true`,[ids,restaurantId]);
 if(menu.length!==new Set(ids).size)throw Object.assign(new Error("بعض المنتجات لم تعد متاحة"),{status:400});
 const byId=new Map(menu.map(i=>[String(i.id),i]));let subtotal=0;const normalized=[];
 for(const raw of items){const item=byId.get(String(raw.menuItemId));const quantity=Math.floor(Number(raw.quantity));if(!item||!Number.isFinite(quantity)||quantity<1||quantity>50)throw Object.assign(new Error("بيانات السلة غير صحيحة"),{status:400});const unit=Number(item.price),line=unit*quantity;subtotal+=line;normalized.push({item,quantity,unit,line});}
 const coords=b.deliveryLatitude!=null&&b.deliveryLongitude!=null&&b.deliveryLatitude!==""&&b.deliveryLongitude!=="";
 const delivery=await calcDelivery(client,restaurantId,coords?Number(b.deliveryLatitude):null,coords?Number(b.deliveryLongitude):null);
 const address=b.deliveryAddress?String(b.deliveryAddress).trim():"";
 const total=subtotal+delivery.fee;
 const {rows:[order]}=await client.query(`INSERT INTO orders(customer_id,restaurant_id,status,delivery_latitude,delivery_longitude,delivery_address,delivery_distance_meters,delivery_fee,total_amount,subtotal,payment_method,order_notes) VALUES($1,$2,'restaurant_pending',$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[userId,restaurantId,coords?Number(b.deliveryLatitude):null,coords?Number(b.deliveryLongitude):null,address||null,delivery.distance,delivery.fee,total,subtotal,String(b.paymentMethod||"cash"),b.orderNotes?String(b.orderNotes).trim():null]);
 for(const x of normalized)await client.query(`INSERT INTO order_items(order_id,menu_item_id,item_name,unit_price,quantity,line_total) VALUES($1,$2,$3,$4,$5,$6)`,[order.id,x.item.id,x.item.name,x.unit,x.quantity,x.line]);
 await client.query(`INSERT INTO notifications(user_id,title,body,type,data) VALUES($1,'طلب جديد','لديك طلب جديد يحتاج للمراجعة','order',$2)`,[restaurantId,JSON.stringify({orderId:order.id})]);
 return {order,subtotal,deliveryFee:delivery.fee,total};
}

router.post("/bulk",requireAuth,requireRole("customer"),async(req,res,next)=>{const b=req.body||{},groups=Array.isArray(b.orders)?b.orders:[];try{const hasLat=b.deliveryLatitude!==undefined&&b.deliveryLatitude!==null&&b.deliveryLatitude!=="",hasLon=b.deliveryLongitude!==undefined&&b.deliveryLongitude!==null&&b.deliveryLongitude!=="",coords=hasLat&&hasLon;if(coords&&(!validCoordinate(b.deliveryLatitude,-90,90)||!validCoordinate(b.deliveryLongitude,-180,180)))return res.status(400).json({error:"إحداثيات موقع التوصيل غير صحيحة"});const address=b.deliveryAddress?String(b.deliveryAddress).trim():"";if(!address&&!coords)return res.status(400).json({error:"اكتب عنوان التوصيل أو حدد موقعك على الخريطة"});if(!groups.length)return res.status(400).json({error:"السلة فارغة"});const unique=new Set(groups.map(g=>String(g?.restaurantId||"")));if(unique.size!==groups.length)return res.status(400).json({error:"يوجد تكرار غير صحيح في المطاعم"});const client=await pool.connect();try{await client.query("BEGIN");const results=[];for(const group of groups)results.push(await normalizeAndCreateOrder(client,req.user.id,group,b));await client.query("COMMIT");res.status(201).json({orders:results.map(x=>x.order),summary:{restaurants:results.length,subtotal:results.reduce((s,x)=>s+x.subtotal,0),deliveryFees:results.reduce((s,x)=>s+x.deliveryFee,0),total:results.reduce((s,x)=>s+x.total,0)}})}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}catch(e){if(e.status)return res.status(e.status).json({error:e.message});next(e)}});

router.post("/",requireAuth,requireRole("customer"),async(req,res,next)=>{const b=req.body||{},hasLat=b.deliveryLatitude!==undefined&&b.deliveryLatitude!==null&&b.deliveryLatitude!=="",hasLon=b.deliveryLongitude!==undefined&&b.deliveryLongitude!==null&&b.deliveryLongitude!=="",coords=hasLat&&hasLon;try{if(coords&&(!validCoordinate(b.deliveryLatitude,-90,90)||!validCoordinate(b.deliveryLongitude,-180,180)))return res.status(400).json({error:"إحداثيات موقع التوصيل غير صحيحة"});const address=b.deliveryAddress?String(b.deliveryAddress).trim():"";if(!address&&!coords)return res.status(400).json({error:"اكتب عنوان التوصيل أو حدد موقعك على الخريطة"});const result=await (async()=>{const client=await pool.connect();try{await client.query("BEGIN");const x=await normalizeAndCreateOrder(client,req.user.id,{restaurantId:b.restaurantId,items:b.items},b);await client.query("COMMIT");return x}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}})();res.status(201).json(result)}catch(e){if(e.status)return res.status(e.status).json({error:e.message});next(e)}});

router.patch("/:id/restaurant-decision",requireAuth,requireRole("restaurant","admin","staff"),async(req,res,next)=>{try{const approve=Boolean(req.body?.approve),reason=String(req.body?.reason||"").trim();if(!approve&&!reason)return res.status(400).json({error:"اكتب سبب الرفض"});const where=req.user.role==="restaurant"?"restaurant_id=$2":"TRUE";const q=approve?`UPDATE orders SET status='confirmed',updated_at=now() WHERE id=$1 AND ${where} AND status='restaurant_pending' RETURNING *`:`UPDATE orders SET status='restaurant_rejected',restaurant_rejection_reason=$3,updated_at=now() WHERE id=$1 AND ${where} AND status='restaurant_pending' RETURNING *`;const params=req.user.role==="restaurant"?[req.params.id,req.user.id,reason]:[req.params.id,null,reason];const {rows}=await pool.query(q,params);if(!rows[0])return res.status(404).json({error:"الطلب غير متاح لاتخاذ القرار"});res.json({order:rows[0]})}catch(e){next(e)}});
router.get("/restaurant/mine",requireAuth,requireRole("restaurant"),async(req,res,next)=>{try{const {rows}=await pool.query(`SELECT o.*,c.full_name AS customer_name,c.phone AS customer_phone,(SELECT json_agg(oi ORDER BY oi.created_at) FROM order_items oi WHERE oi.order_id=o.id) AS items FROM orders o JOIN users c ON c.id=o.customer_id WHERE o.restaurant_id=$1 ORDER BY o.updated_at DESC LIMIT 200`,[req.user.id]);res.json({orders:rows})}catch(e){next(e)}});
router.patch("/:id/restaurant-status",requireAuth,requireRole("restaurant"),async(req,res,next)=>{try{const nextStatus=String(req.body?.status||"");const transitions={preparing:"confirmed",ready:"preparing"};const previous=transitions[nextStatus];if(!previous)return res.status(400).json({error:"حالة المطعم غير صحيحة"});const {rows}=await pool.query(`UPDATE orders SET status=$1,updated_at=now() WHERE id=$2 AND restaurant_id=$3 AND status=$4 RETURNING *`,[nextStatus,req.params.id,req.user.id,previous]);if(!rows[0])return res.status(400).json({error:"لا يمكن تغيير حالة الطلب بهذه الطريقة"});res.json({order:rows[0]})}catch(e){next(e)}});
router.patch("/:id/admin-decision",requireAuth,requireRole("admin","staff"),async(req,res,next)=>{try{const approve=Boolean(req.body?.approve),reason=String(req.body?.reason||"").trim();if(!approve&&!reason)return res.status(400).json({error:"اكتب سبب الرفض"});const {rows}=await pool.query(approve?`UPDATE orders SET status='confirmed',updated_at=now() WHERE id=$1 AND status IN ('pending','restaurant_pending') RETURNING *`:`UPDATE orders SET status='admin_rejected',admin_rejection_reason=$2,updated_at=now() WHERE id=$1 AND status NOT IN ('delivered','cancelled') RETURNING *`,approve?[req.params.id]:[req.params.id,reason]);if(!rows[0])return res.status(404).json({error:"الطلب غير متاح"});res.json({order:rows[0]})}catch(e){next(e)}});
router.patch("/:id/cancel",requireAuth,requireRole("admin","staff","restaurant","customer"),async(req,res,next)=>{try{const reason=String(req.body?.reason||"").trim();if(!reason)return res.status(400).json({error:"اكتب سبب الإلغاء"});const {rows}=await pool.query(`UPDATE orders SET status='cancelled',cancelled_by=$1,cancellation_reason=$2,updated_at=now() WHERE id=$3 AND status NOT IN ('delivered','cancelled') RETURNING *`,[req.user.id,reason,req.params.id]);if(!rows[0])return res.status(404).json({error:"الطلب غير متاح للإلغاء"});res.json({order:rows[0]})}catch(e){next(e)}});
router.get("/mine",requireAuth,requireRole("customer"),async(req,res,next)=>{try{const {rows}=await pool.query(`SELECT o.*,u.full_name AS driver_name,u.phone AS driver_phone,l.latitude AS driver_latitude,l.longitude AS driver_longitude,l.accuracy AS driver_accuracy,l.heading AS driver_heading,l.speed AS driver_speed,l.updated_at AS driver_location_updated_at,(SELECT json_agg(oi ORDER BY oi.created_at) FROM order_items oi WHERE oi.order_id=o.id) AS items FROM orders o LEFT JOIN users u ON u.id=o.driver_id LEFT JOIN user_locations l ON l.user_id=o.driver_id WHERE o.customer_id=$1 ORDER BY o.created_at DESC LIMIT 50`,[req.user.id]);res.json({orders:rows})}catch(e){next(e)}});
router.get("/driver/available",requireAuth,requireRole("driver"),async(req,res,next)=>{try{const me=await pool.query(`SELECT is_online,is_available FROM users WHERE id=$1 AND status='active' AND role='driver'`,[req.user.id]);if(!me.rows[0]||!me.rows[0].is_online||!me.rows[0].is_available)return res.json({orders:[]});const {rows}=await pool.query(`SELECT o.id,o.status,o.restaurant_id,o.delivery_latitude,o.delivery_longitude,o.delivery_address,o.total_amount,o.created_at,o.updated_at,c.full_name AS customer_name,c.phone AS customer_phone,(SELECT json_agg(oi ORDER BY oi.created_at) FROM order_items oi WHERE oi.order_id=o.id) AS items FROM orders o JOIN users c ON c.id=o.customer_id WHERE o.driver_id IS NULL AND o.status IN ('confirmed','preparing','ready') ORDER BY o.created_at ASC LIMIT 100`);res.json({orders:rows})}catch(e){next(e)}});
router.patch("/:id/claim",requireAuth,requireRole("driver"),async(req,res,next)=>{try{const {rows}=await pool.query(`UPDATE orders SET driver_id=$1,status='assigned',updated_at=now() WHERE id=$2 AND driver_id IS NULL AND status IN ('confirmed','preparing','ready') AND EXISTS(SELECT 1 FROM users WHERE id=$1 AND role='driver' AND status='active' AND is_online=true AND is_available=true) RETURNING *`,[req.user.id,req.params.id]);if(!rows[0])return res.status(409).json({error:"الطلب غير متاح أو أنت غير متاح للاستلام"});res.json({order:rows[0]})}catch(e){next(e)}});
router.get("/driver/mine",requireAuth,requireRole("driver"),async(req,res,next)=>{try{const {rows}=await pool.query(`SELECT o.*,c.full_name AS customer_name,c.phone AS customer_phone,c.secondary_phone AS customer_secondary_phone,(SELECT json_agg(oi ORDER BY oi.created_at) FROM order_items oi WHERE oi.order_id=o.id) AS items FROM orders o JOIN users c ON c.id=o.customer_id WHERE o.driver_id=$1 AND o.status IN ('assigned','picked_up','on_the_way') ORDER BY o.updated_at DESC`,[req.user.id]);res.json({orders:rows})}catch(e){next(e)}});
router.get("/admin",requireAuth,requireRole("admin","staff"),async(_req,res,next)=>{try{const {rows}=await pool.query(`SELECT o.*,c.full_name AS customer_name,c.phone AS customer_phone,d.full_name AS driver_name,d.phone AS driver_phone,(SELECT json_agg(oi ORDER BY oi.created_at) FROM order_items oi WHERE oi.order_id=o.id) AS items FROM orders o JOIN users c ON c.id=o.customer_id LEFT JOIN users d ON d.id=o.driver_id ORDER BY o.updated_at DESC LIMIT 200`);res.json({orders:rows})}catch(e){next(e)}});
router.patch("/:id/assign",requireAuth,requireRole("admin","staff"),async(req,res,next)=>{try{const driverId=String(req.body?.driverId||"");const driver=await pool.query("SELECT id FROM users WHERE id=$1 AND role='driver' AND status='active'",[driverId]);if(!driver.rows[0])return res.status(400).json({error:"المندوب غير موجود أو غير نشط"});const {rows}=await pool.query(`UPDATE orders SET driver_id=$1,status='assigned',updated_at=now() WHERE id=$2 AND status NOT IN ('delivered','cancelled') RETURNING *`,[driverId,req.params.id]);if(!rows[0])return res.status(404).json({error:"الطلب غير موجود أو مغلق"});res.json({order:rows[0]})}catch(e){next(e)}});
router.patch("/:id/status",requireAuth,requireRole("driver"),async(req,res,next)=>{try{const requested=String(req.body?.status||"");const transitions={picked_up:"assigned",on_the_way:"picked_up",delivered:"on_the_way"};const previous=transitions[requested];if(!previous)return res.status(400).json({error:"انتقال الحالة غير صحيح"});const {rows}=await pool.query(`UPDATE orders SET status=$1,updated_at=now() WHERE id=$2 AND driver_id=$3 AND status=$4 RETURNING *`,[requested,req.params.id,req.user.id,previous]);if(!rows[0])return res.status(404).json({error:"الطلب غير موجود أو حالته تغيرت"});res.json({order:rows[0]})}catch(e){next(e)}});
module.exports=router;
