const express=require('express');const router=express.Router();const{pool}=require('../db');const{requireAuth,requireRole}=require('../auth');
function month(){return new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Cairo',year:'numeric',month:'2-digit'});}
async function rollMembership(client,userId){const key=month();const q=await client.query(`SELECT cm.*,mt.name,mt.sort_order,mt.maintenance_orders,mt.upgrade_orders,mt.is_active FROM customer_memberships cm LEFT JOIN membership_tiers mt ON mt.id=cm.tier_id WHERE cm.user_id=$1 FOR UPDATE`,[userId]);if(!q.rows[0])return null;let m=q.rows[0];if(m.month_key===key)return m;const tiers=(await client.query(`SELECT * FROM membership_tiers WHERE is_active=true ORDER BY sort_order`)).rows;const current=tiers.find(t=>String(t.id)===String(m.tier_id))||tiers[0];const previous=tiers.filter(t=>Number(t.sort_order)<Number(current?.sort_order)).sort((a,b)=>b.sort_order-a.sort_order)[0]||current;const keep=Number(m.maintenance_orders_count||m.orders_count||0)>=Number(current?.maintenance_orders||0);const nextTier=keep?current:previous;await client.query(`UPDATE customer_memberships SET last_month_tier_id=tier_id,tier_id=$2,started_tier_id=$2,month_key=$3,orders_count=0,maintenance_orders_count=0,upgrade_orders_count=0,updated_at=now() WHERE user_id=$1`,[userId,nextTier.id,key]);return (await client.query(`SELECT cm.*,mt.name,mt.sort_order,mt.maintenance_orders,mt.upgrade_orders,mt.badge_label,mt.badge_type,mt.badge_image_url,mt.rewards,mt.benefits FROM customer_memberships cm LEFT JOIN membership_tiers mt ON mt.id=cm.tier_id WHERE cm.user_id=$1`,[userId])).rows[0];}
router.get('/membership',requireAuth,requireRole('customer'),async(req,res,next)=>{const c=await pool.connect();try{await c.query('BEGIN');const m=await rollMembership(c,req.user.id);const tiers=(await c.query(`SELECT id,name,sort_order,maintenance_orders,upgrade_orders,badge_label,badge_type,badge_image_url,rewards,benefits FROM membership_tiers WHERE is_active=true ORDER BY sort_order`)).rows;await c.query('COMMIT');const current=tiers.find(t=>String(t.id)===String(m?.tier_id));const next=tiers.filter(t=>Number(t.sort_order)>Number(current?.sort_order||0))[0]||null;res.json({membership:m,currentTier:current,nextTier:next})}catch(e){await c.query('ROLLBACK');next(e)}finally{c.release()}});
router.get('/ui',requireAuth,requireRole('admin'),async(req,res,next)=>{try{const{rows}=await pool.query('SELECT * FROM platform_ui_settings WHERE id=1');res.json({settings:rows[0]})}catch(e){next(e)}});
router.patch('/ui',requireAuth,requireRole('admin'),async(req,res,next)=>{try{const b=req.body||{};const{rows}=await pool.query(`UPDATE platform_ui_settings SET show_banners=COALESCE($1,show_banners),show_categories=COALESCE($2,show_categories),sections=COALESCE($3,sections),updated_at=now() WHERE id=1 RETURNING *`,[b.showBanners,b.showCategories,JSON.stringify(Array.isArray(b.sections)?b.sections:[])]);res.json({settings:rows[0]})}catch(e){next(e)}});
router.get('/tiers',requireAuth,requireRole('admin'),async(req,res,next)=>{try{const{rows}=await pool.query(`SELECT * FROM membership_tiers ORDER BY sort_order`);res.json({tiers:rows})}catch(e){next(e)}});
router.post('/tiers',requireAuth,requireRole('admin'),async(req,res,next)=>{try{const b=req.body||{};if(!String(b.name||'').trim())return res.status(400).json({error:'اكتب اسم الفئة'});const{rows}=await pool.query(`INSERT INTO membership_tiers(name,monthly_orders,maintenance_orders,upgrade_orders,badge_label,badge_type,badge_image_url,rewards,benefits,sort_order,is_active) VALUES($1,0,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[String(b.name).trim(),Number(b.maintenanceOrders||0),Number(b.upgradeOrders||0),b.badgeLabel||null,b.badgeType||'emoji',b.badgeImageUrl||null,JSON.stringify(Array.isArray(b.rewards)?b.rewards:[]),JSON.stringify(Array.isArray(b.benefits)?b.benefits:[]),Number(b.sortOrder||0),b.isActive!==false]);res.status(201).json({tier:rows[0]})}catch(e){if(e.code==='23505')return res.status(409).json({error:'اسم الفئة مستخدم بالفعل'});next(e)}});
router.patch('/tiers/:id',requireAuth,requireRole('admin'),async(req,res,next)=>{try{const b=req.body||{};const{rows}=await pool.query(`UPDATE membership_tiers SET name=COALESCE($1,name),maintenance_orders=COALESCE($2,maintenance_orders),upgrade_orders=COALESCE($3,upgrade_orders),badge_label=$4,badge_type=COALESCE($5,badge_type),badge_image_url=$6,rewards=COALESCE($7,rewards),benefits=COALESCE($8,benefits),sort_order=COALESCE($9,sort_order),is_active=COALESCE($10,is_active),updated_at=now() WHERE id=$11 RETURNING *`,[b.name, b.maintenanceOrders===undefined?null:Number(b.maintenanceOrders),b.upgradeOrders===undefined?null:Number(b.upgradeOrders),b.badgeLabel||null,b.badgeType,b.badgeImageUrl||null,b.rewards===undefined?null:JSON.stringify(b.rewards),b.benefits===undefined?null:JSON.stringify(b.benefits),b.sortOrder===undefined?null:Number(b.sortOrder),b.isActive===undefined?null:Boolean(b.isActive),req.params.id]);if(!rows[0])return res.status(404).json({error:'الفئة غير موجودة'});res.json({tier:rows[0]})}catch(e){next(e)}});
router.get('/locations',requireAuth,requireRole('admin'),async(req,res,next)=>{try{const g=await pool.query('SELECT * FROM egypt_governorates ORDER BY sort_order,name');const c=await pool.query('SELECT * FROM egypt_centers ORDER BY governorate_id,sort_order,name');res.json({governorates:g.rows,centers:c.rows})}catch(e){next(e)}});
router.patch('/locations/governorates/:id',requireAuth,requireRole('admin'),async(req,res,next)=>{try{const{rows}=await pool.query('UPDATE egypt_governorates SET name=COALESCE($1,name),is_active=COALESCE($2,is_active),sort_order=COALESCE($3,sort_order) WHERE id=$4 RETURNING *',[req.body?.name||null,req.body?.isActive===undefined?null:Boolean(req.body.isActive),req.body?.sortOrder===undefined?null:Number(req.body.sortOrder),req.params.id]);if(!rows[0])return res.status(404).json({error:'المحافظة غير موجودة'});res.json({governorate:rows[0]})}catch(e){next(e)}});
router.post('/locations/governorates',requireAuth,requireRole('admin'),async(req,res,next)=>{try{const{rows}=await pool.query('INSERT INTO egypt_governorates(name,sort_order) VALUES($1,$2) RETURNING *',[String(req.body?.name||'').trim(),Number(req.body?.sortOrder||0)]);res.status(201).json({governorate:rows[0]})}catch(e){if(e.code==='23505')return res.status(409).json({error:'المحافظة موجودة بالفعل'});next(e)}});
router.post('/locations/centers',requireAuth,requireRole('admin'),async(req,res,next)=>{try{const{rows}=await pool.query('INSERT INTO egypt_centers(governorate_id,name,sort_order) VALUES($1,$2,$3) RETURNING *',[req.body?.governorateId,String(req.body?.name||'').trim(),Number(req.body?.sortOrder||0)]);res.status(201).json({center:rows[0]})}catch(e){next(e)}});
router.patch('/locations/centers/:id',requireAuth,requireRole('admin'),async(req,res,next)=>{try{const{rows}=await pool.query('UPDATE egypt_centers SET name=COALESCE($1,name),is_active=COALESCE($2,is_active),sort_order=COALESCE($3,sort_order) WHERE id=$4 RETURNING *',[req.body?.name||null,req.body?.isActive===undefined?null:Boolean(req.body.isActive),req.body?.sortOrder===undefined?null:Number(req.body.sortOrder),req.params.id]);if(!rows[0])return res.status(404).json({error:'المركز غير موجود'});res.json({center:rows[0]})}catch(e){next(e)}});
module.exports=router;
