const express=require('express');const crypto=require('crypto');const router=express.Router();const{pool}=require('../db');const{requireAuth,requireRole}=require('../auth');const admin=requireRole('admin','staff');
function code(){return crypto.randomBytes(5).toString('hex').toUpperCase()}
async function settings(){const{rows}=await pool.query("SELECT key,value FROM platform_settings WHERE key LIKE 'referral.%' OR key LIKE 'promotion.first_order.%'");return Object.fromEntries(rows.map(x=>[x.key,x.value]))}
router.get('/me',requireAuth,requireRole('customer'),async(req,res,next)=>{try{const s=await settings();let p=(await pool.query('SELECT code FROM referral_profiles WHERE user_id=$1',[req.user.id])).rows[0];if(!p){for(let i=0;i<5&&!p;i++){const c=code();try{p=(await pool.query('INSERT INTO referral_profiles(user_id,code) VALUES($1,$2) RETURNING code',[req.user.id,c])).rows[0]}catch(e){if(e.code!=='23505')throw e}}}const{rows}=await pool.query("SELECT status,count(*)::int count FROM referrals WHERE referrer_id=$1 GROUP BY status",[req.user.id]);const counts=Object.fromEntries(rows.map(x=>[x.status,x.count]));res.json({code:p?.code||null,enabled:s['referral.enabled']==='true',requiredCount:Number(s['referral.required_count']||3),rewardType:s['referral.reward_type']||'free_delivery',rewardValue:Number(s['referral.reward_value']||1),qualified:Number(counts.qualified||0)+Number(counts.rewarded||0),pending:Number(counts.pending||0),rejected:Number(counts.rejected||0)})}catch(e){next(e)}});
router.get('/admin/settings',requireAuth,admin,async(_req,res,next)=>{try{const s=await settings();res.json({settings:s})}catch(e){next(e)}});
router.patch('/admin/settings',requireAuth,admin,async(req,res,next)=>{try{const b=req.body||{},allowed=['promotion.first_order.enabled','promotion.first_order.name','referral.enabled','referral.required_count','referral.reward_type','referral.reward_value','referral.qualification'];for(const k of allowed)if(b[k]!==undefined)await pool.query("INSERT INTO platform_settings(key,value,updated_at) VALUES($1,$2,now()) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=now()",[k,String(b[k])]);res.json({ok:true,settings:await settings()})}catch(e){next(e)}});
router.get('/admin/referrals',requireAuth,admin,async(req,res,next)=>{try{const{rows}=await pool.query(`SELECT r.*,a.full_name referrer_name,a.phone referrer_phone,b.full_name referee_name,b.phone referee_phone FROM referrals r JOIN users a ON a.id=r.referrer_id JOIN users b ON b.id=r.referee_id ORDER BY r.created_at DESC LIMIT 300`);res.json({referrals:rows})}catch(e){next(e)}});
router.post('/admin/promotions',requireAuth,admin,async(req,res,next)=>{try{const b=req.body||{};const{rows}=await pool.query(`INSERT INTO promotion_rules(name,promotion_type,trigger_type,config,is_active,starts_at,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[String(b.name||'').trim(),String(b.promotionType||''),String(b.triggerType||''),JSON.stringify(b.config||{}),b.isActive!==false,b.startsAt||null,b.expiresAt||null]);res.status(201).json({promotion:rows[0]})}catch(e){next(e)}});
router.get('/admin/promotions',requireAuth,admin,async(_req,res,next)=>{try{const{rows}=await pool.query('SELECT * FROM promotion_rules ORDER BY created_at DESC');res.json({promotions:rows})}catch(e){next(e)}});
module.exports=router;