import AsyncStorage from '@react-native-async-storage/async-storage';
import {useEffect,useRef,useState}from'react';
import {ActivityIndicator,Animated,PanResponder,Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import {SafeAreaView}from'react-native-safe-area-context';
import {router,useLocalSearchParams}from'expo-router';
import {theme}from'@/constants/theme';
const API=(process.env.EXPO_PUBLIC_API_URL||'').replace(/\/$/,'');
function Swipe({title,onDone}:{title:string;onDone:()=>void}){const x=useRef(new Animated.Value(0)).current,done=useRef(false);const p=useRef(PanResponder.create({onStartShouldSetPanResponder:()=>true,onMoveShouldSetPanResponder:(_,g)=>Math.abs(g.dx)>5,onPanResponderMove:(_,g)=>x.setValue(Math.max(0,Math.min(245,g.dx))),onPanResponderRelease:(_,g)=>{if(g.dx>150&&!done.current){done.current=true;Animated.timing(x,{toValue:245,duration:140,useNativeDriver:true}).start(onDone)}else Animated.spring(x,{toValue:0,useNativeDriver:true}).start()}})).current;return <View style={s.swipe} {...p.panHandlers}><Text style={s.swipeText}>{title}</Text><Animated.View style={[s.knob,{transform:[{translateX:x}]}]}><Text style={s.knobText}>›</Text></Animated.View></View>}
export default function DriverOrder(){
 const {orderId,assigned}=useLocalSearchParams<{orderId:string;assigned?:string}>();const [o,setO]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{try{const t=await AsyncStorage.getItem('auth_token'),r=await fetch(API+'/api/orders/driver/'+orderId+'/detail',{headers:{Authorization:'Bearer '+t}}),d=await r.json();if(!r.ok)throw Error(d.error||'تعذر تحميل الطلب');setO(d.order);setError('')}catch(e){setError(e instanceof Error?e.message:'تعذر التحميل')}finally{setLoading(false)}};
 useEffect(()=>{load()},[orderId]);
 const call=async(path:string,body?:any)=>{try{setBusy(true);const t=await AsyncStorage.getItem('auth_token'),r=await fetch(API+path,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:'Bearer '+t},body:body?JSON.stringify(body):undefined}),d=await r.json();if(!r.ok)throw Error(d.error||'تعذر تنفيذ العملية');await load()}catch(e){setError(e instanceof Error?e.message:'تعذر تنفيذ العملية')}finally{setBusy(false)}};
 if(loading)return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator color={theme.primary}/></View></SafeAreaView>;
 if(!o)return <SafeAreaView style={s.safe}><View style={s.center}><Text style={s.error}>{error||'الطلب غير متاح'}</Text></View></SafeAreaView>;
 const manual=o.driver_assignment_mode==='manual',pendingManual=manual&&!o.driver_assignment_accepted_at;
 const available=!o.driver_id;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>→</Text></Pressable><View style={{flex:1}}><Text style={s.title}>طلب #{String(o.id).slice(0,8)}</Text><Text style={s.sub}>{pendingManual?'🛡️ هذا الطلب مُسند إليك من الإدارة':o.status==='preparing'?'⏱ جاري التجهيز':o.status==='ready'?'📦 جاهز للاستلام':'متابعة التنفيذ'}</Text></View></View>
 {error?<Text style={s.error}>{error}</Text>:null}
 {pendingManual?<View style={s.badge}><Text style={s.badgeText}>🛡️ طلب مُسند إليك — لا يظهر لباقي المندوبين</Text></View>:null}
 <Card title="ملخص الطلب"><Row l="الجهة" v={o.restaurant_name||'جهة الطلب'}/><Row l="العميل" v={o.customer_name||'—'}/><Row l="التحصيل" v={Number(o.cash_due||0).toFixed(2)+' ج.م'}/><Row l="العمولة" v={Number(o.driver_commission||0).toFixed(2)+' ج.م'}/><Row l="عدد العناصر" v={String((o.items||[]).reduce((n:any,x:any)=>n+Number(x.quantity||0),0))}/></Card>
 <Card title="أماكن التوصيل"><Text style={s.place}>🏪 {o.restaurant_name||'الجهة'}</Text><Text style={s.address}>{o.restaurant_address||'العنوان غير مسجل'}</Text><Text style={s.place}>🏠 العميل</Text><Text style={s.address}>{o.delivery_address||'العنوان غير مسجل'}</Text></Card>
 <Card title="محتويات الطلب">{(o.items||[]).map((x:any)=><View key={x.id} style={s.item}><Text style={s.qty}>×{x.quantity}</Text><Text style={s.itemName}>{x.item_name}</Text></View>)}</Card>
 {o.order_notes?<Card title="ملاحظات"><Text style={s.note}>{o.order_notes}</Text></Card>:null}
 <Card title="مراحل الطلب"><Text style={s.stage}>1. {['preparing','ready','assigned','picked_up','on_the_way'].includes(o.status)?'✓':'○'} تجهيز الطلب</Text><Text style={s.stage}>2. {['assigned','picked_up','on_the_way'].includes(o.status)?'✓':'○'} قبول مهمة التوصيل</Text><Text style={s.stage}>3. {['picked_up','on_the_way'].includes(o.status)?'✓':'○'} استلام الطلب من الجهة</Text><Text style={s.stage}>4. {o.status==='on_the_way'?'✓':'○'} التوجه للعميل</Text></Card>
 {available?<Swipe title="اسحب لقبول الطلب" onDone={()=>call('/api/orders/'+o.id+'/claim')}/>:pendingManual?<Swipe title="اسحب لقبول المهمة المُسندة" onDone={()=>call('/api/orders/'+o.id+'/accept-assignment')}/>:o.status==='assigned'?<Pressable disabled={busy} onPress={()=>call('/api/orders/'+o.id+'/driver-status',{status:'assigned'})} style={s.primary}><Text style={s.primaryText}>📦 تم استلام الطلب من الجهة</Text></Pressable>:o.status==='picked_up'?<Pressable disabled={busy} onPress={()=>call('/api/orders/'+o.id+'/driver-status',{status:'picked_up'})} style={s.primary}><Text style={s.primaryText}>🛵 بدأت التوجه للعميل</Text></Pressable>:o.status==='on_the_way'?<Pressable onPress={()=>router.push({pathname:'/driver/delivery-proof',params:{orderId:o.id}})} style={s.primary}><Text style={s.primaryText}>🔐 تأكيد التسليم بالـ PIN</Text></Pressable>:<View style={s.wait}><Text style={s.waitText}>بعد قبولك، انتظر حتى يصبح الطلب جاهزًا للاستلام.</Text></View>}
 </ScrollView></SafeAreaView>
}
function Card({title,children}:{title:string;children:any}){return <View style={s.card}><Text style={s.cardTitle}>{title}</Text>{children}</View>}
function Row({l,v}:{l:string;v:string}){return <View style={s.row}><Text style={s.value}>{v}</Text><Text style={s.label}>{l}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.background},page:{padding:16,paddingBottom:40},center:{flex:1,alignItems:'center',justifyContent:'center'},head:{flexDirection:'row-reverse',alignItems:'center',gap:10,marginBottom:13},back:{width:42,height:42,borderRadius:13,borderWidth:1,borderColor:theme.border,backgroundColor:theme.surface,alignItems:'center',justifyContent:'center'},backText:{color:theme.text,fontSize:22},title:{color:theme.text,fontSize:23,fontWeight:'900',textAlign:'right'},sub:{color:theme.muted,fontSize:10,textAlign:'right',marginTop:4},badge:{backgroundColor:theme.primarySoft,borderRadius:13,padding:11,marginBottom:9},badgeText:{color:theme.primary,fontWeight:'900',fontSize:10,textAlign:'right'},card:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:18,padding:13,marginBottom:9},cardTitle:{color:theme.text,fontSize:14,fontWeight:'900',textAlign:'right',marginBottom:9},row:{flexDirection:'row-reverse',justifyContent:'space-between',paddingVertical:5,borderBottomWidth:1,borderBottomColor:theme.border},label:{color:theme.muted,fontSize:9},value:{color:theme.text,fontSize:10,fontWeight:'900'},place:{color:theme.text,fontWeight:'900',textAlign:'right',marginTop:5},address:{color:theme.muted,fontSize:10,textAlign:'right',marginTop:3,lineHeight:16},item:{flexDirection:'row-reverse',gap:9,paddingVertical:7,borderBottomWidth:1,borderBottomColor:theme.border},qty:{color:theme.primary,fontWeight:'900'},itemName:{color:theme.text,flex:1,textAlign:'right'},note:{color:theme.muted,textAlign:'right',lineHeight:18},stage:{color:theme.text,textAlign:'right',fontSize:10,paddingVertical:5},swipe:{height:56,borderRadius:17,borderWidth:1,borderColor:theme.primary,backgroundColor:theme.surface,justifyContent:'center',alignItems:'center',overflow:'hidden',marginTop:8},swipeText:{color:theme.text,fontWeight:'900',fontSize:11},knob:{position:'absolute',left:4,width:48,height:48,borderRadius:15,backgroundColor:theme.primary,alignItems:'center',justifyContent:'center'},knobText:{color:'#fff',fontSize:29,fontWeight:'900'},primary:{height:54,borderRadius:16,backgroundColor:theme.primary,alignItems:'center',justifyContent:'center',marginTop:8},primaryText:{color:'#fff',fontWeight:'900'},wait:{backgroundColor:theme.primarySoft,borderRadius:14,padding:12,marginTop:8},waitText:{color:theme.primary,textAlign:'right',fontSize:10,fontWeight:'800'},error:{color:theme.danger,textAlign:'right',marginBottom:8}});