import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Location from "expo-location";
import * as TaskManager from "expo-task-manager";
import { useEffect, useState } from "react";
import { ActivityIndicator, StyleSheet, Text, View } from "react-native";
import { theme } from "@/constants/theme";
const API_URL=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,""); const TASK_NAME="waselni-driver-location";
TaskManager.defineTask(TASK_NAME,async({data,error})=>{if(error||!data)return;const locations=(data as {locations?:Location.LocationObject[]}).locations||[],l=locations[locations.length-1];if(!l)return;const token=await AsyncStorage.getItem("auth_token");if(!token||!API_URL)return;await fetch(API_URL+"/api/location/me",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({latitude:l.coords.latitude,longitude:l.coords.longitude,accuracy:l.coords.accuracy,heading:l.coords.heading,speed:l.coords.speed})})});
export default function DriverTracking(){const [status,setStatus]=useState("جاري تجهيز GPS...");useEffect(()=>{let timer:ReturnType<typeof setInterval>|undefined;(async()=>{const p=await Location.requestForegroundPermissionsAsync();if(p.status!=="granted"){setStatus("تم رفض إذن الموقع");return;}const send=async()=>{const l=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High}),t=await AsyncStorage.getItem("auth_token");if(t&&API_URL)await fetch(API_URL+"/api/location/me",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+t},body:JSON.stringify({latitude:l.coords.latitude,longitude:l.coords.longitude,accuracy:l.coords.accuracy,heading:l.coords.heading,speed:l.coords.speed})})};await send();setStatus("الدليفري متصل — يتم تحديث الموقع");timer=setInterval(send,5000);try{const bg=await Location.requestBackgroundPermissionsAsync();if(bg.status==="granted")await Location.startLocationUpdatesAsync(TASK_NAME,{accuracy:Location.Accuracy.High,timeInterval:5000,distanceInterval:5,showsBackgroundLocationIndicator:true,foregroundService:{notificationTitle:"وصّلني",notificationBody:"تحديث موقع الدليفري أثناء التوصيل"}})}catch{}})();return()=>{if(timer)clearInterval(timer)}},[]);return <View style={styles.page}><View style={styles.dot}/><Text style={styles.title}>تتبع الدليفري</Text><Text style={styles.status}>{status}</Text><Text style={styles.note}>الموقع بيتبعت للخادم تلقائيًا أثناء التوصيل.</Text><ActivityIndicator color={theme.primary} style={{marginTop:20}}/></View>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:theme.background,alignItems:"center",justifyContent:"center",padding:30},dot:{width:22,height:22,borderRadius:11,backgroundColor:"#25A55F"},title:{fontSize:28,fontWeight:"900",color:theme.text,marginTop:18},status:{fontSize:15,fontWeight:"800",color:theme.text,marginTop:9,textAlign:"center"},note:{fontSize:12,color:theme.muted,textAlign:"center",marginTop:8}});