import { Stack } from "expo-router";
import { SafeAreaProvider } from "react-native-safe-area-context";
import { useEffect } from "react";
import { Platform } from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Notifications from "expo-notifications";
import Constants from "expo-constants";
Notifications.setNotificationHandler({ handleNotification: async () => ({ shouldShowBanner:true, shouldShowList:true, shouldPlaySound:true, shouldSetBadge:true }) });
const API=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,"");
export default function RootLayout(){useEffect(()=>{if(Platform.OS==="web"||!API)return;let mounted=true,done=false;const register=async()=>{try{if(done)return;const token=await AsyncStorage.getItem("auth_token");if(!token)return;if(Platform.OS==="android")await Notifications.setNotificationChannelAsync("orders",{name:"الطلبات",importance:Notifications.AndroidImportance.MAX,vibrationPattern:[0,250,250,250]});const current=await Notifications.getPermissionsAsync();let status=current.status;if(status!=="granted"){if(status==="denied")return;const requested=await Notifications.requestPermissionsAsync();status=requested.status}if(!mounted||status!=="granted")return;const projectId=Constants.expoConfig?.extra?.eas?.projectId||Constants.easConfig?.projectId;if(!projectId)return;const push=(await Notifications.getExpoPushTokenAsync({projectId})).data;if(!push)return;const previous=await AsyncStorage.getItem("registered_push_token");if(previous===push){done=true;return}const r=await fetch(API+"/api/notifications/push-token",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({token:push,platform:Platform.OS})});if(r.ok){await AsyncStorage.setItem("registered_push_token",push);done=true}}catch{}};register();const id=setInterval(register,5000);return()=>{mounted=false;clearInterval(id)}},[]);return <SafeAreaProvider><Stack screenOptions={{headerShown:false}} /></SafeAreaProvider>}
