import AsyncStorage from "@react-native-async-storage/async-storage";
import { router } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { theme } from "@/constants/theme";
import { fonts } from "@/constants/fonts";
const API_URL=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,"");
const phoneInput=(value:string)=>value.replace(/\D/g,"").slice(0,11);
function goByRole(role:string){if(role==="admin")router.replace("/admin");else if(role==="driver")router.replace("/driver");else if(role==="restaurant")router.replace("/restaurant");else router.replace("/home")}
export default function Auth(){const [phone,setPhone]=useState(""),[password,setPassword]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState("");const valid=/^01\d{9}$/.test(phone)&&password.length>=8;const go=async()=>{if(!valid||loading)return;if(!API_URL){setError("رابط الخادم غير مضبوط.");return}setLoading(true);setError("");try{const r=await fetch(`${API_URL}/api/auth/login`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({identifier:phone,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر تسجيل الدخول");await AsyncStorage.multiSet([["auth_token",d.token],["auth_user",JSON.stringify(d.user)]]);goByRole(d.user.role)}catch(e){setError(e instanceof Error?e.message:"تعذر الاتصال بالخادم")}finally{setLoading(false)}};return <SafeAreaView style={s.safe}><View style={s.page}><Pressable onPress={()=>router.replace("/")} style={s.back}><Text style={s.backText}>→</Text></Pressable><View style={s.header}><View style={s.logo}><Text style={s.logoText}>و</Text></View><Text style={s.title}>أهلاً بيك</Text><Text style={s.subtitle}>سجّل دخولك برقم الموبايل وكلمة المرور.</Text></View><View style={s.form}><Text style={s.label}>رقم الهاتف</Text><TextInput value={phone} onChangeText={v=>setPhone(phoneInput(v))} placeholder="01XXXXXXXXX" placeholderTextColor="#A0A0A0" keyboardType="phone-pad" textAlign="right" style={s.input} maxLength={11}/><Text style={s.helper}>11 رقم بالضبط • يبدأ بـ 01</Text><Text style={s.label}>كلمة المرور</Text><TextInput value={password} onChangeText={setPassword} placeholder="كلمة المرور" placeholderTextColor="#A0A0A0" secureTextEntry textAlign="right" style={s.input}/>{error?<Text style={s.error}>{error}</Text>:null}<Pressable onPress={()=>router.push("/register")} style={s.reg}><Text style={s.regText}>إنشاء حساب جديد</Text></Pressable><Pressable disabled={!valid||loading} onPress={go} style={[s.button,(!valid||loading)&&s.disabled]}>{loading?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>تسجيل الدخول</Text>}</Pressable></View><Text style={s.footer}>وصّلني • دخول آمن وسريع</Text></View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.background},page:{flex:1,paddingHorizontal:24,paddingTop:8,justifyContent:"space-between"},back:{width:44,height:44,borderRadius:14,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,alignItems:"center",justifyContent:"center",alignSelf:"flex-start"},backText:{fontSize:24,color:theme.text},header:{alignItems:"center"},logo:{width:58,height:58,borderRadius:18,backgroundColor:theme.primary,alignItems:"center",justifyContent:"center",marginBottom:20},logoText:{color:"#fff",fontSize:30,fontWeight:fonts.weight.heavy},title:{color:theme.text,fontSize:31,fontWeight:fonts.weight.heavy,textAlign:"center"},subtitle:{color:theme.muted,fontSize:fonts.size.md,marginTop:9,textAlign:"center"},form:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:20,padding:18},label:{color:theme.text,fontSize:fonts.size.md,fontWeight:fonts.weight.bold,textAlign:"right",marginBottom:9,marginTop:4},input:{minHeight:56,borderWidth:1,borderColor:theme.border,borderRadius:15,paddingHorizontal:16,color:theme.text,fontSize:fonts.size.lg,backgroundColor:theme.background,marginBottom:2},helper:{color:theme.muted,fontSize:fonts.size.xs,lineHeight:19,textAlign:"right",marginBottom:10},error:{color:theme.danger,fontSize:fonts.size.xs,lineHeight:19,textAlign:"right",marginTop:9},button:{minHeight:56,borderRadius:15,backgroundColor:theme.primary,alignItems:"center",justifyContent:"center",marginTop:10},buttonText:{color:"#fff",fontSize:fonts.size.lg,fontWeight:fonts.weight.bold},reg:{minHeight:50,borderRadius:15,borderWidth:1,borderColor:theme.border,alignItems:"center",justifyContent:"center",marginTop:10},regText:{color:theme.text,fontSize:fonts.size.md,fontWeight:fonts.weight.bold},disabled:{opacity:.45},footer:{color:theme.muted,fontSize:fonts.size.xs,textAlign:"center",paddingBottom:14}});