import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Notifications from "expo-notifications";
import { router } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Platform, Pressable, StyleSheet, Text, View } from "react-native";
import * as Location from "expo-location";
import { SafeAreaView } from "react-native-safe-area-context";
import { theme } from "@/constants/theme";
import { fonts } from "@/constants/fonts";
export default function Onboarding(){const [busy,setBusy]=useState(false),[location,setLocation]=useState(false),[notifications,setNotifications]=useState(false);const finish=async()=>{await AsyncStorage.setItem("onboarding_done","1");router.replace("/home")};const enableLocation=async()=>{try{setBusy(true);const p=await Location.requestForegroundPermissionsAsync();setLocation(p.status==="granted")}finally{setBusy(false)}};const enableNotifications=async()=>{try{setBusy(true);if(Platform.OS==="android")await Notifications.setNotificationChannelAsync("default",{name:"وصّلني",importance:Notifications.AndroidImportance.HIGH,sound:"default",vibrationPattern:[0,250,250,250]});const p=await Notifications.requestPermissionsAsync();setNotifications(p.status==="granted")}finally{setBusy(false)}};return <SafeAreaView style={s.safe}><View style={s.page}><View><View style={s.logo}><Text style={s.logoText}>و</Text></View><Text style={s.title}>ظبطنا الأساسيات ✨</Text><Text style={s.sub}>خطوتين اختياريين يخلو تجربة وصّلني أفضل من أول طلب.</Text><View style={s.card}><Text style={s.icon}>📍</Text><View style={s.copy}><Text style={s.cardTitle}>الموقع</Text><Text style={s.cardSub}>للعناوين الدقيقة وحساب رسوم التوصيل.</Text></View><Pressable onPress={enableLocation} disabled={busy} style={[s.action,location&&s.done]}><Text style={s.actionText}>{location?"تم":"تفعيل"}</Text></Pressable></View><View style={s.card}><Text style={s.icon}>🔔</Text><View style={s.copy}><Text style={s.cardTitle}>الإشعارات</Text><Text style={s.cardSub}>تنبيهات حالة الطلب والعروض المهمة.</Text></View><Pressable onPress={enableNotifications} disabled={busy} style={[s.action,notifications&&s.done]}><Text style={s.actionText}>{notifications?"تم":"تفعيل"}</Text></Pressable></View></View><View>{busy&&<ActivityIndicator color={theme.primary} style={{marginBottom:10}}/>}<Pressable onPress={finish} style={s.primary}><Text style={s.primaryText}>ابدأ استخدام وصّلني</Text></Pressable><Pressable onPress={finish} style={s.skip}><Text style={s.skipText}>هعملها بعدين</Text></Pressable></View></View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.background},page:{flex:1,padding:22,justifyContent:"space-between"},logo:{width:64,height:64,borderRadius:20,backgroundColor:theme.primary,alignItems:"center",justifyContent:"center",alignSelf:"center",marginTop:20},logoText:{color:"#fff",fontSize:34,fontWeight:fonts.weight.heavy},title:{color:theme.text,fontSize:29,fontWeight:fonts.weight.heavy,textAlign:"center",marginTop:22},sub:{color:theme.muted,fontSize:14,lineHeight:22,textAlign:"center",marginTop:8,marginBottom:22},card:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:20,padding:15,flexDirection:"row-reverse",alignItems:"center",marginBottom:11},icon:{fontSize:26,marginLeft:11},copy:{flex:1},cardTitle:{color:theme.text,fontSize:15,fontWeight:fonts.weight.bold,textAlign:"right"},cardSub:{color:theme.muted,fontSize:11,lineHeight:17,textAlign:"right",marginTop:3},action:{backgroundColor:theme.primary,borderRadius:11,paddingHorizontal:13,paddingVertical:9},done:{backgroundColor:theme.success},actionText:{color:"#fff",fontSize:11,fontWeight:fonts.weight.bold},primary:{height:56,borderRadius:16,backgroundColor:theme.primary,alignItems:"center",justifyContent:"center"},primaryText:{color:"#fff",fontSize:16,fontWeight:fonts.weight.bold},skip:{height:42,alignItems:"center",justifyContent:"center"},skipText:{color:theme.muted,fontSize:12,fontWeight:fonts.weight.medium}});