import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Location from "expo-location";
import { router } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import MapView, { Marker, Region } from "react-native-maps";
import { SafeAreaView } from "react-native-safe-area-context";
import { theme } from "@/constants/theme";
import { fonts } from "@/constants/fonts";
const API_URL=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,"");
const DEFAULT_REGION:Region={latitude:30.0444,longitude:31.2357,latitudeDelta:.08,longitudeDelta:.08};
const phoneInput=(value:string)=>value.replace(/\D/g,"").slice(0,11);
export default function Register(){
 const [fullName,setFullName]=useState(""),[phone,setPhone]=useState(""),[secondaryPhone,setSecondaryPhone]=useState(""),[email,setEmail]=useState("");
 const [password,setPassword]=useState(""),[confirmPassword,setConfirmPassword]=useState("");
 const [area,setArea]=useState(""),[address,setAddress]=useState(""),[building,setBuilding]=useState(""),[floor,setFloor]=useState(""),[apartment,setApartment]=useState(""),[notes,setNotes]=useState("");
 const [region,setRegion]=useState<Region>(DEFAULT_REGION),[hasLocation,setHasLocation]=useState(false),[loading,setLoading]=useState(false),[locating,setLocating]=useState(false),[error,setError]=useState("");
 const locate=async()=>{try{setLocating(true);setError("");const p=await Location.requestForegroundPermissionsAsync();if(p.status!=="granted"){setError("الموقع اختياري. يمكنك كتابة العنوان يدويًا.");return;}const l=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});setRegion(r=>({...r,latitude:l.coords.latitude,longitude:l.coords.longitude}));setHasLocation(true);}catch{setError("تعذر تحديد موقعك، يمكنك كتابة العنوان يدويًا.");}finally{setLocating(false)}};
 const submit=async()=>{const p=phoneInput(phone),sp=phoneInput(secondaryPhone);if(fullName.trim().length<2)return setError("اكتب الاسم بالكامل.");if(!/^01\d{9}$/.test(p))return setError("رقم الهاتف يجب أن يكون 11 رقمًا ويبدأ بـ 01.");if(sp&&!/^01\d{9}$/.test(sp))return setError("رقم الهاتف الاحتياطي غير صحيح.");if(sp===p)return setError("الرقم الاحتياطي لازم يكون مختلف.");if(password.length<8)return setError("كلمة المرور يجب أن تكون 8 أحرف على الأقل.");if(password!==confirmPassword)return setError("تأكيد كلمة المرور غير مطابق.");if(!address.trim())return setError("اكتب عنوان التوصيل.");try{setLoading(true);setError("");const r=await fetch(API_URL+"/api/auth/register-customer",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fullName,phone:p,secondaryPhone:sp,email,area,address,building,floor,apartment,addressNotes:notes,password,confirmPassword})});const d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر إنشاء الحساب");await AsyncStorage.multiSet([["auth_token",d.token],["auth_user",JSON.stringify(d.user)],["onboarding_done","0"]]);if(hasLocation){await fetch(API_URL+"/api/location/me",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+d.token},body:JSON.stringify({latitude:region.latitude,longitude:region.longitude})});}router.replace("/onboarding");}catch(e){setError(e instanceof Error?e.message:"تعذر إنشاء الحساب");}finally{setLoading(false)}};
 const fields:[string,string,(v:string)=>void,string][]=[["الاسم بالكامل",fullName,setFullName,"اكتب اسمك"],["رقم الهاتف",phone,setPhone,"01XXXXXXXXX"],["رقم احتياطي",secondaryPhone,setSecondaryPhone,"اختياري"],["البريد الإلكتروني",email,setEmail,"اختياري"],["المنطقة",area,setArea,"مثال: بنها"],["العنوان",address,setAddress,"اسم الشارع والعلامة المميزة"],["رقم العمارة",building,setBuilding,"اختياري"],["الدور",floor,setFloor,"اختياري"],["الشقة",apartment,setApartment,"اختياري"],["ملاحظات التوصيل",notes,setNotes,"مثال: الباب بجوار الصيدلية"]];
 return <SafeAreaView style={styles.safe}><ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><Pressable onPress={()=>router.replace("/auth")} style={styles.back}><Text style={styles.backText}>→</Text></Pressable><Text style={styles.title}>إنشاء حساب عميل</Text><Text style={styles.subtitle}>أنشئ كلمة مرور مرة واحدة، وبعدها دخولك يكون سريع وآمن.</Text><View style={styles.passwordCard}><Text style={styles.cardTitle}>تأمين الحساب</Text><Text style={styles.cardSub}>8 أحرف على الأقل</Text><TextInput value={password} onChangeText={setPassword} placeholder="كلمة المرور" placeholderTextColor={theme.muted} style={styles.input} secureTextEntry textAlign="right"/><TextInput value={confirmPassword} onChangeText={setConfirmPassword} placeholder="تأكيد كلمة المرور" placeholderTextColor={theme.muted} style={styles.input} secureTextEntry textAlign="right"/></View>{fields.map((f,i)=><View key={f[0]} style={styles.field}><Text style={styles.label}>{f[0]}</Text><TextInput value={f[1]} onChangeText={i===1||i===2?value=>f[2](phoneInput(value)):f[2]} placeholder={f[3]} placeholderTextColor="#A0A0A0" style={styles.input} textAlign="right" keyboardType={i===1||i===2?"phone-pad":i===3?"email-address":"default"} maxLength={i===1||i===2?11:undefined}/></View>)}<Text style={styles.label}>موقع التوصيل على الخريطة <Text style={styles.optional}>(اختياري)</Text></Text><MapView style={styles.map} region={region} onRegionChangeComplete={(r)=>{setRegion(r);setHasLocation(true)}}><Marker coordinate={{latitude:region.latitude,longitude:region.longitude}}/></MapView><Pressable onPress={locate} style={styles.locationButton}>{locating?<ActivityIndicator color={theme.primary}/>:<Text style={styles.locationText}>📍 استخدم موقعي الحالي</Text>}</Pressable><Text style={styles.hint}>{hasLocation?"تم تحديد موقعك، وسيُستخدم مع العنوان.":"الموقع اختياري ويمكنك استخدام العنوان المكتوب."}</Text>{!!error&&<Text style={styles.error}>{error}</Text>}<Pressable disabled={loading} onPress={submit} style={[styles.submit,loading&&styles.disabled]}>{loading?<ActivityIndicator color="#fff"/>:<Text style={styles.submitText}>إنشاء الحساب</Text>}</Pressable></ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:theme.background},page:{flex:1},content:{padding:20,paddingBottom:44},back:{width:44,height:44,borderRadius:14,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,alignItems:"center",justifyContent:"center",marginBottom:18},backText:{fontSize:24,color:theme.text},title:{fontSize:29,fontWeight:fonts.weight.heavy,color:theme.text,textAlign:"right"},subtitle:{color:theme.muted,textAlign:"right",marginTop:6,marginBottom:18,lineHeight:20},passwordCard:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:18,padding:14,marginBottom:15},cardTitle:{fontSize:15,fontWeight:fonts.weight.bold,color:theme.text,textAlign:"right"},cardSub:{fontSize:11,color:theme.muted,textAlign:"right",marginTop:3,marginBottom:10},field:{marginBottom:10},label:{color:theme.text,fontSize:13,fontWeight:fonts.weight.bold,textAlign:"right",marginBottom:6},optional:{color:theme.muted,fontWeight:fonts.weight.medium},input:{minHeight:50,borderWidth:1,borderColor:theme.border,borderRadius:14,backgroundColor:theme.surface,color:theme.text,paddingHorizontal:14,fontSize:14,marginBottom:8},map:{height:230,borderRadius:18,marginTop:5,marginBottom:10},locationButton:{height:48,borderRadius:13,borderWidth:1,borderColor:theme.border,alignItems:"center",justifyContent:"center",backgroundColor:theme.surface},locationText:{color:theme.text,fontWeight:fonts.weight.bold},hint:{color:theme.muted,textAlign:"right",fontSize:11,marginTop:7,lineHeight:18},error:{color:theme.danger,textAlign:"right",fontSize:12,marginTop:10},submit:{height:55,borderRadius:15,backgroundColor:theme.primary,alignItems:"center",justifyContent:"center",marginTop:14},submitText:{color:"#fff",fontSize:16,fontWeight:fonts.weight.heavy},disabled:{opacity:.5}});