import AsyncStorage from "@react-native-async-storage/async-storage";
import { router } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { theme } from "@/constants/theme";
const API_URL=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,"");
type CartItem={id:string;name:string;description?:string|null;price:number;quantity:number};
type Cart={restaurantId:string;restaurantName:string;items:CartItem[]};
const KEY="customer_cart";
export default function Cart(){
 const [cart,setCart]=useState<Cart|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[address,setAddress]=useState(""),[notes,setNotes]=useState(""),[error,setError]=useState("");
 useEffect(()=>{(async()=>{try{const raw=await AsyncStorage.getItem(KEY);if(raw)setCart(JSON.parse(raw));}catch{}finally{setLoading(false)}})()},[]);
 const subtotal=useMemo(()=>cart?.items.reduce((s,i)=>s+i.price*i.quantity,0)||0,[cart]);
 const update=async(items:CartItem[])=>{if(!cart)return;const next={...cart,items};setCart(next);if(items.length)await AsyncStorage.setItem(KEY,JSON.stringify(next));else await AsyncStorage.removeItem(KEY)};
 const change=async(id:string,delta:number)=>{if(!cart)return;const items=cart.items.map(i=>i.id===id?{...i,quantity:i.quantity+delta}:i).filter(i=>i.quantity>0);await update(items)};
 const checkout=async()=>{try{setError("");if(!cart?.items.length)return;if(!address.trim())return setError("اكتب عنوان التوصيل أولًا");setBusy(true);const token=await AsyncStorage.getItem("auth_token");if(!token)return router.replace("/auth");const r=await fetch(API_URL+"/api/orders",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({restaurantId:cart.restaurantId,deliveryAddress:address.trim(),subtotal,totalAmount:subtotal,paymentMethod:"cash",orderNotes:notes.trim()||null,items:cart.items.map(i=>({menuItemId:i.id,quantity:i.quantity}))})});const d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر إنشاء الطلب");await AsyncStorage.removeItem(KEY);router.replace({pathname:"/customer/tracking",params:{orderId:d.order?.id||""}})}catch(e){setError(e instanceof Error?e.message:"تعذر إنشاء الطلب")}finally{setBusy(false)}};
 if(loading)return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator color={theme.primary}/></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>→</Text></Pressable><View style={{flex:1}}><Text style={s.title}>السلة</Text><Text style={s.sub}>{cart?.restaurantName||"مفيش منتجات"}</Text></View></View>{!cart?.items.length?<View style={s.empty}><Text style={s.emptyIcon}>🛒</Text><Text style={s.emptyTitle}>السلة فاضية</Text><Text style={s.muted}>اختار منتجات من أي مطعم وارجع هنا.</Text><Pressable onPress={()=>router.push("/customer/restaurants")} style={s.primary}><Text style={s.primaryText}>اختيار مطعم</Text></Pressable></View>:<><Text style={s.section}>المنتجات</Text>{cart.items.map(i=><View key={i.id} style={s.item}><View style={s.qty}><Pressable onPress={()=>change(i.id,1)} style={s.qbtn}><Text style={s.qtext}>+</Text></Pressable><Text style={s.qnum}>{i.quantity}</Text><Pressable onPress={()=>change(i.id,-1)} style={s.qbtn}><Text style={s.qtext}>−</Text></Pressable></View><View style={s.info}><Text style={s.name}>{i.name}</Text><Text style={s.price}>{(i.price*i.quantity).toFixed(2)} ج.م</Text></View></View>)}<Text style={s.section}>بيانات التوصيل</Text><TextInput value={address} onChangeText={setAddress} placeholder="العنوان بالتفصيل" placeholderTextColor={theme.muted} style={s.input} textAlign="right"/><TextInput value={notes} onChangeText={setNotes} placeholder="ملاحظات للطلب (اختياري)" placeholderTextColor={theme.muted} style={[s.input,s.notes]} textAlign="right" multiline/><View style={s.summary}><View style={s.row}><Text style={s.value}>{subtotal.toFixed(2)} ج.م</Text><Text style={s.label}>قيمة المنتجات</Text></View><View style={s.row}><Text style={s.value}>سيتم الحساب</Text><Text style={s.label}>رسوم التوصيل</Text></View><View style={s.total}><Text style={s.totalValue}>{subtotal.toFixed(2)} ج.م</Text><Text style={s.totalLabel}>الإجمالي المبدئي</Text></View></View>{error?<Text style={s.error}>{error}</Text>:null}<Pressable disabled={busy} onPress={checkout} style={[s.primary,busy&&{opacity:.6}]}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>تأكيد الطلب — كاش</Text>}</Pressable></>}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.background},content:{padding:18,paddingBottom:40},head:{flexDirection:"row-reverse",alignItems:"center",gap:12,marginBottom:22},back:{width:44,height:44,borderRadius:14,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,alignItems:"center",justifyContent:"center"},backText:{fontSize:24,color:theme.text},title:{fontSize:29,fontWeight:"900",color:theme.text,textAlign:"right"},sub:{fontSize:12,color:theme.muted,textAlign:"right",marginTop:4},section:{color:theme.text,fontSize:18,fontWeight:"900",textAlign:"right",marginTop:10,marginBottom:10},item:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:17,padding:13,flexDirection:"row-reverse",alignItems:"center",marginBottom:9},info:{flex:1},name:{color:theme.text,fontSize:15,fontWeight:"900",textAlign:"right"},price:{color:theme.primary,fontSize:12,fontWeight:"900",textAlign:"right",marginTop:5},qty:{flexDirection:"row",alignItems:"center",gap:8},qbtn:{width:32,height:32,borderRadius:10,backgroundColor:theme.background,alignItems:"center",justifyContent:"center"},qtext:{color:theme.text,fontSize:20,fontWeight:"900"},qnum:{color:theme.text,fontWeight:"900",minWidth:16,textAlign:"center"},input:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:14,minHeight:50,paddingHorizontal:14,color:theme.text,marginBottom:9},notes:{minHeight:80,paddingTop:13},summary:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:17,padding:14,marginTop:8},row:{flexDirection:"row-reverse",justifyContent:"space-between",paddingVertical:5},label:{color:theme.muted,fontSize:12},value:{color:theme.text,fontSize:12,fontWeight:"800"},total:{borderTopWidth:1,borderTopColor:theme.border,marginTop:7,paddingTop:10,flexDirection:"row-reverse",justifyContent:"space-between"},totalLabel:{color:theme.text,fontSize:14,fontWeight:"900"},totalValue:{color:theme.primary,fontSize:16,fontWeight:"900"},primary:{height:52,borderRadius:15,backgroundColor:theme.primary,alignItems:"center",justifyContent:"center",marginTop:12},primaryText:{color:"#fff",fontWeight:"900"},error:{color:theme.danger,textAlign:"right",fontWeight:"800",marginTop:10},empty:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:20,padding:35,alignItems:"center",marginTop:30},emptyIcon:{fontSize:48},emptyTitle:{color:theme.text,fontSize:20,fontWeight:"900",marginTop:8},muted:{color:theme.muted,fontSize:12,marginTop:5,textAlign:"center"},center:{flex:1,alignItems:"center",justifyContent:"center"}});