import AsyncStorage from "@react-native-async-storage/async-storage";
import { router } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { theme } from "@/constants/theme";
const API_URL=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,"");const KEY="customer_cart";const LOCATION_KEY="customer_delivery_location";
type CartItem={id:string;name:string;description?:string|null;price:number;quantity:number;restaurantId:string;restaurantName:string};type Cart={items:CartItem[]};type Quote={restaurants:number;subtotal:number;deliveryFees:number;total:number;deliveryDistanceMeters:number|null;pricing?:{baseFee:number;distanceFee:number;merchantFee:number;includedKm:number;extraKmFee:number;extraMerchantFee:number;extraKm:number};zone?:{id:string;name:string}|null};
export default function Cart(){
 const [cart,setCart]=useState<Cart>({items:[]});const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[address,setAddress]=useState(""),[notes,setNotes]=useState(""),[error,setError]=useState(""),[quote,setQuote]=useState<Quote|null>(null),[quoteLoading,setQuoteLoading]=useState(false);
 useEffect(()=>{(async()=>{try{const raw=await AsyncStorage.getItem(KEY);if(raw){const c=JSON.parse(raw);setCart({items:Array.isArray(c.items)?c.items:[]})}}catch{}finally{setLoading(false)}})()},[]);
 const groups=useMemo(()=>{const map=new Map<string,{restaurantId:string;restaurantName:string;items:CartItem[]}>();for(const item of cart.items){const key=item.restaurantId;if(!map.has(key))map.set(key,{restaurantId:key,restaurantName:item.restaurantName,items:[]});map.get(key)!.items.push(item)}return Array.from(map.values())},[cart]);
 const productsTotal=useMemo(()=>cart.items.reduce((s,i)=>s+i.price*i.quantity,0),[cart]);
 const update=async(items:CartItem[])=>{const next={items};setCart(next);if(items.length)await AsyncStorage.setItem(KEY,JSON.stringify(next));else await AsyncStorage.removeItem(KEY)};
 const change=async(id:string,restaurantId:string,delta:number)=>{const items=cart.items.map(i=>i.id===id&&i.restaurantId===restaurantId?{...i,quantity:i.quantity+delta}:i).filter(i=>i.quantity>0);await update(items)};
 const getLocation=async()=>{try{const raw=await AsyncStorage.getItem(LOCATION_KEY);if(!raw)return null;const p=JSON.parse(raw);if(Number.isFinite(Number(p.latitude))&&Number.isFinite(Number(p.longitude)))return {latitude:Number(p.latitude),longitude:Number(p.longitude)}}catch{}return null};
 const loadQuote=async()=>{if(!cart.items.length)return;try{setQuoteLoading(true);setError("");const t=await AsyncStorage.getItem("auth_token");const loc=await getLocation();if(!loc){setQuote(null);return}const orders=groups.map(g=>({restaurantId:g.restaurantId,items:g.items.map(i=>({menuItemId:i.id,quantity:i.quantity}))}));const r=await fetch(API_URL+"/api/orders/quote",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({orders,deliveryLatitude:loc.latitude,deliveryLongitude:loc.longitude,deliveryAddress:address.trim()||null})});const d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر حساب رسوم التوصيل");setQuote(d.summary)}catch(e){setQuote(null);setError(e instanceof Error?e.message:"تعذر حساب رسوم التوصيل")}finally{setQuoteLoading(false)}};
 useEffect(()=>{const timer=setTimeout(()=>{loadQuote()},350);return()=>clearTimeout(timer)},[cart.items.length,groups.length,address]);
 const checkout=async()=>{try{setError("");if(!cart.items.length)return;if(!address.trim())return setError("اكتب عنوان التوصيل أولًا");const loc=await getLocation();if(!loc)return setError("حدد موقع التوصيل من صفحة الموقع أولًا");setBusy(true);const token=await AsyncStorage.getItem("auth_token");if(!token)return router.replace("/auth");const orders=groups.map(g=>({restaurantId:g.restaurantId,items:g.items.map(i=>({menuItemId:i.id,quantity:i.quantity}))}));const r=await fetch(API_URL+"/api/orders/bulk",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({orders,deliveryAddress:address.trim(),deliveryLatitude:loc.latitude,deliveryLongitude:loc.longitude,paymentMethod:"cash",orderNotes:notes.trim()||null})});const d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر إنشاء الطلبات");await AsyncStorage.removeItem(KEY);router.replace({pathname:"/customer/tracking",params:{orderId:d.orders?.[0]?.id||"",checkoutId:d.checkout?.id||""}})}catch(e){setError(e instanceof Error?e.message:"تعذر إنشاء الطلبات")}finally{setBusy(false)}};
 if(loading)return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator color={theme.primary}/></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>→</Text></Pressable><View style={{flex:1}}><Text style={s.title}>السلة</Text><Text style={s.sub}>{groups.length?`${groups.length} جهة في السلة`:"مفيش منتجات"}</Text></View></View>
 {!cart.items.length?<View style={s.empty}><Text style={s.emptyIcon}>🛒</Text><Text style={s.emptyTitle}>السلة فاضية</Text><Text style={s.muted}>اختار منتجات من أي جهة وارجع هنا.</Text><Pressable onPress={()=>router.push("/customer/restaurants")} style={s.primary}><Text style={s.primaryText}>اختيار جهة</Text></Pressable></View>:<>
 <Text style={s.section}>المنتجات</Text>{groups.map(g=><View key={g.restaurantId} style={s.group}><View style={s.groupHead}><Text style={s.groupCount}>{g.items.reduce((n,i)=>n+i.quantity,0)} منتج</Text><Text style={s.groupName}>{g.restaurantName}</Text></View>{g.items.map(i=><View key={`${g.restaurantId}-${i.id}`} style={s.item}><View style={s.qty}><Pressable onPress={()=>change(i.id,g.restaurantId,1)} style={s.qbtn}><Text style={s.qtext}>+</Text></Pressable><Text style={s.qnum}>{i.quantity}</Text><Pressable onPress={()=>change(i.id,g.restaurantId,-1)} style={s.qbtn}><Text style={s.qtext}>−</Text></Pressable></View><View style={s.info}><Text style={s.name}>{i.name}</Text><Text style={s.price}>{(i.price*i.quantity).toFixed(2)} ج.م</Text></View></View>)}</View>)}
 <Text style={s.section}>بيانات التوصيل</Text><TextInput value={address} onChangeText={setAddress} placeholder="العنوان بالتفصيل" placeholderTextColor={theme.muted} style={s.input} textAlign="right"/><TextInput value={notes} onChangeText={setNotes} placeholder="ملاحظات للطلب (اختياري)" placeholderTextColor={theme.muted} style={[s.input,s.notes]} textAlign="right" multiline/>
 <View style={s.summary}><View style={s.row}><Text style={s.value}>{productsTotal.toFixed(2)} ج.م</Text><Text style={s.label}>قيمة المنتجات</Text></View><View style={s.row}><Text style={s.value}>{quoteLoading?"...":quote?`${quote.deliveryFees.toFixed(2)} ج.م`:"حدد الموقع"}</Text><Text style={s.label}>رسوم التوصيل</Text></View>{quote&&<><View style={s.row}><Text style={s.value}>{quote.pricing?.baseFee?.toFixed(2)} ج.م</Text><Text style={s.label}>السعر الأساسي</Text></View><View style={s.row}><Text style={s.value}>{quote.pricing?.distanceFee?.toFixed(2)} ج.م</Text><Text style={s.label}>رسوم المسافة</Text></View><View style={s.row}><Text style={s.value}>{quote.pricing?.merchantFee?.toFixed(2)} ج.م</Text><Text style={s.label}>رسوم الجهات الإضافية</Text></View></>}<View style={s.row}><Text style={s.value}>{groups.length}</Text><Text style={s.label}>عدد الجهات</Text></View><View style={s.total}><Text style={s.totalValue}>{quote?`${quote.total.toFixed(2)} ج.م`: `${productsTotal.toFixed(2)} ج.م + التوصيل`}</Text><Text style={s.totalLabel}>الإجمالي النهائي</Text></View></View>
 {!!error&&<Text style={s.error}>{error}</Text>}<Pressable disabled={busy||quoteLoading} onPress={checkout} style={[s.primary,busy&&{opacity:.6}]}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>تأكيد الطلب — كاش</Text>}</Pressable>
 </>}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.background},content:{padding:18,paddingBottom:40},head:{flexDirection:"row-reverse",alignItems:"center",gap:12,marginBottom:22},back:{width:44,height:44,borderRadius:14,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,alignItems:"center",justifyContent:"center"},backText:{fontSize:24,color:theme.text},title:{fontSize:29,fontWeight:"900",color:theme.text,textAlign:"right"},sub:{fontSize:12,color:theme.muted,textAlign:"right",marginTop:4},section:{color:theme.text,fontSize:18,fontWeight:"900",textAlign:"right",marginTop:10,marginBottom:10},group:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:18,padding:12,marginBottom:10},groupHead:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center",paddingBottom:9,borderBottomWidth:1,borderBottomColor:theme.border,marginBottom:8},groupName:{color:theme.text,fontSize:15,fontWeight:"900"},groupCount:{color:theme.muted,fontSize:11},item:{paddingVertical:7,flexDirection:"row-reverse",alignItems:"center"},info:{flex:1},name:{color:theme.text,fontSize:14,fontWeight:"900",textAlign:"right"},price:{color:theme.primary,fontSize:12,fontWeight:"900",textAlign:"right",marginTop:4},qty:{flexDirection:"row",alignItems:"center",gap:8},qbtn:{width:32,height:32,borderRadius:10,backgroundColor:theme.background,alignItems:"center",justifyContent:"center"},qtext:{color:theme.text,fontSize:20,fontWeight:"900"},qnum:{color:theme.text,fontWeight:"900",minWidth:16,textAlign:"center"},input:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:14,minHeight:50,paddingHorizontal:14,color:theme.text,marginBottom:9},notes:{minHeight:80,paddingTop:13},summary:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:17,padding:14,marginTop:8},row:{flexDirection:"row-reverse",justifyContent:"space-between",paddingVertical:5},label:{color:theme.muted,fontSize:12},value:{color:theme.text,fontSize:12,fontWeight:"800"},total:{borderTopWidth:1,borderTopColor:theme.border,marginTop:7,paddingTop:10,flexDirection:"row-reverse",justifyContent:"space-between"},totalLabel:{color:theme.text,fontSize:14,fontWeight:"900"},totalValue:{color:theme.primary,fontSize:14,fontWeight:"900"},primary:{height:52,borderRadius:15,backgroundColor:theme.primary,alignItems:"center",justifyContent:"center",marginTop:12},primaryText:{color:"#fff",fontWeight:"900"},error:{color:theme.danger,textAlign:"right",fontWeight:"800",marginTop:10},empty:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:20,padding:35,alignItems:"center",marginTop:30},emptyIcon:{fontSize:48},emptyTitle:{color:theme.text,fontSize:20,fontWeight:"900",marginTop:8},muted:{color:theme.muted,fontSize:12,marginTop:5,textAlign:"center"},center:{flex:1,alignItems:"center",justifyContent:"center"}});
