import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Location from "expo-location";
import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";
import MapView,{Marker,Region} from "react-native-maps";
import { SafeAreaView } from "react-native-safe-area-context";
import { theme } from "@/constants/theme";
const API_URL=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,"");
export default function CustomerLocation(){const [region,setRegion]=useState<Region>({latitude:30.0444,longitude:31.2357,latitudeDelta:.08,longitudeDelta:.08}),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");const locate=async()=>{const p=await Location.requestForegroundPermissionsAsync();if(p.status!=="granted"){setMsg("اسمح بالموقع أولًا.");return}const l=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});setRegion(r=>({...r,latitude:l.coords.latitude,longitude:l.coords.longitude}))};useEffect(()=>{locate()},[]);const save=async()=>{try{setBusy(true);const t=await AsyncStorage.getItem("auth_token"),r=await fetch(API_URL+"/api/location/me",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+t},body:JSON.stringify({latitude:region.latitude,longitude:region.longitude})});setMsg(r.ok?"تم حفظ موقع التوصيل.":"تعذر حفظ الموقع.")}finally{setBusy(false)}};return <SafeAreaView style={styles.safe}><View style={styles.page}><Text style={styles.title}>موقع التوصيل</Text><Text style={styles.subtitle}>حرّك العلامة أو استخدم GPS.</Text><MapView style={styles.map} region={region} onRegionChangeComplete={setRegion}><Marker coordinate={{latitude:region.latitude,longitude:region.longitude}}/></MapView><Pressable onPress={locate} style={styles.button}><Text style={styles.buttonText}>📍 تحديد موقعي الحالي</Text></Pressable><Pressable onPress={save} style={[styles.button,styles.primary]}>{busy?<ActivityIndicator color="#fff"/>:<Text style={styles.primaryText}>حفظ الموقع</Text>}</Pressable>{!!msg&&<Text style={styles.msg}>{msg}</Text>}</View></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:theme.background},page:{padding:20,flex:1},title:{fontSize:29,fontWeight:"900",color:theme.text,textAlign:"right"},subtitle:{fontSize:12,color:theme.muted,textAlign:"right",marginTop:5,marginBottom:14},map:{flex:1,minHeight:430,borderRadius:20},button:{height:52,borderRadius:14,borderWidth:1,borderColor:theme.border,backgroundColor:theme.surface,alignItems:"center",justifyContent:"center",marginTop:10},buttonText:{color:theme.text,fontWeight:"900"},primary:{backgroundColor:theme.primary,borderColor:theme.primary},primaryText:{color:"#fff",fontWeight:"900"},msg:{color:theme.text,textAlign:"right",fontSize:12,marginTop:8}});