import AsyncStorage from '@react-native-async-storage/async-storage';
import {useEffect,useState}from'react';
import {ActivityIndicator,Image,Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import {SafeAreaView}from'react-native-safe-area-context';
import {router,useLocalSearchParams}from'expo-router';
import {theme}from'@/constants/theme';
const API=(process.env.EXPO_PUBLIC_API_URL||'').replace(/\/$/,'');
export default function Marketplace(){
 const {id}=useLocalSearchParams<{id:string}>();const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const t=await AsyncStorage.getItem('auth_token'),r=await fetch(API+'/api/marketplaces/'+id,{headers:{Authorization:'Bearer '+t}}),d=await r.json();if(!r.ok)throw Error(d.error||'تعذر تحميل القسم');setData(d)}catch(e){setError(e instanceof Error?e.message:'تعذر التحميل')}finally{setLoading(false)}})()},[id]);
 if(loading)return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator color={theme.primary}/></View></SafeAreaView>;
 if(error)return <SafeAreaView style={s.safe}><View style={s.center}><Text style={s.error}>{error}</Text></View></SafeAreaView>;
 const m=data.marketplace,cats=data.categories||[],merchants=data.merchants||[],layout=m.display_layout||'grid';
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>→</Text></Pressable><View style={{flex:1}}><Text style={s.title}>{m.icon||'🛍️'} {m.name}</Text><Text style={s.sub}>{m.description||'تصفح الأقسام والمنتجات المتاحة'}</Text></View></View>
 {m.show_categories&&cats.length?<><Text style={s.section}>تسوق حسب الأقسام</Text>{layout==='horizontal'?<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.horizontal}>{cats.map((c:any)=><Category key={c.id} c={c} horizontal/>)}</ScrollView>:layout==='single'?cats.map((c:any)=><Category key={c.id} c={c}/>):<View style={s.grid}>{cats.map((c:any)=><Category key={c.id} c={c} grid/>)}</View>}</>:null}
 <Text style={s.section}>الجهات المتاحة</Text>{merchants.length?merchants.map((x:any)=><Pressable key={x.id} onPress={()=>router.push({pathname:'/customer/menu',params:{restaurantId:x.id}})} style={s.merchant}>{x.logo_url?<Image source={{uri:x.logo_url}} style={s.logo}/>:<View style={s.logo}><Text>{m.icon||'🏪'}</Text></View>}<View style={{flex:1}}><Text style={s.name}>{x.name}</Text><Text style={s.meta}>{x.is_open===false?'مغلق حاليًا':'متاح للطلبات'} • تجهيز {x.preparation_minutes||30} د</Text></View></Pressable>):<Text style={s.empty}>لا توجد جهات نشطة في هذا القسم حاليًا.</Text>}</ScrollView></SafeAreaView>
}
function Category({c,horizontal,grid}:{c:any;horizontal?:boolean;grid?:boolean}){return <View style={[s.category,horizontal&&s.categoryHorizontal,grid&&s.categoryGrid]}>{c.image_url?<Image source={{uri:c.image_url}} style={s.catImage}/>:<View style={s.catImage}><Text style={{fontSize:25}}>{c.icon||'📂'}</Text></View>}<Text style={s.catName}>{c.name}</Text>{(c.subcategories||[]).slice(0,4).map((x:any)=><Text key={x.id} style={s.subcat}>• {x.name}</Text>)}</View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.background},page:{padding:16,paddingBottom:40},center:{flex:1,alignItems:'center',justifyContent:'center'},head:{flexDirection:'row-reverse',gap:10,alignItems:'center',marginBottom:13},back:{width:42,height:42,borderRadius:13,borderWidth:1,borderColor:theme.border,backgroundColor:theme.surface,alignItems:'center',justifyContent:'center'},backText:{color:theme.text,fontSize:22},title:{color:theme.text,fontSize:25,fontWeight:'900',textAlign:'right'},sub:{color:theme.muted,fontSize:10,textAlign:'right',marginTop:4},section:{color:theme.text,fontSize:18,fontWeight:'900',textAlign:'right',marginTop:14,marginBottom:9},grid:{flexDirection:'row-reverse',flexWrap:'wrap',gap:8},horizontal:{flexDirection:'row-reverse',gap:8},category:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:16,padding:10,marginBottom:8},categoryGrid:{width:'48%'},categoryHorizontal:{width:145},catImage:{width:'100%',height:72,borderRadius:11,backgroundColor:theme.background,alignItems:'center',justifyContent:'center'},catName:{color:theme.text,fontWeight:'900',textAlign:'right',marginTop:8},subcat:{color:theme.muted,fontSize:8,textAlign:'right',marginTop:3},merchant:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:17,padding:11,flexDirection:'row-reverse',alignItems:'center',gap:10,marginBottom:8},logo:{width:54,height:54,borderRadius:16,backgroundColor:theme.background,alignItems:'center',justifyContent:'center'},name:{color:theme.text,fontWeight:'900',textAlign:'right'},meta:{color:theme.muted,fontSize:9,textAlign:'right',marginTop:4},empty:{color:theme.muted,textAlign:'center',paddingVertical:30},error:{color:theme.danger,textAlign:'center'}});