import AsyncStorage from "@react-native-async-storage/async-storage";
import { router } from "expo-router";
import { useEffect,useState } from "react";
import { ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { theme } from "@/constants/theme";
import { fonts } from "@/constants/fonts";
import { BottomNav } from "@/components/BottomNav";
const API=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,"");
export default function CustomerProfile(){const [p,setP]=useState<any>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[savedCount,setSavedCount]=useState(0),[oldPass,setOldPass]=useState(""),[newPass,setNewPass]=useState(""),[confirm,setConfirm]=useState(""),[showPassword,setShowPassword]=useState(false);
 const token=async()=>await AsyncStorage.getItem("auth_token");
 const load=async()=>{try{const t=await token();const r=await fetch(API+"/api/customer/profile",{headers:{Authorization:`Bearer ${t}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر تحميل الملف");setP(d.profile||{});setSavedCount(Number(d.profile?.saved_locations_count||0))}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل الملف")}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const save=async()=>{try{setBusy(true);setError("");const r=await fetch(API+"/api/customer/profile",{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${await token()}`},body:JSON.stringify({fullName:p.full_name,secondaryPhone:p.secondary_phone,email:p.email,area:p.area,address:p.address,building:p.building,floor:p.floor,apartment:p.apartment,addressNotes:p.address_notes})});const d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر حفظ التعديلات");setP((x:any)=>({...x,...d.profile}));const old=await AsyncStorage.getItem("auth_user"),oldUser=old?JSON.parse(old):{};await AsyncStorage.setItem("auth_user",JSON.stringify({...oldUser,...d.profile}))}catch(e){setError(e instanceof Error?e.message:"تعذر حفظ التعديلات")}finally{setBusy(false)}};
 const changePassword=async()=>{if(newPass.length<8)return setError("كلمة المرور الجديدة يجب أن تكون 8 أحرف على الأقل");if(newPass!==confirm)return setError("تأكيد كلمة المرور غير مطابق");try{setBusy(true);setError("");const r=await fetch(API+"/api/auth/password",{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${await token()}`},body:JSON.stringify({currentPassword:oldPass,password:newPass,confirmPassword:confirm})});const d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر تغيير كلمة المرور");setOldPass("");setNewPass("");setConfirm("");setShowPassword(false);Alert.alert("تم","تم تغيير كلمة المرور بنجاح.")}catch(e){setError(e instanceof Error?e.message:"تعذر تغيير كلمة المرور")}finally{setBusy(false)}};
 const logout=()=>Alert.alert("تسجيل الخروج","هل أنت متأكد أنك تريد تسجيل الخروج؟",[{text:"إلغاء",style:"cancel"},{text:"تسجيل الخروج",style:"destructive",onPress:async()=>{await AsyncStorage.multiRemove(["auth_token","auth_user","registered_push_token","onboarding_done"]);router.replace("/")}}]);
 const field=(key:string,placeholder:string)=><TextInput value={p[key]||""} onChangeText={v=>setP((x:any)=>({...x,[key]:v}))} placeholder={placeholder} placeholderTextColor={theme.muted} style={s.input} textAlign="right"/>;
 if(loading)return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator color={theme.primary}/></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} showsVerticalScrollIndicator={false}><View style={s.head}><Pressable onPress={()=>router.replace("/home")} style={s.back}><Text style={s.backText}>→</Text></Pressable><View style={{flex:1}}><Text style={s.title}>إعدادات الحساب</Text><Text style={s.sub}>بياناتك، الأمان، ومواقع التوصيل</Text></View></View><View style={s.identity}><View style={s.avatar}><Text style={s.avatarText}>{String(p.full_name||"م").slice(0,1)}</Text></View><View style={{flex:1}}><Text style={s.name}>{p.full_name}</Text><Text style={s.phone}>{p.phone}</Text><Text style={s.accountState}>الحساب نشط ✓</Text></View></View><Text style={s.section}>البيانات الشخصية</Text><View style={s.card}>{field("full_name","الاسم بالكامل")}{field("secondary_phone","رقم احتياطي (اختياري)")}{field("email","البريد الإلكتروني (اختياري)")}<Pressable disabled={busy} onPress={save} style={s.primary}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>حفظ التعديلات</Text>}</Pressable></View><Text style={s.section}>العنوان الافتراضي</Text><View style={s.card}>{field("area","المنطقة")}{field("address","العنوان")}{field("building","رقم المبنى")}{field("floor","الدور")}{field("apartment","الشقة")}{field("address_notes","ملاحظات العنوان")}<View style={s.locationRow}><View><Text style={s.locationTitle}>مواقع التوصيل</Text><Text style={s.locationSub}>{savedCount}/10 مواقع محفوظة</Text></View><Pressable onPress={()=>router.push("/customer/location")} style={s.outline}><Text style={s.outlineText}>إدارة المواقع</Text></Pressable></View></View><Text style={s.section}>الأمان</Text><View style={s.card}><Pressable onPress={()=>setShowPassword(x=>!x)} style={s.settingRow}><View><Text style={s.settingTitle}>كلمة المرور</Text><Text style={s.settingSub}>غيّر كلمة المرور في أي وقت</Text></View><Text style={s.chevron}>{showPassword?"⌃":"⌄"}</Text></Pressable>{showPassword&&<View style={{marginTop:12}}><TextInput value={oldPass} onChangeText={setOldPass} secureTextEntry placeholder="كلمة المرور الحالية" placeholderTextColor={theme.muted} style={s.input} textAlign="right"/><TextInput value={newPass} onChangeText={setNewPass} secureTextEntry placeholder="كلمة المرور الجديدة" placeholderTextColor={theme.muted} style={s.input} textAlign="right"/><TextInput value={confirm} onChangeText={setConfirm} secureTextEntry placeholder="تأكيد كلمة المرور" placeholderTextColor={theme.muted} style={s.input} textAlign="right"/><Pressable disabled={busy} onPress={changePassword} style={s.primary}><Text style={s.primaryText}>تحديث كلمة المرور</Text></Pressable></View>}</View>{!!error&&<Text style={s.error}>{error}</Text>}<Text style={s.section}>الحساب</Text><View style={s.card}><Pressable onPress={logout} style={s.logout}><Text style={s.logoutText}>تسجيل الخروج</Text></Pressable></View></ScrollView><BottomNav role="customer"/></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.background},page:{padding:16,paddingBottom:112},head:{flexDirection:"row-reverse",alignItems:"center",gap:11,marginBottom:18},back:{width:44,height:44,borderRadius:14,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,alignItems:"center",justifyContent:"center"},backText:{fontSize:23,color:theme.text},title:{fontSize:27,fontWeight:fonts.weight.heavy,color:theme.text,textAlign:"right"},sub:{fontSize:12,color:theme.muted,textAlign:"right",marginTop:3},identity:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:24,padding:16,flexDirection:"row-reverse",alignItems:"center",gap:13},avatar:{width:64,height:64,borderRadius:22,backgroundColor:theme.primary,alignItems:"center",justifyContent:"center"},avatarText:{fontSize:28,fontWeight:fonts.weight.heavy,color:"#fff"},name:{fontSize:18,fontWeight:fonts.weight.bold,color:theme.text,textAlign:"right"},phone:{fontSize:12,color:theme.muted,textAlign:"right",marginTop:3},accountState:{fontSize:11,color:theme.success,textAlign:"right",marginTop:6,fontWeight:fonts.weight.bold},section:{fontSize:17,fontWeight:fonts.weight.heavy,color:theme.text,textAlign:"right",marginTop:22,marginBottom:9},card:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:22,padding:14},input:{height:49,backgroundColor:theme.background,borderWidth:1,borderColor:theme.border,borderRadius:13,color:theme.text,paddingHorizontal:13,marginBottom:8,fontSize:14},primary:{height:50,borderRadius:14,backgroundColor:theme.primary,alignItems:"center",justifyContent:"center",marginTop:3},primaryText:{color:"#fff",fontWeight:fonts.weight.bold},locationRow:{marginTop:7,paddingTop:13,borderTopWidth:1,borderTopColor:theme.border,flexDirection:"row-reverse",alignItems:"center",justifyContent:"space-between"},locationTitle:{color:theme.text,fontSize:14,fontWeight:fonts.weight.bold,textAlign:"right"},locationSub:{color:theme.muted,fontSize:10,marginTop:3,textAlign:"right"},outline:{borderRadius:11,borderWidth:1,borderColor:theme.border,paddingHorizontal:13,paddingVertical:9},outlineText:{color:theme.text,fontSize:11,fontWeight:fonts.weight.bold},settingRow:{flexDirection:"row-reverse",alignItems:"center",justifyContent:"space-between"},settingTitle:{color:theme.text,fontSize:14,fontWeight:fonts.weight.bold,textAlign:"right"},settingSub:{color:theme.muted,fontSize:11,marginTop:3,textAlign:"right"},chevron:{fontSize:20,color:theme.muted},logout:{height:50,borderRadius:14,backgroundColor:theme.dangerSoft,alignItems:"center",justifyContent:"center"},logoutText:{color:theme.danger,fontWeight:fonts.weight.bold},error:{color:theme.danger,textAlign:"right",fontSize:11,marginTop:10},center:{flex:1,alignItems:"center",justifyContent:"center"}});