import AsyncStorage from '@react-native-async-storage/async-storage';
import{router,useLocalSearchParams}from'expo-router';
import{useEffect,useState}from'react';
import{Image,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import{SafeAreaView}from'react-native-safe-area-context';
import{theme}from'@/constants/theme';
import{BottomNav}from'@/components/BottomNav';
const API=(process.env.EXPO_PUBLIC_API_URL||'').replace(/\/$/,'');
type Chip={key?:string;label:string;active:boolean;onPress:()=>void};

export default function Restaurants(){
 const p=useLocalSearchParams<any>();
 const[q,setQ]=useState(String(p.q||'')),[category,setCategory]=useState(String(p.category||'')),[merchantType,setMerchantType]=useState(String(p.merchantType||'')),[badge,setBadge]=useState(String(p.badge||'')),[open,setOpen]=useState(''),[minRating,setMinRating]=useState(''),[maxMinutes,setMaxMinutes]=useState('');
 const[cats,setCats]=useState<any[]>([]),[badges,setBadges]=useState<any[]>([]),[types,setTypes]=useState<any[]>([]),[list,setList]=useState<any[]>([]),[favs,setFavs]=useState<string[]>([]);
 const[out,setOut]=useState(false),[locationRequired,setLocationRequired]=useState(false),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(false),[error,setError]=useState(''),[showFilters,setShowFilters]=useState(false);
 const load=async()=>{try{setError('');const t=await AsyncStorage.getItem('auth_token');if(!t)return router.replace('/auth');const qs=new URLSearchParams();if(q.trim())qs.set('q',q.trim());if(category)qs.set('category',category);if(merchantType)qs.set('merchantType',merchantType);if(badge)qs.set('badge',badge);if(open)qs.set('open',open);if(minRating)qs.set('minRating',minRating);if(maxMinutes)qs.set('maxMinutes',maxMinutes);const h={Authorization:'Bearer '+t};const[r,hc,f,tr]=await Promise.all([fetch(API+'/api/customer/eligible-restaurants?'+qs.toString(),{headers:h}),fetch(API+'/api/catalog/home',{headers:h}),fetch(API+'/api/customer/favorites',{headers:h}),fetch(API+'/api/customer/merchant-types/types',{headers:h})]);const d=await r.json(),hd=await hc.json(),fd=await f.json(),td=await tr.json();if(!r.ok)throw new Error(d.error||'تعذر تحميل الجهات');setList(d.restaurants||[]);setOut(Boolean(d.outOfRange));setLocationRequired(Boolean(d.locationRequired));setCats(hd.categories||[]);setBadges(hd.badges||[]);setFavs(fd.favorites||[]);setTypes(td.types||[])}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل الجهات')}finally{setLoading(false);setRefresh(false)}};
 useEffect(()=>{load()},[category,merchantType,badge,open,minRating,maxMinutes]);
 const favorite=async(id:string)=>{const t=await AsyncStorage.getItem('auth_token'),on=favs.includes(id);const r=await fetch(API+'/api/customer/favorites/'+id,{method:on?'DELETE':'POST',headers:{Authorization:'Bearer '+t}});if(r.ok)setFavs(x=>on?x.filter(v=>v!==id):[...x,id])};
 const clearFilters=()=>{setCategory('');setBadge('');setOpen('');setMinRating('');setMaxMinutes('')};const activeCount=[category,badge,open,minRating,maxMinutes].filter(Boolean).length;
 const quick:Chip[]=[{key:'open',label:'مفتوح الآن',active:open==='true',onPress:()=>setOpen(open==='true'?'':'true')},{key:'4',label:'★ 4+',active:minRating==='4',onPress:()=>setMinRating(minRating==='4'?'':'4')},{key:'20',label:'⚡ حتى 20 دقيقة',active:maxMinutes==='20',onPress:()=>setMaxMinutes(maxMinutes==='20'?'':'20')}];
 return <SafeAreaView style={s.safe}><View style={s.page}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={refresh} onRefresh={()=>{setRefresh(true);load()}}/>}>
 <View style={s.header}><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>→</Text></Pressable><View style={{flex:1}}><Text style={s.eyebrow}>اكتشف المتاح حولك</Text><Text style={s.title}>{merchantType?types.find(x=>String(x.id)===merchantType)?.name||'الجهات':'المطاعم والجهات'}</Text></View></View>
 <View style={s.search}><TextInput value={q} onChangeText={setQ} onSubmitEditing={load} placeholder="ابحث عن مطعم، متجر أو منتج..." placeholderTextColor={theme.muted} style={s.input} textAlign="right"/><Pressable onPress={load} style={s.searchBtn}><Text style={s.searchText}>⌕</Text></Pressable></View>
 {types.length>0&&<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.typeRow}><Pressable onPress={()=>setMerchantType('')} style={[s.typeChip,!merchantType&&s.typeChipOn]}><Text style={[s.typeText,!merchantType&&s.typeTextOn]}>الكل</Text></Pressable>{types.map(x=><Pressable key={x.id} onPress={()=>setMerchantType(String(x.id))} style={[s.typeChip,merchantType===String(x.id)&&s.typeChipOn]}><Text style={s.typeEmoji}>{x.icon||'🛍️'}</Text><Text style={[s.typeText,merchantType===String(x.id)&&s.typeTextOn]}>{x.name}</Text></Pressable>)}</ScrollView>}
 {!locationRequired&&!out&&<View style={s.quickBar}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.quickRow}>{quick.map(x=><FilterChip key={x.key} {...x}/>)}</ScrollView><Pressable onPress={()=>setShowFilters(!showFilters)} style={[s.filterButton,(showFilters||activeCount>0)&&s.filterButtonOn]}><Text style={[s.filterButtonText,(showFilters||activeCount>0)&&s.filterButtonTextOn]}>تصفية {activeCount?'('+activeCount+')':''}</Text></Pressable></View>}
 {showFilters&&!locationRequired&&!out&&<View style={s.filters}><FilterSection title="التصنيفات"><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filterRow}>{cats.map(x=><FilterChip key={x.id} label={x.name} active={category===x.name} onPress={()=>setCategory(category===x.name?'':x.name)}/>)}</ScrollView></FilterSection><FilterSection title="التقييم ووقت التجهيز"><View style={s.wrapRow}><FilterChip label="★ 4+" active={minRating==='4'} onPress={()=>setMinRating(minRating==='4'?'':'4')}/><FilterChip label="★ 3+" active={minRating==='3'} onPress={()=>setMinRating(minRating==='3'?'':'3')}/><FilterChip label="حتى 30 دقيقة" active={maxMinutes==='30'} onPress={()=>setMaxMinutes(maxMinutes==='30'?'':'30')}/></View></FilterSection>{badges.length>0&&<FilterSection title="وسوم مميزة"><View style={s.wrapRow}>{badges.map(x=><FilterChip key={x.id} label={(x.icon||'🏷️')+' '+x.name} active={badge===x.name} onPress={()=>setBadge(badge===x.name?'':x.name)}/>)}</View></FilterSection>}{activeCount>0&&<Pressable onPress={clearFilters} style={s.clear}><Text style={s.clearText}>مسح كل الفلاتر</Text></Pressable>}</View>}
 {locationRequired?<Notice icon="📍" title="حدد موقع التوصيل أولًا" text="نحتاج موقعك لمعرفة الجهات التي توصل لمنطقتك." action="تحديد الموقع" onPress={()=>router.push('/customer/location')}/>:out?<Notice icon="🚚" title="موقعك خارج نطاق التوصيل" text="جرّب تغيير عنوان التوصيل أو تواصل مع الدعم." action="تواصل مع الدعم" onPress={()=>router.push('/customer/support')}/>:<Results loading={loading} error={error} list={list} favs={favs} favorite={favorite}/>}
 </ScrollView><BottomNav role="customer"/></View></SafeAreaView>
}
function FilterChip({label,active,onPress}:Chip){return <Pressable onPress={onPress} style={[s.filterChip,active&&s.filterChipOn]}><Text style={[s.filterChipText,active&&s.filterChipTextOn]}>{label}</Text></Pressable>}
function FilterSection({title,children}:{title:string;children:any}){return <View style={s.filterSection}><Text style={s.filterTitle}>{title}</Text>{children}</View>}
function Notice({icon,title,text,action,onPress}:{icon:string;title:string;text:string;action:string;onPress:()=>void}){return <View style={s.notice}><Text style={s.noticeIcon}>{icon}</Text><Text style={s.noticeTitle}>{title}</Text><Text style={s.noticeText}>{text}</Text><Pressable onPress={onPress} style={s.primary}><Text style={s.primaryText}>{action}</Text></Pressable></View>}
function Results({loading,error,list,favs,favorite}:{loading:boolean;error:string;list:any[];favs:string[];favorite:(id:string)=>void}){if(loading)return <View style={s.center}><Text style={s.big}>⌛</Text><Text style={s.muted}>بنجيبلك أفضل الخيارات...</Text></View>;if(error)return <View style={s.center}><Text style={s.error}>{error}</Text></View>;if(!list.length)return <View style={s.center}><Text style={s.big}>🔎</Text><Text style={s.empty}>مفيش نتائج مطابقة حاليًا</Text><Text style={s.muted}>جرّب البحث أو غيّر الفلاتر</Text></View>;return <View style={s.results}>{list.map(r=>{const open=r.is_open!==false,icon=r.merchant_type==='pharmacy'?'💊':r.merchant_type==='supermarket'?'🛒':r.merchant_type==='grocery'?'🥫':r.merchant_type==='butcher'?'🥩':'🍴';return <Pressable key={r.id} onPress={()=>router.push('/customer/menu?restaurantId='+r.id)} style={s.card}><View style={s.cardTop}><View style={s.logoWrap}>{r.logo_url?<Image source={{uri:r.logo_url}} style={s.logo}/>:<Text style={s.logoEmoji}>{icon}</Text>}</View><View style={s.info}><View style={s.nameRow}><Text numberOfLines={1} style={s.name}>{r.name}</Text><View style={[s.status,open?s.statusOpen:s.statusClosed]}><Text style={[s.statusText,open?s.statusTextOpen:s.statusTextClosed]}>{open?'متاح':'مغلق'}</Text></View></View><Text numberOfLines={1} style={s.meta}>{r.area||r.address||'الموقع غير محدد'}</Text><View style={s.stats}><Text style={s.rating}>★ {Number(r.rating||0).toFixed(1)}</Text><Text style={s.dot}>•</Text><Text style={s.eta}>تجهيز {r.preparation_minutes||30} د</Text>{r.rating_count?<><Text style={s.dot}>•</Text><Text style={s.eta}>{r.rating_count} تقييم</Text></>:null}</View></View><Pressable onPress={(e:any)=>{e?.stopPropagation?.();favorite(r.id)}} style={s.heart}><Text style={[s.heartText,favs.includes(r.id)&&s.hearted]}>{favs.includes(r.id)?'♥':'♡'}</Text></Pressable></View>{(r.badges||[]).length>0&&<View style={s.badgeRow}>{(r.badges||[]).slice(0,3).map((b:any)=><View key={b.id} style={s.miniBadge}><Text style={s.miniText}>{b.icon||'🏷️'} {b.name}</Text></View>)}</View>}</Pressable>})}</View>}
const s=StyleSheet.create({
safe:{flex:1,backgroundColor:theme.background},page:{flex:1},content:{paddingHorizontal:16,paddingTop:10,paddingBottom:112},
header:{flexDirection:'row-reverse',alignItems:'center',gap:12,marginBottom:17},back:{width:46,height:46,borderRadius:16,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,alignItems:'center',justifyContent:'center'},backText:{fontSize:24,color:theme.text},eyebrow:{color:theme.muted,fontSize:10,fontWeight:'700',textAlign:'right'},title:{color:theme.text,fontSize:25,fontWeight:'900',textAlign:'right',marginTop:2},
search:{height:56,borderRadius:18,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,flexDirection:'row-reverse',alignItems:'center',padding:5},input:{flex:1,color:theme.text,paddingHorizontal:12,fontSize:12},searchBtn:{width:46,height:46,borderRadius:14,backgroundColor:theme.primary,alignItems:'center',justifyContent:'center'},searchText:{color:'#fff',fontSize:25,fontWeight:'900'},
typeRow:{gap:8,paddingTop:13,paddingBottom:5,flexDirection:'row-reverse'},typeChip:{minHeight:44,paddingHorizontal:12,borderRadius:15,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,flexDirection:'row-reverse',alignItems:'center',gap:6},typeChipOn:{backgroundColor:theme.primary,borderColor:theme.primary},typeEmoji:{fontSize:17},typeText:{color:theme.text,fontSize:10,fontWeight:'900'},typeTextOn:{color:'#fff'},
quickBar:{flexDirection:'row-reverse',alignItems:'center',gap:8,marginTop:13},quickRow:{gap:7,flex:1,flexDirection:'row-reverse'},filterButton:{height:38,paddingHorizontal:12,borderRadius:13,borderWidth:1,borderColor:theme.border,backgroundColor:theme.surface,justifyContent:'center'},filterButtonOn:{borderColor:theme.primary,backgroundColor:theme.primarySoft},filterButtonText:{color:theme.text,fontSize:10,fontWeight:'900'},filterButtonTextOn:{color:theme.primary},
filters:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:20,padding:13,marginTop:10},filterSection:{marginBottom:13},filterTitle:{color:theme.text,fontSize:12,fontWeight:'900',textAlign:'right',marginBottom:8},filterRow:{gap:7,flexDirection:'row-reverse'},wrapRow:{flexDirection:'row-reverse',flexWrap:'wrap',gap:7},filterChip:{minHeight:38,paddingHorizontal:12,borderRadius:13,borderWidth:1,borderColor:theme.border,backgroundColor:theme.background,alignItems:'center',justifyContent:'center'},filterChipOn:{backgroundColor:theme.primary,borderColor:theme.primary},filterChipText:{color:theme.text,fontSize:10,fontWeight:'800'},filterChipTextOn:{color:'#fff'},clear:{height:40,borderRadius:12,backgroundColor:theme.dangerSoft,alignItems:'center',justifyContent:'center'},clearText:{color:theme.danger,fontSize:11,fontWeight:'900'},
notice:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:22,padding:22,alignItems:'center',marginTop:28},noticeIcon:{fontSize:34},noticeTitle:{color:theme.text,fontSize:18,fontWeight:'900',marginTop:9},noticeText:{color:theme.muted,fontSize:11,textAlign:'center',lineHeight:18,marginTop:6},primary:{height:46,paddingHorizontal:22,borderRadius:14,backgroundColor:theme.primary,alignItems:'center',justifyContent:'center',marginTop:15},primaryText:{color:'#fff',fontWeight:'900'},
center:{alignItems:'center',justifyContent:'center',paddingVertical:90,gap:8},big:{fontSize:37},muted:{color:theme.muted,fontSize:11},empty:{color:theme.text,fontWeight:'900',fontSize:15},error:{color:theme.danger,textAlign:'center',fontWeight:'800'},
results:{marginTop:17,gap:10},card:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:21,padding:13},cardTop:{flexDirection:'row-reverse',alignItems:'center',gap:11},logoWrap:{width:66,height:66,borderRadius:19,backgroundColor:theme.surfaceAlt,alignItems:'center',justifyContent:'center',overflow:'hidden'},logo:{width:'100%',height:'100%'},logoEmoji:{fontSize:27},info:{flex:1,minWidth:0},nameRow:{flexDirection:'row-reverse',alignItems:'center',gap:7},name:{flex:1,color:theme.text,fontSize:15,fontWeight:'900',textAlign:'right'},status:{paddingHorizontal:7,paddingVertical:4,borderRadius:9},statusOpen:{backgroundColor:theme.successSoft},statusClosed:{backgroundColor:theme.dangerSoft},statusText:{fontSize:8,fontWeight:'900'},statusTextOpen:{color:theme.success},statusTextClosed:{color:theme.danger},meta:{color:theme.muted,fontSize:10,textAlign:'right',marginTop:4},stats:{flexDirection:'row-reverse',alignItems:'center',gap:5,marginTop:6},rating:{color:theme.warning,fontSize:10,fontWeight:'900'},eta:{color:theme.muted,fontSize:9,fontWeight:'800'},dot:{color:theme.border,fontSize:12},heart:{width:38,height:38,borderRadius:13,backgroundColor:theme.surfaceAlt,alignItems:'center',justifyContent:'center'},heartText:{fontSize:22,color:theme.muted},hearted:{color:theme.danger},badgeRow:{flexDirection:'row-reverse',gap:5,flexWrap:'wrap',marginTop:11,paddingTop:10,borderTopWidth:1,borderTopColor:theme.border},miniBadge:{paddingHorizontal:8,paddingVertical:5,borderRadius:10,backgroundColor:theme.background},miniText:{color:theme.text,fontSize:8,fontWeight:'800'}
});