import AsyncStorage from '@react-native-async-storage/async-storage';
import {useState}from'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import {SafeAreaView}from'react-native-safe-area-context';
import {router}from'expo-router';
import {theme}from'@/constants/theme';
const API=(process.env.EXPO_PUBLIC_API_URL||'').replace(/\/$/,'');
export default function SpecialOrder(){
 const [description,setDescription]=useState(''),[place,setPlace]=useState(''),[placeDescription,setPlaceDescription]=useState(''),[estimate,setEstimate]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async()=>{try{if(description.trim().length<3)return setError('اكتب تفاصيل الطلب بوضوح');setBusy(true);setError('');const t=await AsyncStorage.getItem('auth_token'),r=await fetch(API+'/api/special-orders',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+t},body:JSON.stringify({description:description.trim(),placeName:place.trim()||null,placeDescription:placeDescription.trim()||null,estimatedProductPrice:estimate.trim()?Number(estimate):null})}),d=await r.json();if(!r.ok)throw Error(d.error||'تعذر إرسال الطلب');router.back()}catch(e){setError(e instanceof Error?e.message:'تعذر إرسال الطلب')}finally{setBusy(false)}};
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>→</Text></Pressable><Text style={s.title}>📝 اطلب أي شيء</Text></View><Text style={s.sub}>اكتب الطلب كما تريد. يمكنك تحديد المكان والسعر التقريبي. السعر الحقيقي ورسوم التوصيل لن يتم حسابهما الآن؛ ستراجع الإدارة الطلب ثم يظهر لك العرض النهائي للموافقة.</Text><Pressable onPress={()=>router.push('/customer/special-orders')} style={s.my}><Text style={s.myText}>عرض طلباتي الخاصة</Text></Pressable>
 <Label t="ماذا تريد؟ *"/><TextInput value={description} onChangeText={setDescription} placeholder="مثال: علبة Aptamil رقم 2، ولو غير متوفر اتصل بي قبل شراء بديل..." placeholderTextColor={theme.muted} multiline style={[s.input,s.multi]} textAlign="right" textAlignVertical="top"/>
 <Label t="من أين تريد الطلب؟ (اختياري)"/><TextInput value={place} onChangeText={setPlace} placeholder="مثال: صيدلية النور" placeholderTextColor={theme.muted} style={s.input} textAlign="right"/>
 <Label t="اشرح مكان الجهة أو أي تفاصيل (اختياري)"/><TextInput value={placeDescription} onChangeText={setPlaceDescription} placeholder="مثال: بجوار مستشفى بنها الجامعي، المدخل من شارع..." placeholderTextColor={theme.muted} multiline style={[s.input,s.multiSmall]} textAlign="right" textAlignVertical="top"/>
 <View style={s.location}><Text style={s.locationTitle}>📍 موقع المكان (اختياري)</Text><Text style={s.locationText}>تم تجهيز النظام لاستقبال إحداثيات المكان، لكن اختيار Pin على الخريطة مؤجل مع تنفيذ الخرائط وGPS في المرحلة القادمة.</Text></View>
 <Label t="السعر التقريبي للمنتج (اختياري)"/><TextInput value={estimate} onChangeText={setEstimate} keyboardType="decimal-pad" placeholder="مثال: 150" placeholderTextColor={theme.muted} style={s.input} textAlign="right"/>
 <View style={s.notice}><Text style={s.noticeTitle}>كيف سيتم الحساب؟</Text><Text style={s.noticeText}>• السعر التقريبي يساعدنا فقط في فهم الطلب.</Text><Text style={s.noticeText}>• السعر النهائي ورسوم التوصيل = سيتم تحديدهما بعد المراجعة.</Text><Text style={s.noticeText}>• بعد التسعير يصلك عرض نهائي، ويمكنك الموافقة أو الإلغاء.</Text></View>
 {error?<Text style={s.error}>{error}</Text>:null}<Pressable disabled={busy} onPress={submit} style={s.primary}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>إرسال الطلب للمراجعة</Text>}</Pressable></ScrollView></SafeAreaView>
}
function Label({t}:{t:string}){return <Text style={s.label}>{t}</Text>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.background},page:{padding:17,paddingBottom:45},head:{flexDirection:'row-reverse',alignItems:'center',gap:10},back:{width:42,height:42,borderRadius:13,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,alignItems:'center',justifyContent:'center'},backText:{fontSize:22,color:theme.text},title:{color:theme.text,fontSize:24,fontWeight:'900',flex:1,textAlign:'right'},sub:{color:theme.muted,fontSize:11,textAlign:'right',lineHeight:19,marginTop:12},my:{alignSelf:'flex-end',marginTop:8,paddingHorizontal:10,paddingVertical:7,borderRadius:10,backgroundColor:theme.primarySoft},myText:{color:theme.primary,fontSize:10,fontWeight:'900'},label:{color:theme.text,fontWeight:'900',textAlign:'right',marginTop:16,marginBottom:7},input:{height:48,borderRadius:13,borderWidth:1,borderColor:theme.border,backgroundColor:theme.surface,color:theme.text,paddingHorizontal:12},multi:{height:115,paddingTop:12},multiSmall:{height:90,paddingTop:12},location:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:15,padding:12,marginTop:15},locationTitle:{color:theme.text,fontWeight:'900',textAlign:'right'},locationText:{color:theme.muted,fontSize:9,textAlign:'right',lineHeight:16,marginTop:5},notice:{backgroundColor:theme.primarySoft,borderRadius:15,padding:13,marginTop:16},noticeTitle:{color:theme.primary,fontWeight:'900',textAlign:'right',marginBottom:6},noticeText:{color:theme.text,fontSize:9,textAlign:'right',lineHeight:17},error:{color:theme.danger,textAlign:'right',marginTop:10,fontWeight:'800'},primary:{height:53,borderRadius:15,backgroundColor:theme.primary,alignItems:'center',justifyContent:'center',marginTop:14},primaryText:{color:'#fff',fontWeight:'900'}});