import AsyncStorage from '@react-native-async-storage/async-storage';
import {useCallback,useState}from'react';
import {ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View}from'react-native';
import {SafeAreaView}from'react-native-safe-area-context';
import {router,useFocusEffect}from'expo-router';
import {theme}from'@/constants/theme';
const API=(process.env.EXPO_PUBLIC_API_URL||'').replace(/\/$/,'');
const labels:any={pending_review:'قيد المراجعة',priced:'بانتظار موافقتك',customer_confirmed:'تم التأكيد',in_progress:'جاري التنفيذ',completed:'مكتمل',cancelled:'ملغي',rejected:'مرفوض'};
export default function SpecialOrders(){
 const [list,setList]=useState<any[]>([]),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(false),[error,setError]=useState('');
 const load=async()=>{try{const t=await AsyncStorage.getItem('auth_token'),r=await fetch(API+'/api/special-orders/mine',{headers:{Authorization:'Bearer '+t}}),d=await r.json();if(!r.ok)throw Error(d.error||'تعذر تحميل الطلبات');setList(d.specialOrders||[]);setError('')}catch(e){setError(e instanceof Error?e.message:'تعذر التحميل')}finally{setLoading(false);setRefresh(false)}};
 useFocusEffect(useCallback(()=>{load()},[]));
 const act=async(id:string,path:string)=>{try{const t=await AsyncStorage.getItem('auth_token'),r=await fetch(API+'/api/special-orders/'+id+'/'+path,{method:'PATCH',headers:{Authorization:'Bearer '+t}}),d=await r.json();if(!r.ok)throw Error(d.error||'تعذر تنفيذ العملية');await load()}catch(e){setError(e instanceof Error?e.message:'تعذر تنفيذ العملية')}};
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} refreshControl={<RefreshControl refreshing={refresh} onRefresh={()=>{setRefresh(true);load()}}/>}><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>→</Text></Pressable><View style={{flex:1}}><Text style={s.title}>طلباتي الخاصة</Text><Text style={s.sub}>تابع المراجعة والسعر النهائي ثم أكد موافقتك.</Text></View></View>
 <Pressable onPress={()=>router.push('/customer/special-order')} style={s.new}><Text style={s.newText}>+ إنشاء طلب خاص جديد</Text></Pressable>
 {loading?<View style={s.center}><ActivityIndicator color={theme.primary}/></View>:error?<Text style={s.error}>{error}</Text>:!list.length?<View style={s.empty}><Text style={s.emptyTitle}>لا توجد طلبات خاصة</Text><Text style={s.sub}>يمكنك طلب أي منتج أو شيء من أي مكان.</Text></View>:list.map(o=><View key={o.id} style={s.card}><View style={s.top}><Text style={s.status}>{labels[o.status]||o.status}</Text><Text style={s.date}>{new Date(o.created_at).toLocaleDateString('ar-EG')}</Text></View><Text style={s.desc}>{o.description}</Text>{o.place_name?<Text style={s.meta}>📍 {o.place_name}</Text>:null}{o.estimated_product_price!=null?<Text style={s.meta}>السعر التقريبي: {Number(o.estimated_product_price).toFixed(2)} ج.م</Text>:null}
 {o.status==='priced'?<View style={s.quote}><Text style={s.quoteTitle}>العرض النهائي</Text><Text style={s.line}>سعر المنتج: {Number(o.quoted_product_price||0).toFixed(2)} ج.م</Text><Text style={s.line}>رسوم التوصيل: {Number(o.quoted_delivery_fee||0).toFixed(2)} ج.م</Text><Text style={s.total}>الإجمالي: {Number(o.quoted_total||0).toFixed(2)} ج.م</Text><View style={s.actions}><Pressable onPress={()=>act(o.id,'confirm')} style={s.confirm}><Text style={s.actionText}>موافق</Text></Pressable><Pressable onPress={()=>act(o.id,'cancel')} style={s.cancel}><Text style={s.cancelText}>إلغاء</Text></Pressable></View></View>:null}</View>)}</ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.background},page:{padding:17,paddingBottom:45},head:{flexDirection:'row-reverse',alignItems:'center',gap:10},back:{width:42,height:42,borderRadius:13,backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,alignItems:'center',justifyContent:'center'},backText:{fontSize:22,color:theme.text},title:{color:theme.text,fontSize:24,fontWeight:'900',textAlign:'right'},sub:{color:theme.muted,fontSize:10,textAlign:'right',marginTop:4},new:{height:47,borderRadius:14,backgroundColor:theme.primary,alignItems:'center',justifyContent:'center',marginTop:15},newText:{color:'#fff',fontWeight:'900'},card:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:17,padding:12,marginTop:10},top:{flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center'},status:{color:theme.primary,fontSize:10,fontWeight:'900'},date:{color:theme.muted,fontSize:9},desc:{color:theme.text,fontWeight:'800',textAlign:'right',lineHeight:18,marginTop:9},meta:{color:theme.muted,fontSize:9,textAlign:'right',marginTop:5},quote:{backgroundColor:theme.primarySoft,borderRadius:13,padding:10,marginTop:10},quoteTitle:{color:theme.primary,fontWeight:'900',textAlign:'right'},line:{color:theme.text,fontSize:10,textAlign:'right',marginTop:5},total:{color:theme.primary,fontWeight:'900',fontSize:14,textAlign:'right',marginTop:7},actions:{flexDirection:'row-reverse',gap:7,marginTop:10},confirm:{flex:1,height:43,borderRadius:11,backgroundColor:theme.primary,alignItems:'center',justifyContent:'center'},cancel:{flex:1,height:43,borderRadius:11,borderWidth:1,borderColor:theme.border,alignItems:'center',justifyContent:'center'},actionText:{color:'#fff',fontWeight:'900'},cancelText:{color:theme.text,fontWeight:'900'},error:{color:theme.danger,textAlign:'right',marginTop:15},center:{padding:50,alignItems:'center'},empty:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:18,padding:25,alignItems:'center',marginTop:18},emptyTitle:{color:theme.text,fontSize:17,fontWeight:'900',marginBottom:4}});
