import AsyncStorage from "@react-native-async-storage/async-storage";
import {useLocalSearchParams} from "expo-router";
import {useEffect,useState} from "react";
import {StyleSheet,Text,View,ActivityIndicator} from "react-native";
import MapView,{Marker,Region} from "react-native-maps";
import {SafeAreaView} from "react-native-safe-area-context";
import {theme} from "@/constants/theme";
const API=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,"");
const labels:any={restaurant_pending:"المطعم بيراجع الطلب",confirmed:"تم قبول الطلب",preparing:"جاري تجهيز الطلب",ready:"الطلب جاهز للدليفري",assigned:"المندوب استلم الطلب",picked_up:"تم استلام الطلب",on_the_way:"المندوب في الطريق",delivered:"تم التسليم",restaurant_rejected:"المطعم رفض الطلب",admin_rejected:"الطلب مرفوض من الإدارة",cancelled:"الطلب ملغي"};
export default function CustomerTracking(){const {orderId}=useLocalSearchParams<{orderId?:string}>();const [order,setOrder]=useState<any>(null),[driver,setDriver]=useState<any>(null),[loading,setLoading]=useState(true),[region,setRegion]=useState<Region>({latitude:30.0444,longitude:31.2357,latitudeDelta:.3,longitudeDelta:.3});useEffect(()=>{let alive=true;const load=async()=>{try{const t=await AsyncStorage.getItem("auth_token");const h={Authorization:`Bearer ${t}`};const [a,b]=await Promise.all([fetch(API+"/api/orders/mine",{headers:h}),fetch(API+"/api/location/my-driver",{headers:h})]);const od=await a.json(),dd=await b.json();const found=(od.orders||[]).find((x:any)=>!orderId||x.id===orderId)||(od.orders||[])[0];if(alive){setOrder(found||null);setDriver(dd.driver||null);const d=dd.driver;if(d?.latitude!=null&&d?.longitude!=null)setRegion(x=>({...x,latitude:Number(d.latitude),longitude:Number(d.longitude)}))}}catch{}finally{if(alive)setLoading(false)}};load();const id=setInterval(load,5000);return()=>{alive=false;clearInterval(id)}},[orderId]);return <SafeAreaView style={s.safe}><View style={s.page}><Text style={s.title}>متابعة الطلب</Text>{loading?<ActivityIndicator color={theme.primary}/>:order?<><Text style={s.order}>طلب #{order.id.slice(0,8)}</Text><View style={s.statusBox}><Text style={s.status}>{labels[order.status]||order.status}</Text><Text style={s.total}>الإجمالي {Number(order.total_amount).toFixed(2)} ج.م</Text></View>{driver?<Text style={s.subtitle}>المندوب: {driver.full_name} • الموقع يتحدث كل 5 ثواني</Text>:<Text style={s.subtitle}>لا يوجد مندوب مسند للطلب حتى الآن</Text>}<MapView style={s.map} region={region}>{driver&&driver.latitude!=null&&<Marker coordinate={{latitude:Number(driver.latitude),longitude:Number(driver.longitude)}} title={driver.full_name} description="موقع مباشر"/>}{order.delivery_latitude!=null&&order.delivery_longitude!=null&&<Marker coordinate={{latitude:Number(order.delivery_latitude),longitude:Number(order.delivery_longitude)}} title="موقع التسليم"/>}</MapView></>:<Text style={s.subtitle}>لم يتم العثور على الطلب.</Text>}</View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.background},page:{padding:20,flex:1},title:{fontSize:29,fontWeight:"900",color:theme.text,textAlign:"right"},order:{fontSize:12,color:theme.muted,textAlign:"right",marginTop:5},statusBox:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:18,padding:16,marginTop:12,marginBottom:10},status:{fontSize:17,fontWeight:"900",color:theme.primary,textAlign:"right"},total:{fontSize:12,color:theme.text,textAlign:"right",marginTop:6},subtitle:{fontSize:12,color:theme.muted,textAlign:"right",marginBottom:12},map:{flex:1,minHeight:400,borderRadius:20}});